[[quotes]]
quote = "As long as you think your past is bad you must be improving"
author = "Louis C.K"

[[quotes]]
quote = "It's okay to have a bad day"
author = "Unknown"

[[quotes]]
quote = "We must all suffer from one of two pains: the pain of discipline or the pain of regret. The difference is discipline weighs ounces while regret weighs tons."
author = "Jim Rohn"

[[quotes]]
quote = "A ship in the harbor is safe. But that's not what ships are for."
author = "Unknown"

[[quotes]]
quote = "You have survived every single bad day so far"
author = "Unknown"

[[quotes]]
quote = "Please pay attention very carefully, because this is the truest thing a stranger will ever say to you: In the face of such hopelessness as our eventual, unavoidable death, there is little sense in not at least TRYING to accomplish all your wildest dreams in life."
author = "Kevin Smith"

[[quotes]]
quote = "At the age of 18, I made up my mind to never have another bad day in my life. I dove into a endless sea of gratitude from which I've never emerged."
author = "Patch Adams"

[[quotes]]
quote = "When something is important enough, you do it even if the odds are not in your favor."
author = "Elon Musk"

[[quotes]]
quote = """
Look in the MIRROR...
That's your COMPETITION."""
author = "Unknown"

[[quotes]]
quote = """
BE STRONG
You never know who you are inspiring"""
author = "Unknown"

[[quotes]]
quote = "The greatest success stories were created by people who recognized a problem & turned it into an opportunity."
author = "Joseph Sugarman"
