[[quotes]]
quote = "I never wake up today with yesterday's problems."
author = "Anthony Saleh"

[[quotes]]
quote = """
If you're going through hell,
KEEP GOING."""
author = "Winston Churchill"

[[quotes]]
quote = "Fear stops people from accomplishing their goals."
author = "Unknown"

[[quotes]]
quote = "The boundary between what can be and your life, is your ideas"
author = "Pat Waldron"

[[quotes]]
quote = "Throughout life people will make you mad, disrespect you and treat you bad. Let God deal with the things they do, cause hate in your heart will consume you too."
author = "Will Smith"

[[quotes]]
quote = """
There are three rules.
1. If you do not go after what you want, you will never have it.
2. If you do not ask, the answer will always be no.
3. If you do not step forward, you will remain in the same place."""
author = "Unknown"

[[quotes]]
quote = "If people are not laughing at your goals, your goals are too small"
author = "Asim Premji"

[[quotes]]
quote = "There are many wonderful things that will never be done if you do not do them."
author = "Charles D Gill"

[[quotes]]
quote = "To the world you may be one person, but to one person you may be the world."
author = "Dr. Suess"

[[quotes]]
quote = "It's never too late to be whoever you want to be. I hope you live a life you're proud of, And if you find that you're not, I hope you have the strength to start over."
author = "F. Scott Fitzgerald"

[[quotes]]
quote = "Just because you took longer than others, doesn’t mean you failed."
author = "Unknown"
