[[quotes]]
quote = "Try not to become a person of success, but rather try to become a person of value."
author = "Albert Einstein"

[[quotes]]
quote = "Great minds discuss ideas; average minds discuss events; small minds discuss people."
author = "Eleanor Roosevelt"

[[quotes]]
quote = "I have not failed. I've just found 10,000 ways that won't work."
author = "Thomas A. Edison"

[[quotes]]
quote = "If you don't value your time, neither will others. Stop giving away your time and talents--start charging for it."
author = "Kim Garst"

[[quotes]]
quote = "A successful man is one who can lay a firm foundation with the bricks others have thrown at him."
author = "David Brinkley"

[[quotes]]
quote = "No one can make you feel inferior without your consent."
author = "Eleanor Roosevelt"

[[quotes]]
quote = "The whole secret of a successful life is to find out what is one's destiny to do, and then do it."
author = "Henry Ford"

[[quotes]]
quote = "You learn more from failure than from success. Don’t let it stop you. Failure builds character."
author = "Unknown"

[[quotes]]
quote = "The ones who are crazy enough to think they can change the world, are the ones who do."
author = "Unknown"

[[quotes]]
quote = "Don't raise your voice, improve your argument."
author = "Unknown"

[[quotes]]
quote = "What seems to us as bitter trials are often blessings in disguise."
author = "Oscar Wilde"
