[[quotes]]
quote = "Success is dependent on effort."
author = "Sophocles"

[[quotes]]
quote = "I think if there's something one needs to change with oneself, it doesn't have to happen in the New Year. You can do that any time you please - not that it's not a good inspirational tactic for the people that it works for."
author = "Brittany Murphy"

[[quotes]]
quote = "Courage, my friends; 'tis not too late to build a better world."
author = "Tommy Douglas"

[[quotes]]
quote = "Don't be afraid of failure; be afraid of petty success."
author = "Maude Adams"

[[quotes]]
quote = "I'll tell you, there is nothing better in life than being a late bloomer. I believe that success can happen at any time and at any age."
author = "Salma Hayek"

[[quotes]]
quote = "Miracles are a retelling in small letters of the very same story which is written across the whole world in letters too large for some of us to see."
author = "C. S. Lewis"

[[quotes]]
quote = "The will to persevere is often the difference between failure and success."
author = "David Sarnoff"

[[quotes]]
quote = "I attribute my success to my mental approach to the game. I have always been a serious student of umpiring. I enjoy studying rules, situations, and positioning."
author = "Jim Evans"

[[quotes]]
quote = "Had I not come out with an inspirational CD, you perhaps would have never known that I feel like I feel, that all songs, all the music I've ever done is a gift from God."
author = "Smokey Robinson"

[[quotes]]
quote = "We just want to win. That's the bottom line. I think a lot of times people may become content with one championship or a little bit of success, but we don't really reflect on what we've done in the past. We focus on the present."
author = "Derek Jeter"

[[quotes]]
quote = "I'm lucky to be part of a team who help to make me look good, and they deserve as much of the credit for my success as I do for the hard work we have all put in on the training ground."
author = "Lionel Messi"
