[[quotes]]
quote = "Success consists of getting up just one more time than you fall."
author = "Oliver Goldsmith"

[[quotes]]
quote = "In order that people may be happy in their work, these three things are needed: They must be fit for it. They must not do too much of it. And they must have a sense of success in it."
author = "John Ruskin"

[[quotes]]
quote = "The one thing that I know is that you win with good people."
author = "Don Shula"

[[quotes]]
quote = "I have looked into your eyes with my eyes. I have put my heart near your heart."
author = "Pope John XXIII"

[[quotes]]
quote = "I can honestly say that I was never affected by the question of the success of an undertaking. If I felt it was the right thing to do, I was for it regardless of the possible outcome."
author = "Golda Meir"

[[quotes]]
quote = "Fun opens the doors to creativity, which then leads to inspiration, which then births passion, which all together equals both happiness and success!"
author = "Rachele Brooke Smith"

[[quotes]]
quote = "Architecture is not an inspirational business, it's a rational procedure to do sensible and hopefully beautiful things; that's all."
author = "Harry Seidler"

[[quotes]]
quote = "Every person who wins in any undertaking must be willing to cut all sources of retreat. Only by doing so can one be sure of maintaining that state of mind known as a burning desire to win - essential to success."
author = "Napoleon Hill"

[[quotes]]
quote = "Encouragement of higher education for our youth is critical to the success of our collective future."
author = "Charles B. Rangel"

[[quotes]]
quote = "The secret of my success is a two word answer: Know people."
author = "Harvey S. Firestone"

[[quotes]]
quote = "It is by acts and not by ideas that people live."
author = "Anatole France"
