[[quotes]]
quote = "Defeat is not the worst of failures. Not to have tried is the true failure."
author = "George Edward Woodberry"

[[quotes]]
quote = "What drives success, and the most successful students, is internal motivation."
author = "Vivienne Ming"

[[quotes]]
quote = "Success is the child of drudgery and perseverance. It cannot be coaxed or bribed; pay the price and it is yours."
author = "Orison Swett Marden"

[[quotes]]
quote = "Our time here is magic! It's the only space you have to realize whatever it is that is beautiful, whatever is true, whatever is great, whatever is potential, whatever is rare, whatever is unique, in. It's the only space."
author = "Ben Okri"

[[quotes]]
quote = "Your talent is God's gift to you. What you do with it is your gift back to God."
author = "Leo Buscaglia"

[[quotes]]
quote = "For true success ask yourself these four questions: Why? Why not? Why not me? Why not now?"
author = "James Allen"

[[quotes]]
quote = "Even successful musicians have had periods where people say they suck and no one likes them, even after they've had periods of great success. So I think it's like you just gotta do you and try to stay motivated. Until, you know, you decide to stay home and make spaghetti all day."
author = "K. Flay"

[[quotes]]
quote = "We are taught to consume. And that's what we do. But if we realized that there really is no reason to consume, that it's just a mind set, that it's just an addiction, then we wouldn't be out there stepping on people's hands climbing the corporate ladder of success."
author = "River Phoenix"

[[quotes]]
quote = "I wish that the Indians believed me a god, for upon the report of an enemy's valor oftentimes depends the success of a battle, and false reports have many times done as great things as true courage and resolution."
author = "Alexander the Great"

[[quotes]]
quote = "Men judge us by the success of our efforts. God looks at the efforts themselves."
author = "Charlotte Bronte"

[[quotes]]
quote = "I think there's an awful lot of noise about the Church being persecuted but there is a more real issue that the conventional churches face - that the people who are really driving their revival and success believe in an old-time religion which, in my view, is incompatible with a modern, multi-ethnic, multicultural society."
author = "Trevor Phillips"
