[[quotes]]
quote = "You never know when some small thing will lead to a big idea. Travel is very inspirational - but it's in the ordinary that I find my themes of love and work and family."
author = "Adriana Trigiani"

[[quotes]]
quote = "Without craftsmanship, inspiration is a mere reed shaken in the wind."
author = "Johannes Brahms"

[[quotes]]
quote = "Success in its highest and noblest form calls for peace of mind and enjoyment and happiness which come only to the man who has found the work that he likes best."
author = "Napoleon Hill"

[[quotes]]
quote = "I am very conscious of who I am as an artist and as an inspirational person."
author = "R. Kelly"

[[quotes]]
quote = "He conquers who endures."
author = "Persius"

[[quotes]]
quote = "Motivation will almost always beat mere talent."
author = "Norman Ralph Augustine"

[[quotes]]
quote = "Think twice before you speak, because your words and influence will plant the seed of either success or failure in the mind of another."
author = "Napoleon Hill"

[[quotes]]
quote = "Ambition is the path to success. Persistence is the vehicle you arrive in."
author = "Bill Bradley"

[[quotes]]
quote = "The ladder of success is never crowded at the top."
author = "Napoleon Hill"

[[quotes]]
quote = "The successful man will profit from his mistakes and try again in a different way."
author = "Dale Carnegie"

[[quotes]]
quote = "Success in life is founded upon attention to the small things rather than to the large things; to the every day things nearest to us rather than to the things that are remote and uncommon."
author = "Booker T. Washington"
