[[quotes]]
quote = "What I have in common with the character in 'Truman' is this incredible need to please people. I feel like I want to take care of everyone and I also feel this terrible guilt if I am unable to. And I have felt this way ever since all this success started."
author = "Jim Carrey"

[[quotes]]
quote = "Thelonious Monk was one of the musicians I most connected with early on. I'm a huge Betty Carter fan, and the way that Abbey Lincoln and Shirley Horn grew immensely from the time they were young is so inspirational."
author = "Cecile McLorin Salvant"

[[quotes]]
quote = "Not on one strand are all life's jewels strung."
author = "William Morris"

[[quotes]]
quote = "In order to attain the impossible, one must attempt the absurd."
author = "Miguel de Cervantes"

[[quotes]]
quote = "The historical basis for the gap between the black middle class and underclass shows that ending discrimination, by itself, would not eradicate black poverty and dysfunction. We also need intervention to promulgate a middle-class ethic of success among the poor, while expanding opportunities for economic betterment."
author = "Henry Louis Gates"

[[quotes]]
quote = "My parents are very proud of my success but still worry, as I'm in a profession where there is no guarantee of work. They have always supported my decision to go into acting, but there have been tough times work-wise."
author = "David Harewood"

[[quotes]]
quote = "Keep all special thoughts and memories for lifetimes to come. Share these keepsakes with others to inspire hope and build from the past, which can bridge to the future."
author = "Mattie Stepanek"

[[quotes]]
quote = "It is very important to know who you are. To make decisions. To show who you are."
author = "Malala Yousafzai"

[[quotes]]
quote = "Self-belief and hard work will always earn you success."
author = "Virat Kohli"

[[quotes]]
quote = "I have had success throughout the years. Some of the hard rock bands today don't have the history that I have."
author = "Gary Cherone"

[[quotes]]
quote = "My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style."
author = "Maya Angelou"
