[[quotes]]
quote = "The survival of liberty in our land increasingly depends on the success of liberty in other lands. The best hope for peace in our world is the expansion of freedom in all the world."
author = "Bill Frist"

[[quotes]]
quote = "I really think that it's disgusting that Paris is the only place where it is illegal for paps to follow you around. It actually took someone losing their life - Diana, an inspirational woman - and then it changed, but they still won't change it in London! It's horrible!"
author = "Cara Delevingne"

[[quotes]]
quote = "Lord knows, every day is not a success, every year is not a success. You have to celebrate the good."
author = "Reese Witherspoon"

[[quotes]]
quote = "God always gives His best to those who leave the choice with him."
author = "Jim Elliot"

[[quotes]]
quote = "God has already done everything He's going to do. The ball is now in your court. If you want success, if you want wisdom, if you want to be prosperous and healthy, you're going to have to do more than meditate and believe; you must boldly declare words of faith and victory over yourself and your family."
author = "Joel Osteen"

[[quotes]]
quote = "Success in almost any field depends more on energy and drive than it does on intelligence. This explains why we have so many stupid leaders."
author = "Sloan Wilson"

[[quotes]]
quote = "The success and the failure are not my concern, but His."
author = "Joseph Barber Lightfoot"

[[quotes]]
quote = "I do love to eavesdrop. It's inspirational, not only for subject matter but for actual dialogue, the way people talk."
author = "Lynda Barry"

[[quotes]]
quote = "Every success story has a parent who says, 'over my dead body.' Every success story has an old person who walks up to you and says, when you're acting the fool, 'you know I worry about you sometimes.'"
author = "Bill Cosby"

[[quotes]]
quote = "Success in business today requires real-time, mobile access to business opportunities."
author = "Bob McDonnell"

[[quotes]]
quote = "Management is efficiency in climbing the ladder of success; leadership determines whether the ladder is leaning against the right wall."
author = "Stephen Covey"
