[[quotes]]
quote = "If you accept the expectations of others, especially negative ones, then you never will change the outcome."
author = "Michael Jordan"

[[quotes]]
quote = "We convince by our presence."
author = "Walt Whitman"

[[quotes]]
quote = "Always desire to learn something useful."
author = "Sophocles"

[[quotes]]
quote = "In the United States there's a Puritan ethic and a mythology of success. He who is successful is good. In Latin countries, in Catholic countries, a successful person is a sinner."
author = "Umberto Eco"

[[quotes]]
quote = "If I have seen further than others, it is by standing upon the shoulders of giants."
author = "Isaac Newton"

[[quotes]]
quote = "I think the biggest challenge is to continue on the same path. I think it's easy to become complacent from the success you've had."
author = "Jason Derulo"

[[quotes]]
quote = "The dog that trots about finds a bone."
author = "Golda Meir"

[[quotes]]
quote = "The key is to keep company only with people who uplift you, whose presence calls forth your best."
author = "Epictetus"

[[quotes]]
quote = "Flaming enthusiasm, backed up by horse sense and persistence, is the quality that most frequently makes for success."
author = "Dale Carnegie"

[[quotes]]
quote = "Every day we should hear at least one little song, read one good poem, see one exquisite picture, and, if possible, speak a few sensible words."
author = "Johann Wolfgang von Goethe"

[[quotes]]
quote = "Noble deeds that are concealed are most esteemed."
author = "Blaise Pascal"
