[[quotes]]
quote = "I wrote '('Til) I Kissed You' about a girl I met in Australia. Her name was Lilian, and she was very, very inspirational. I was married, but... I wrote the song about her on the way back home."
author = "Don Everly"

[[quotes]]
quote = "We learned about gratitude and humility - that so many people had a hand in our success, from the teachers who inspired us to the janitors who kept our school clean... and we were taught to value everyone's contribution and treat everyone with respect."
author = "Michelle Obama"

[[quotes]]
quote = "I'd like to one day be featured on a list of inspirational people who have made a difference in the world, whether it be helping underprivileged people or putting an end to the poaching of wildlife in Africa."
author = "Candice Swanepoel"

[[quotes]]
quote = "A compliment is something like a kiss through a veil."
author = "Victor Hugo"

[[quotes]]
quote = "To get down to the quick of it, respect motivates me - not success."
author = "Hugh Jackman"

[[quotes]]
quote = "It's how you deal with failure that determines how you achieve success."
author = "Charlotte Whitton"

[[quotes]]
quote = "Success consists in being successful, not in having potential for success. Any wide piece of ground is the potential site of a palace, but there's no palace till it's built."
author = "Fernando Pessoa"

[[quotes]]
quote = "That should be the measure of success for everyone. It's not money, it's not fame, it's not celebrity; my index of success is happiness."
author = "Lupe Fiasco"

[[quotes]]
quote = "Within the hearts men, loyalty and consideration are esteemed greater than success."
author = "Bryant H. McGill"

[[quotes]]
quote = "Communication - the human connection - is the key to personal and career success."
author = "Paul J. Meyer"

[[quotes]]
quote = "You have to learn the rules of the game. And then you have to play better than anyone else."
author = "Unknown"
