[[quotes]]
quote = "A tragic irony of life is that we so often achieve success or financial independence after the chief reason for which we sought it has passed away."
author = "Ellen Glasgow"

[[quotes]]
quote = "God sleeps in the minerals, awakens in plants, walks in animals, and thinks in man."
author = "Arthur Young"

[[quotes]]
quote = "True leaders don't invest in buildings. Jesus never built a building. They invest in people. Why? Because success without a successor is failure. So your legacy should not be in buildings, programs, or projects; your legacy must be in people."
author = "Myles Munroe"

[[quotes]]
quote = "Success is never final, failure is never fatal. It's courage that counts."
author = "John Wooden"

[[quotes]]
quote = "Be faithful to that which exists within yourself."
author = "Andre Gide"

[[quotes]]
quote = "All those who are around me are the bridge to my success, so they are all important."
author = "Manny Pacquiao"

[[quotes]]
quote = "Success is about dedication. You may not be where you want to be or do what you want to do when you're on the journey. But you've got to be willing to have vision and foresight that leads you to an incredible end."
author = "Usher"

[[quotes]]
quote = "You just can't beat the person who never gives up."
author = "Babe Ruth"

[[quotes]]
quote = "Success in any endeavor depends on the degree to which it is an expression of your true self."
author = "Ralph Marston"

[[quotes]]
quote = "Perfection is not attainable, but if we chase perfection we can catch excellence."
author = "Vince Lombardi"

[[quotes]]
quote = "Anybody who succeeds is helping people. The secret to success is find a need and fill it; find a hurt and heal it; find a problem and solve it."
author = "Robert H. Schuller"
