[[quotes]]
quote = "Stem cell research holds enormous promise for easing human suffering, and federal support is critical to its success."
author = "Tom Harkin"

[[quotes]]
quote = "The keys to brand success are self-definition, transparency, authenticity and accountability."
author = "Simon Mainwaring"

[[quotes]]
quote = "Remember you will not always win. Some days, the most resourceful individual will taste defeat. But there is, in this case, always tomorrow - after you have done your best to achieve success today."
author = "Maxwell Maltz"

[[quotes]]
quote = "Young man, the secret of my success is that at early age I discovered that I was not God."
author = "Oliver Wendell Holmes, Jr."

[[quotes]]
quote = "I think it's way harder when you have success, 'cause people tend to not treat you the same or look at you the same because they see the success or the money you make."
author = "Meek Mill"

[[quotes]]
quote = "Nothing succeeds like success."
author = "Alexandre Dumas"

[[quotes]]
quote = "Always remember that striving and struggle precede success, even in the dictionary."
author = "Sarah Ban Breathnach"

[[quotes]]
quote = "I was sure I'd set the world on fire, and it was hard for a young feller like me to realize the truth - that I hadn't set the world on fire, and I was totally unprepared to handle the consequences if 'The Big Trail' had been a success and launched me as a star."
author = "John Wayne"

[[quotes]]
quote = "If you can figure out my success on the screen, you're a better man than I."
author = "Alan Ladd"

[[quotes]]
quote = "What were once only hopes for the future have now come to pass; it is almost exactly 13 years since the overwhelming majority of people in Ireland and Northern Ireland voted in favour of the agreement signed on Good Friday 1998, paving the way for Northern Ireland to become the exciting and inspirational place that it is today."
author = "Queen Elizabeth II"

[[quotes]]
quote = "The two most important requirements for major success are: first, being in the right place at the right time, and second, doing something about it."
author = "Ray Kroc"
