[[quotes]]
quote = "The meaning of life is to find your gift. The purpose of life is to give it away."
author = "Unknown"

[[quotes]]
quote = "The distance between insanity and genius is measured only by success."
author = "Bruce Feirstein"

[[quotes]]
quote = "When you stop chasing the wrong things, you give the right things a chance to catch you."
author = "Lolly Daskal"

[[quotes]]
quote = "I believe that the only courage anybody ever needs is the courage to follow your own dreams."
author = "Oprah Winfrey"

[[quotes]]
quote = "No masterpiece was ever created by a lazy artist."
author = "Unknown"

[[quotes]]
quote = "Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you."
author = "Nathaniel Hawthorne"

[[quotes]]
quote = "If you can't explain it simply, you don't understand it well enough."
author = "Albert Einstein"

[[quotes]]
quote = "Blessed are those who can give without remembering and take without forgetting."
author = "Unknown"

[[quotes]]
quote = "Do one thing every day that scares you."
author = "Unknown"

[[quotes]]
quote = "What's the point of being alive if you don't at least try to do something remarkable."
author = "Unknown"

[[quotes]]
quote = "Life is not about finding yourself. Life is about creating yourself."
author = "Lolly Daskal"
