[[quotes]]
quote = "No foreign policy - no matter how ingenious - has any chance of success if it is born in the minds of a few and carried in the hearts of none."
author = "Henry Kissinger"

[[quotes]]
quote = "The secrets of success are a good wife and a steady job. My wife told me."
author = "Howard Nemerov"

[[quotes]]
quote = "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time."
author = "Thomas A. Edison"

[[quotes]]
quote = "Once we believe in ourselves, we can risk curiosity, wonder, spontaneous delight, or any experience that reveals the human spirit."
author = "e. e. cummings"

[[quotes]]
quote = "I want to make this world perfect."
author = "Malala Yousafzai"

[[quotes]]
quote = "At the end of the day, you are solely responsible for your success and your failure. And the sooner you realize that, you accept that, and integrate that into your work ethic, you will start being successful. As long as you blame others for the reason you aren't where you want to be, you will always be a failure."
author = "Erin Cummings"

[[quotes]]
quote = "Personal relationships are the fertile soil from which all advancement, all success, all achievement in real life grows."
author = "Ben Stein"

[[quotes]]
quote = "If everyone is moving forward together, then success takes care of itself."
author = "Henry Ford"

[[quotes]]
quote = "Pursue one great decisive aim with force and determination."
author = "Carl von Clausewitz"

[[quotes]]
quote = "Joy descends gently upon us like the evening dew, and does not patter down like a hailstorm."
author = "Jean Paul"

[[quotes]]
quote = "Often, these downplay the power of cultural imperialism - in that sense, playing the game of US interests - by reassuring us that the global success of American mass culture is not as bad as all that."
author = "Fredric Jameson"
