[[quotes]]
quote = "As knowledge increases, wonder deepens."
author = "Charles Morgan"

[[quotes]]
quote = "Success isn't everything but it makes a man stand straight."
author = "Lillian Hellman"

[[quotes]]
quote = "I am highly offended by the total lack of acknowledgement of my contribution to Laker success."
author = "Kareem Abdul-Jabbar"

[[quotes]]
quote = "You see countries like India really investing in their space program because they see it as inspirational and good for their economy."
author = "Ellen Stofan"

[[quotes]]
quote = "My dad is too cute. Every morning, he sends me one motivational quote. I have a folder full of all his quotes."
author = "Alia Bhatt"

[[quotes]]
quote = "A #2 pencil and a dream can take you anywhere."
author = "Joyce Meyer"

[[quotes]]
quote = "Learning to celebrate success is a key component of learning how to win in the market."
author = "Douglas Conant"

[[quotes]]
quote = "You have to make it happen."
author = "Denis Diderot"

[[quotes]]
quote = "Past success is no guarantee of future success, so I have learned to be an entrepreneur. I began to produce and direct my own projects."
author = "Ian Ziering"

[[quotes]]
quote = "Success usually comes to those who are too busy to be looking for it."
author = "Henry David Thoreau"

[[quotes]]
quote = "There's no secret about success. Did you ever know a successful man who didn't tell you about it?"
author = "Kin Hubbard"
