[[quotes]]
quote = "What is called genius is the abundance of life and health."
author = "Henry David Thoreau"

[[quotes]]
quote = "Earn your success based on service to others, not at the expense of others."
author = "H. Jackson Brown, Jr."

[[quotes]]
quote = "Our limitations and success will be based, most often, on your own expectations for ourselves. What the mind dwells upon, the body acts upon."
author = "Denis Waitley"

[[quotes]]
quote = "Knock the 't' off the 'can't'"
author = "George Reeves"

[[quotes]]
quote = "Success consists of going from failure to failure without loss of enthusiasm."
author = "Winston Churchill"

[[quotes]]
quote = "Thought is the wind, knowledge the sail, and mankind the vessel."
author = "Augustus Hare"

[[quotes]]
quote = "Begin to be now what you will be hereafter."
author = "William James"

[[quotes]]
quote = "Success consecrates the most offensive crimes."
author = "Lucius Annaeus Seneca"

[[quotes]]
quote = "Success is tricky to deal with, both professionally and in your personal life."
author = "Ewan McGregor"

[[quotes]]
quote = "I've worked too hard and too long to let anything stand in the way of my goals. I will not let my teammates down and I will not let myself down."
author = "Mia Hamm"

[[quotes]]
quote = "You will be a failure, until you impress the subconscious with the conviction you are a success. This is done by making an affirmation which 'clicks.'"
author = "Florence Scovel Shinn"
