[[quotes]]
quote = "'No one can make you successful; the will to success comes from within.' I've made this my motto. I've internalized it to the point of understanding that the success of my actions and/or endeavors doesn't depend on anyone else, and that includes a possible failure."
author = "Fabrizio Moreira"

[[quotes]]
quote = "I love inspirational R&B, like Mary J. Blige and Jennifer Hudson. I want to do that. That kind of music stays with you."
author = "Ashthon Jones"

[[quotes]]
quote = "You just hope that you will get the opportunity to do what you love and pay your bills, and that is being a success as an actor."
author = "Debra Messing"

[[quotes]]
quote = "Creative risk taking is essential to success in any goal where the stakes are high. Thoughtless risks are destructive, of course, but perhaps even more wasteful is thoughtless caution which prompts inaction and promotes failure to seize opportunity."
author = "Gary Ryan Blair"

[[quotes]]
quote = "Vitality shows in not only the ability to persist but the ability to start over."
author = "F. Scott Fitzgerald"

[[quotes]]
quote = "Expect problems and eat them for breakfast."
author = "Alfred A. Montapert"

[[quotes]]
quote = "Awards are not the only markers of success; I don't judge myself just based on them. I believe that each cinema-goer has his own mental trophies."
author = "Fan Bingbing"

[[quotes]]
quote = "I think that the reason for my success is that I am really not aspirational. I am inspirational in that the people at home feel like they can really relate to me."
author = "Rosie O'Donnell"

[[quotes]]
quote = "All you need is the plan, the road map, and the courage to press on to your destination."
author = "Earl Nightingale"

[[quotes]]
quote = "Success is a state of mind. If you want success, start thinking of yourself as a success."
author = "Joyce Brothers"

[[quotes]]
quote = "Do not weep; do not wax indignant. Understand."
author = "Baruch Spinoza"
