[[quotes]]
quote = "Barack Obama's inspirational whoosh to the presidency in 2008 was unusual. Most campaigns are less exhilarating; indeed, they are downright disappointing - until someone wins."
author = "Joe Klein"

[[quotes]]
quote = "If you could only love enough, you could be the most powerful person in the world."
author = "Emmet Fox"

[[quotes]]
quote = "A great secret of success is to go through life as a man who never gets used up."
author = "Albert Schweitzer"

[[quotes]]
quote = "Space exploration is important research to our economic and national defense, and America's space program is a symbol of our success as a scientifically and technologically advanced nation."
author = "Randy Forbes"

[[quotes]]
quote = "Let your life lightly dance on the edges of Time like dew on the tip of a leaf."
author = "Rabindranath Tagore"

[[quotes]]
quote = "I believe that one key to success is to accept truth, no matter how it's spoken."
author = "Robert Kiyosaki"

[[quotes]]
quote = "The undertaking of a new action brings new strength."
author = "Richard L. Evans"

[[quotes]]
quote = "The foundation of success in life is good health: that is the substratum fortune; it is also the basis of happiness. A person cannot accumulate a fortune very well when he is sick."
author = "P. T. Barnum"

[[quotes]]
quote = "I worked at The Old Globe Theater under the great baton of Craig Noel. One of the great theater heroes that we have. He was so great and so inspirational. I think I did 'Antony and Cleopatra' and 'The Taming of the Shrew'. I lived in Ocean Beach, and my rent was $140 a month."
author = "Jeffrey Tambor"

[[quotes]]
quote = "A man has to learn that he cannot command things, but that he can command himself; that he cannot coerce the wills of others, but that he can mold and master his own will: and things serve him who serves Truth; people seek guidance of him who is master of himself."
author = "James Allen"

[[quotes]]
quote = "Learning how to be still, to really be still and let life happen - that stillness becomes a radiance."
author = "Morgan Freeman"
