[[quotes]]
quote = "With the new day comes new strength and new thoughts."
author = "Eleanor Roosevelt"

[[quotes]]
quote = "Try to look at your weakness and convert it into your strength. That's success."
author = "Zig Ziglar"

[[quotes]]
quote = "Success is getting what you want. Happiness is wanting what you get."
author = "Dale Carnegie"

[[quotes]]
quote = "You know you are on the road to success if you would do your job, and not be paid for it."
author = "Oprah Winfrey"

[[quotes]]
quote = "We've been surrounded by images of space our whole lives, from the speculative images of science fiction to the inspirational visions of artists to the increasingly beautiful pictures made possible by complex technologies. But whilst we have an overwhelmingly vivid visual understanding of space, we have no sense of what space sounds like."
author = "Honor Harger"

[[quotes]]
quote = "To this day, just always treat people the way you want to be treated. Whether it's family or friends or co-workers, I think it's the most important thing. Whether you have success or don't have it, whether you're a good person is all that matters."
author = "Brenda Song"

[[quotes]]
quote = "Success is not a place at which one arrives but rather the spirit with which one undertakes and continues the journey."
author = "Alex Noble"

[[quotes]]
quote = "I would love to be a guest on a talk show or a panel that shows women who have been on reality shows who've had success, to prove to audiences that you don't have to be a fool to become successful."
author = "NeNe Leakes"

[[quotes]]
quote = "Growing up, in church we had the homily; at home it's what I call the 'momily' - the inspirational and instructive mom-isms that every family has."
author = "Christine Pelosi"

[[quotes]]
quote = "Wherever you are - be all there."
author = "Jim Elliot"

[[quotes]]
quote = "Everyone who achieves success in a great venture, solves each problem as they came to it. They helped themselves. And they were helped through powers known and unknown to them at the time they set out on their voyage. They keep going regardless of the obstacles they met."
author = "W. Clement Stone"
