[[quotes]]
quote = "The power of pop culture stories should not be underestimated, and there is an enormous potential for inspirational stories that can have a positive, transformative effect on our lives."
author = "Anita Sarkeesian"

[[quotes]]
quote = "I have always believed, and I still believe, that whatever good or bad fortune may come our way we can always give it meaning and transform it into something of value."
author = "Hermann Hesse"

[[quotes]]
quote = "Choose something you like to do. I know it's a cliche, and you've heard it over and over. But the reason is, you're going to have to work long and hard to achieve any success. You better like it or life is going to be terrible."
author = "Bill Kurtis"

[[quotes]]
quote = "I attribute my success to this - I never gave or took any excuse."
author = "Florence Nightingale"

[[quotes]]
quote = "I believe in the city as a natural human environment, but we must humanize it. It's art that will re-define public space in the 21st Century. We can make our cities diverse, inspirational places by putting art, dance and performance in all its forms into the matrix of street life."
author = "Antony Gormley"

[[quotes]]
quote = "There is nothing more difficult to take in hand, more perilous to conduct, or more uncertain in its success, than to take the lead in the introduction of a new order of things."
author = "Niccolo Machiavelli"

[[quotes]]
quote = "If you work just for money, you'll never make it, but if you love what you're doing and you always put the customer first, success will be yours."
author = "Ray Kroc"

[[quotes]]
quote = "Inspirational leaders need to have a winning mentality in order to inspire respect. It is hard to trust in the leadership of someone who is half-hearted about their purpose, or only sporadic in focus or enthusiasm."
author = "Sebastian Coe"

[[quotes]]
quote = "It's harder to be a success, globally, and be artistic. Harder to have that balance than just to be artistic when nobody understands you."
author = "Andre Benjamin"

[[quotes]]
quote = "We help people to begin truly healthful diets, and it is absolutely wonderful to see, not only their success, but also their delight at their ability to break old habits and feel really healthy for a change."
author = "Neal Barnard"

[[quotes]]
quote = "The hardest thing to find in life is balance - especially the more success you have, the more you look to the other side of the gate. What do I need to stay grounded, in touch, in love, connected, emotionally balanced? Look within yourself."
author = "Celine Dion"
