[[quotes]]
quote = "The decadent international but individualistic capitalism in the hands of which we found ourselves after the war is not a success. It is not intelligent. It is not beautiful. It is not just. It is not virtuous. And it doesn't deliver the goods."
author = "John Maynard Keynes"

[[quotes]]
quote = "One important key to success is self-confidence. An important key to self-confidence is preparation."
author = "Arthur Ashe"

[[quotes]]
quote = "Let us sacrifice our today so that our children can have a better tomorrow."
author = "A. P. J. Abdul Kalam"

[[quotes]]
quote = "Let every nation know, whether it wishes us well or ill, that we shall pay any price, bear any burden, meet any hardship, support any friend, oppose any foe to assure the survival and the success of liberty."
author = "John F. Kennedy"

[[quotes]]
quote = "I define success as being comfortable with yourself and your life. And that is about as good as it gets, really."
author = "Treat Williams"

[[quotes]]
quote = "Go big or go home. Because it's true. What do you have to lose?"
author = "Eliza Dushku"

[[quotes]]
quote = "Who would have thought that a tap-dancing penguin would outpoint James Bond at the box office? And deserve to? Not that there's anything wrong with 'Casino Royale.' But 'Happy Feet' - written and directed by George Miller - is a complete charmer, even if, in the way of most family fare, it can't resist straying into the Inspirational."
author = "Robert Gottlieb"

[[quotes]]
quote = "The only true measure of success is the ratio between what we might have done and what we might have been on the one hand, and the thing we have made and the things we have made of ourselves on the other."
author = "H. G. Wells"

[[quotes]]
quote = "The more things you do, the more you can do."
author = "Lucille Ball"

[[quotes]]
quote = "Success to me is having ten honeydew melons and eating only the top half of each slice."
author = "Barbra Streisand"

[[quotes]]
quote = "You'll never convince me there is a hopeless situation or there is any finality in any success or any failure."
author = "Carlos Ghosn"
