[[quotes]]
quote = "To burn always with this hard, gem-like flame, to maintain this ecstasy, is success in life."
author = "Walter Pater"

[[quotes]]
quote = "Without hard work, nothing grows but weeds."
author = "Gordon B. Hinckley"

[[quotes]]
quote = "Never retreat. Never explain. Get it done and let them howl."
author = "Benjamin Jowett"

[[quotes]]
quote = "Action is the foundational key to all success."
author = "Pablo Picasso"

[[quotes]]
quote = "President Obama called for a 'we' nation in his Inauguration Address. Art convenes. It is not just inspirational. It is aspirational. It pricks the walls of our compartmentalized minds, opens our hearts and makes us brave. And that's what we need most in our country today."
author = "Anna Deavere Smith"

[[quotes]]
quote = "Success is due to our stretching to the challenges of life. Failure comes when we shrink from them."
author = "John C. Maxwell"

[[quotes]]
quote = "It is the hopeful, buoyant, cheerful attitude of mind that wins. Optimism is a success builder; pessimism an achievement killer."
author = "Orison Swett Marden"

[[quotes]]
quote = "It's hard for a man to live with a successful woman - they seem to resent you so much. Very few men are generous enough to accept success in their women."
author = "Shirley Bassey"

[[quotes]]
quote = "A minute's success pays the failure of years."
author = "Robert Browning"

[[quotes]]
quote = "You need to overcome the tug of people against you as you reach for high goals."
author = "George S. Patton"

[[quotes]]
quote = "Keep your eyes on the stars, and your feet on the ground."
author = "Theodore Roosevelt"
