[[quotes]]
quote = "Success without honor is an unseasoned dish; it will satisfy your hunger, but it won't taste good."
author = "Joe Paterno"

[[quotes]]
quote = "That's the key to success, isn't it? It has to be fun."
author = "Monica Seles"

[[quotes]]
quote = "I don't think about financial success as the measurement of my success."
author = "Christie Hefner"

[[quotes]]
quote = "Hope is a state of mind, not of the world. Hope, in this deep and powerful sense, is not the same as joy that things are going well, or willingness to invest in enterprises that are obviously heading for success, but rather an ability to work for something because it is good."
author = "Vaclav Havel"

[[quotes]]
quote = "Knowing is not enough; we must apply. Willing is not enough; we must do."
author = "Johann Wolfgang von Goethe"

[[quotes]]
quote = "Aim for the moon. If you miss, you may hit a star."
author = "W. Clement Stone"

[[quotes]]
quote = "It is a mistake to suppose that men succeed through success; they much oftener succeed through failures. Precept, study, advice, and example could never have taught them so well as failure has done."
author = "Samuel Smiles"

[[quotes]]
quote = "Success is counted sweetest by those who never succeed."
author = "Emily Dickinson"

[[quotes]]
quote = "Success is dependent upon the glands - sweat glands."
author = "Zig Ziglar"

[[quotes]]
quote = "Success is the one unpardonable sin against our fellows."
author = "Ambrose Bierce"

[[quotes]]
quote = "For me, success is a state of mind. I feel like success isn't about conquering something; it's being happy with who you are."
author = "Britney Spears"
