[[quotes]]
quote = "Nothing in the world is more common than unsuccessful people with talent."
author = "Unknown"

[[quotes]]
quote = "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it."
author = "Unknown"

[[quotes]]
quote = "Your problem isn't the problem. Your reaction is the problem."
author = "Unknown"

[[quotes]]
quote = "You can do anything, but not everything."
author = "Unknown"

[[quotes]]
quote = "It’s not whether you get knocked down, it’s whether you get up."
author = "Vince Lombardi"

[[quotes]]
quote = "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed."
author = "Ray Goforth"

[[quotes]]
quote = "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life."
author = "A.P.J. Abdul Kalam"

[[quotes]]
quote = "I find that the harder I work, the more luck I seem to have."
author = "Thomas Jefferson"

[[quotes]]
quote = "The starting point of all achievement is desire."
author = "Napoleon Hill"

[[quotes]]
quote = "Success is the sum of small efforts, repeated day-in and day-out."
author = "Robert Collier"

[[quotes]]
quote = "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work."
author = "Thomas J. Watson"
