[[quotes]]
quote = "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things."
author = "Leonardo da Vinci"

[[quotes]]
quote = "More power than all the success slogans ever penned by human hand is the realization for every man that he has but one boss. That boss is the man - he - himself."
author = "Gabriel Heatter"

[[quotes]]
quote = "Success is not only one thing. It's not only having a nice house in Beverly Hills and driving a nice Mercedes."
author = "Malik Bendjelloul"

[[quotes]]
quote = "Hopefully, when people see 'Senna', they will understand why this inspirational story needed to be told, why it had to be made as a movie for the big screen, and why it is a film for everyone."
author = "Asif Kapadia"

[[quotes]]
quote = "Almost every college playwright or sketch or improv comedian was sort of aware of Christopher Durang - even kids in high school. His short plays were so accessible to younger people and I think that was inspirational to me."
author = "Mindy Kaling"

[[quotes]]
quote = "Happiness must happen, and the same holds for success: you have to let it happen by not caring about it."
author = "Viktor E. Frankl"

[[quotes]]
quote = "If you wish to be a success in the world, promise everything, deliver nothing."
author = "Napoleon Bonaparte"

[[quotes]]
quote = "I do not think there is any thrill that can go through the human heart like that felt by the inventor as he sees some creation of the brain unfolding to success... such emotions make a man forget food, sleep, friends, love, everything."
author = "Nikola Tesla"

[[quotes]]
quote = "The more tranquil a man becomes, the greater is his success, his influence, his power for good. Calmness of mind is one of the beautiful jewels of wisdom."
author = "James Allen"

[[quotes]]
quote = "Success means having the courage, the determination, and the will to become the person you believe you were meant to be."
author = "George A. Sheehan"

[[quotes]]
quote = "I have a tendency to sabotage relationships; I have a tendency to sabotage everything. Fear of success, fear of failure, fear of being afraid. Useless, good-for-nothing thoughts."
author = "Michael Buble"
