[[quotes]]
quote = "I'm not going to get somewhere and say, 'OK, I'm done.' Success is never final; I'll just keep on going. The same way as failure never being fatal. Just keep going. I'm going to the stars and then past them."
author = "Conor McGregor"

[[quotes]]
quote = "Get action. Seize the moment. Man was never intended to become an oyster."
author = "Theodore Roosevelt"

[[quotes]]
quote = "You are never too old to set another goal or to dream a new dream."
author = "Les Brown"

[[quotes]]
quote = "Marvin's Motivational Moments actually started as something that was actually therapeutic for me. I would sit up late at night after my wife passed trying to adjust to being alone."
author = "Marvin Sapp"

[[quotes]]
quote = "Change your life today. Don't gamble on the future, act now, without delay."
author = "Simone de Beauvoir"

[[quotes]]
quote = "Our subliminal mental processes operate outside awareness because they arise in these portions of our mind that are inaccessible to our conscious self; their inaccessibility is due to the architecture of the brain rather than because they have been subject to Freudian motivational forces like repression."
author = "Leonard Mlodinow"

[[quotes]]
quote = "Since we launched the original 'Pop Idol' in England, I've remained close with Simon Fuller. Working as executive producer on 'American idol' for its first seven years not only was an inspirational journey into the heart of American pop culture, it opened my eyes to the untapped potential of the incredibly dynamic young people in this world."
author = "Nigel Lythgoe"

[[quotes]]
quote = "Success can make you go one of two ways. It can make you a prima donna - or it can smooth the edges, take away the insecurities, let the nice things come out."
author = "Barbara Walters"

[[quotes]]
quote = "We don't have a divine right to success. So I agree with a lot of politicians out there when they say, 'We've got serious issues.' We do: immigration, infrastructure. I think income inequality's one of them."
author = "Jamie Dimon"

[[quotes]]
quote = "Academic success depends on research and publications."
author = "Philip Zimbardo"

[[quotes]]
quote = "Success is a science; if you have the conditions, you get the result."
author = "Oscar Wilde"
