[[quotes]]
quote = "Well, I think that there's a very thin dividing line between success and failure. And I think if you start a business without financial backing, you're likely to go the wrong side of that dividing line."
author = "Richard Branson"

[[quotes]]
quote = "Success is how high you bounce when you hit bottom."
author = "George S. Patton"

[[quotes]]
quote = "Work will win when wishy washy wishing won t."
author = "Thomas S. Monson"

[[quotes]]
quote = "You know you've reached true success the day you become truly humble. That's the day you stop needing to prove to the world - and yourself - that you've accomplished something meaningful."
author = "Naveen Jain"

[[quotes]]
quote = "The central conservative truth is that it is culture, not politics, that determines the success of a society. The central liberal truth is that politics can change a culture and save it from itself."
author = "Daniel Patrick Moynihan"

[[quotes]]
quote = "The love of what you do, combined with your belief in what you do, will not determine your success. It will determine how hard you will work and how dedicated you will be to achieving it. Success just shows up from there."
author = "Jeffrey Gitomer"

[[quotes]]
quote = "Never complain and never explain."
author = "Benjamin Disraeli"

[[quotes]]
quote = "I always say be humble but be firm. Humility and openness are the key to success without compromising your beliefs."
author = "George Hickenlooper"

[[quotes]]
quote = "The art of effective listening is essential to clear communication, and clear communication is necessary to management success."
author = "James Cash Penney"

[[quotes]]
quote = "I arise full of eagerness and energy, knowing well what achievement lies ahead of me."
author = "Zane Grey"

[[quotes]]
quote = "Honesty is the most single most important factor having a direct bearing on the final success of an individual, corporation, or product."
author = "Ed McMahon"
