[[quotes]]
quote = "I was successful materially, but I know life is much more than worldly success. I saw all these blessings God had given me. The way to give thanks is obedience to God."
author = "Hakeem Olajuwon"

[[quotes]]
quote = "I am fully aware that everybody has a right to succeed, and success should be with ethics."
author = "Sharad Pawar"

[[quotes]]
quote = "Success is a lousy teacher. It seduces smart people into thinking they can't lose."
author = "Bill Gates"

[[quotes]]
quote = "Your big opportunity may be right where you are now."
author = "Napoleon Hill"

[[quotes]]
quote = "Problems are not stop signs, they are guidelines."
author = "Robert H. Schuller"

[[quotes]]
quote = "Hope... is the companion of power, and the mother of success; for who so hopes has within him the gift of miracles."
author = "Samuel Smiles"

[[quotes]]
quote = "Success comes from taking the initiative and following up... persisting... eloquently expressing the depth of your love. What simple action could you take today to produce a new momentum toward success in your life?"
author = "Tony Robbins"

[[quotes]]
quote = "We can come to look upon the deaths of our enemies with as much regret as we feel for those of our friends, namely, when we miss their existence as witnesses to our success."
author = "Arthur Schopenhauer"

[[quotes]]
quote = "Whether a party can have much success without a woman present I must ask others to decide, but one thing is certain, no party is any fun unless seasoned with folly."
author = "Desiderius Erasmus"

[[quotes]]
quote = "It is not ignorance but knowledge which is the mother of wonder."
author = "Joseph Wood Krutch"

[[quotes]]
quote = "Success depends in a very large measure upon individual initiative and exertion, and cannot be achieved except by a dint of hard work."
author = "Anna Pavlova"
