[[quotes]]
quote = "One way to keep momentum going is to have constantly greater goals."
author = "Michael Korda"

[[quotes]]
quote = "We were all born with a certain degree of power. The key to success is discovering this innate power and using it daily to deal with whatever challenges come our way."
author = "Les Brown"

[[quotes]]
quote = "Patience, persistence and perspiration make an unbeatable combination for success."
author = "Napoleon Hill"

[[quotes]]
quote = "You were designed for accomplishment, engineered for success, and endowed with the seeds of greatness."
author = "Zig Ziglar"

[[quotes]]
quote = "Perseverance - a lowly virtue whereby mediocrity achieves an inglorious success."
author = "Ambrose Bierce"

[[quotes]]
quote = "About the only problem with success is that it does not teach you how to deal with failure."
author = "Tommy Lasorda"

[[quotes]]
quote = "Education is the key to success in life, and teachers make a lasting impact in the lives of their students."
author = "Solomon Ortiz"

[[quotes]]
quote = "Where there is a will, there is a way. If there is a chance in a million that you can do something, anything, to keep what you want from ending, do it. Pry the door open or, if need be, wedge your foot in that door and keep it open."
author = "Pauline Kael"

[[quotes]]
quote = "Passion is what gives meaning to our lives. It's what allows us to achieve success beyond our wildest imagination. Try to find a career path that you have a passion for."
author = "Henry Samueli"

[[quotes]]
quote = "Men must live and create. Live to the point of tears."
author = "Albert Camus"

[[quotes]]
quote = "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart."
author = "Marcus Aurelius"
