[[quotes]]
quote = "I said to the almond tree, 'Friend, speak to me of God,' and the almond tree blossomed."
author = "Nikos Kazantzakis"

[[quotes]]
quote = "Follow your inner moonlight; don't hide the madness."
author = "Allen Ginsberg"

[[quotes]]
quote = "In my forties, my optimism was boundless. I had really good health and tremendous success which allowed me to do anything I wanted."
author = "Patricia Cornwell"

[[quotes]]
quote = "Evolution acts slowly. Our psychological characteristics today are those that promoted reproductive success in the ancestral environment."
author = "Keith Henson"

[[quotes]]
quote = "The level of our success is limited only by our imagination and no act of kindness, however small, is ever wasted."
author = "Aesop"

[[quotes]]
quote = "I look at where I'm at today and realize that most of my success is owed to the mentors that was in my life."
author = "Kendrick Lamar"

[[quotes]]
quote = "In all our deeds, the proper value and respect for time determines success or failure."
author = "Malcolm X"

[[quotes]]
quote = "Earl Nightingale has inspired more people toward success and fortune than any other motivational speaker on the planet."
author = "Zig Ziglar"

[[quotes]]
quote = "My proudest achievement has been the success of the shows and artists I have been involved with, because they were made in Britain."
author = "Simon Cowell"

[[quotes]]
quote = "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do."
author = "Pele"

[[quotes]]
quote = "I don't dislike rappers or hip-hop or people who like it. I went to the Def Jam tour in Manchester in the '80s when rap was inspirational. Public Enemy were awesome. But it's all about status and bling now, and it doesn't say anything to me."
author = "Noel Gallagher"
