[[quotes]]
quote = "The things that we love tell us what we are."
author = "Thomas Aquinas"

[[quotes]]
quote = "I come to win."
author = "Leo Durocher"

[[quotes]]
quote = "Never mind what others do; do better than yourself, beat your own record from day to day, and you are a success."
author = "William J. H. Boetcker"

[[quotes]]
quote = "Writers, as they gain success, feel like outsiders because writers don't come together in real groups."
author = "Anne Rice"

[[quotes]]
quote = "True success, true happiness lies in freedom and fulfillment."
author = "Dada Vaswani"

[[quotes]]
quote = "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it."
author = "Steve Jobs"

[[quotes]]
quote = "I don't know what it's like to have a typical father figure. He's not the dad who's going to take me to the beach and go swimming, but he's such a motivational person."
author = "Tiffany Trump"

[[quotes]]
quote = "The success of the Rat Pack or the Clan was due to the camaraderie, the three guys who work together and kid each other and love each other."
author = "Sammy Davis, Jr."

[[quotes]]
quote = "Finding good partners is the key to success in anything: in business, in marriage and, especially, in investing."
author = "Robert Kiyosaki"

[[quotes]]
quote = "The single most important thing in a child's performance is the quality of the teacher. Making sure a child spends the maximum amount of time with inspirational teachers is the most important thing."
author = "Michael Gove"

[[quotes]]
quote = "Success is usually the culmination of controlling failure."
author = "Sylvester Stallone"
