[[quotes]]
quote = "Microsoft has had two goals in the last 10 years. One was to copy the Mac, and the other was to copy Lotus' success in the spreadsheet - basically, the applications business. And over the course of the last 10 years, Microsoft accomplished both of those goals. And now they are completely lost."
author = "Steve Jobs"

[[quotes]]
quote = "The one phrase you can use is that success has a thousand fathers, and failure is an orphan."
author = "Alan Price"

[[quotes]]
quote = "It seems to me we can never give up longing and wishing while we are thoroughly alive. There are certain things we feel to be beautiful and good, and we must hunger after them."
author = "George Eliot"

[[quotes]]
quote = "Everything you want is out there waiting for you to ask. Everything you want also wants you. But you have to take action to get it."
author = "Jules Renard"

[[quotes]]
quote = "Success is simply a matter of luck. Ask any failure."
author = "Earl Wilson"

[[quotes]]
quote = "Achievement is not always success, while reputed failure often is. It is honest endeavor, persistent effort to do the best possible under any and all circumstances."
author = "Orison Swett Marden"

[[quotes]]
quote = "The flow of Guiness into the studio was inspirational as well as nutritive."
author = "Carter Burwell"

[[quotes]]
quote = "The hardships that I encountered in the past will help me succeed in the future."
author = "Philip Emeagwali"

[[quotes]]
quote = "Lady Gaga is the present and the future. She is the most revolutionary and inspirational artist. She is fearless and daring."
author = "Donatella Versace"

[[quotes]]
quote = "Big shots are only little shots who keep shooting."
author = "Christopher Morley"

[[quotes]]
quote = "The making of friends who are real friends, is the best token we have of a man's success in life."
author = "Edward Everett Hale"
