[[quotes]]
quote = "Desire is the most important factor in the success of any athlete."
author = "Bill Shoemaker"

[[quotes]]
quote = "Success is the American Dream. And that success is not something to be ashamed of, or to demonize."
author = "Susana Martinez"

[[quotes]]
quote = "From my tribe I take nothing, I am the maker of my own fortune."
author = "Tecumseh"

[[quotes]]
quote = "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired, and success achieved."
author = "Helen Keller"

[[quotes]]
quote = "Throw your dreams into space like a kite, and you do not know what it will bring back, a new life, a new friend, a new love, a new country."
author = "Anais Nin"

[[quotes]]
quote = "People seldom see the halting and painful steps by which the most insignificant success is achieved."
author = "Anne Sullivan"

[[quotes]]
quote = "The ultimate aim of the ego is not to see something, but to be something."
author = "Muhammad Iqbal"

[[quotes]]
quote = "A strong passion for any object will ensure success, for the desire of the end will point out the means."
author = "Henry Hazlitt"

[[quotes]]
quote = "From its brilliancy everything is illuminated."
author = "Guru Nanak"

[[quotes]]
quote = "Things that look like an 'overnight success' typically are not."
author = "Jason Calacanis"

[[quotes]]
quote = "You never achieve success unless you like what you are doing."
author = "Dale Carnegie"
