[[quotes]]
quote = "Out of difficulties grow miracles."
author = "Jean de la Bruyere"

[[quotes]]
quote = "I really believe that everyone has a talent, ability, or skill that he can mine to support himself and to succeed in life."
author = "Dean Koontz"

[[quotes]]
quote = "I love those who yearn for the impossible."
author = "Johann Wolfgang von Goethe"

[[quotes]]
quote = "I'm a bit of a P. T. Barnum. I make stars out of everyone."
author = "Donald Trump"

[[quotes]]
quote = "Good, better, best. Never let it rest. 'Til your good is better and your better is best."
author = "St. Jerome"

[[quotes]]
quote = "Try not to become a man of success, but rather try to become a man of value."
author = "Albert Einstein"

[[quotes]]
quote = "When it comes to social consequences, they've got all different people acting in different ways, very difficult to even have a proper criterion of success. So, it's a difficult task."
author = "George Soros"

[[quotes]]
quote = "All of us are born for a reason, but all of us don't discover why. Success in life has nothing to do with what you gain in life or accomplish for yourself. It's what you do for others."
author = "Danny Thomas"

[[quotes]]
quote = "Sport is something that is very inspirational for young people."
author = "Pele"

[[quotes]]
quote = "When people stand up and talk about the great success that the EU has been, I'm not sure anybody saying it really believes it themselves anymore."
author = "Nigel Farage"

[[quotes]]
quote = "Today I choose life. Every morning when I wake up I can choose joy, happiness, negativity, pain... To feel the freedom that comes from being able to continue to make mistakes and choices - today I choose to feel life, not to deny my humanity but embrace it."
author = "Kevyn Aucoin"
