[[quotes]]
quote = "All progress takes place outside the comfort zone."
author = "Michael John Bobak"

[[quotes]]
quote = "You may only succeed if you desire succeeding; you may only fail if you do not mind failing."
author = "Philippos"

[[quotes]]
quote = "Courage is resistance to fear, mastery of fear--not absence of fear."
author = "Mark Twain"

[[quotes]]
quote = "Only put off until tomorrow what you are willing to die having left undone."
author = "Pablo Picasso"

[[quotes]]
quote = "People often say that motivation doesn't last. Well, neither does bathing--that's why we recommend it daily."
author = "Zig Ziglar"

[[quotes]]
quote = "We become what we think about most of the time, and that's the strangest secret."
author = "Earl Nightingale"

[[quotes]]
quote = "The only place where success comes before work is in the dictionary."
author = "Vidal Sassoon"

[[quotes]]
quote = "Too many of us are not living our dreams because we are living our fears."
author = "Les Brown"

[[quotes]]
quote = "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing."
author = "Martha Stewart"

[[quotes]]
quote = "It's not what you look at that matters, it's what you see."
author = "Unknown"

[[quotes]]
quote = "The road to success and the road to failure are almost exactly the same."
author = "Colin R. Davis"
