[[quotes]]
quote = "The five essential entrepreneurial skills for success: Concentration, Discrimination, Organization, Innovation and Communication."
author = "Harold S. Geneen"

[[quotes]]
quote = "Fortune befriends the bold."
author = "Emily Dickinson"

[[quotes]]
quote = "Somewhere, something incredible is waiting to be known."
author = "Sharon Begley"

[[quotes]]
quote = "There is never just one thing that leads to success for anyone. I feel it always a combination of passion, dedication, hard work, and being in the right place at the right time."
author = "Lauren Conrad"

[[quotes]]
quote = "Learn from the past, set vivid, detailed goals for the future, and live in the only moment of time over which you have any control: now."
author = "Denis Waitley"

[[quotes]]
quote = "Success didn't spoil me, I've always been insufferable."
author = "Fran Lebowitz"

[[quotes]]
quote = "You never know what motivates you."
author = "Cicely Tyson"

[[quotes]]
quote = "Perseverance is not a long race; it is many short races one after the other."
author = "Walter Elliot"

[[quotes]]
quote = "It's fine to celebrate success but it is more important to heed the lessons of failure."
author = "Bill Gates"

[[quotes]]
quote = "One needs more than ambition and talent to make a success of anything, really. There must be love and a vocation."
author = "Jessye Norman"

[[quotes]]
quote = "Each success only buys an admission ticket to a more difficult problem."
author = "Henry Kissinger"
