[[quotes]]
quote = "What you get by achieving your goals is not as important as what you become by achieving your goals."
author = "Zig Ziglar"

[[quotes]]
quote = "Success is not a matter of mastering subtle, sophisticated theory but rather of embracing common sense with uncommon levels of discipline and persistence."
author = "Patrick Lencioni"

[[quotes]]
quote = "Real success is not, like, materialistic. It's being where you want to be when you want to be; just living your life how you feel; having an ultimate goal and being able to accomplish it."
author = "Lindsey Wixson"

[[quotes]]
quote = "Humor has bailed me out of more tight situations than I can think of. If you go with your instincts and keep your humor, creativity follows. With luck, success comes, too."
author = "Jimmy Buffett"

[[quotes]]
quote = "Success is neither magical nor mysterious. Success is the natural consequence of consistently applying the basic fundamentals."
author = "Jim Rohn"

[[quotes]]
quote = "Sudden success in golf is like the sudden acquisition of wealth. It is apt to unsettle and deteriorate the character."
author = "P. G. Wodehouse"

[[quotes]]
quote = "Singleness of purpose is one of the chief essentials for success in life, no matter what may be one's aim."
author = "John D. Rockefeller"

[[quotes]]
quote = "It's a special person - and personality - who can lead a start-up to soaring success and sustain that success for the long term. Apple co-founder Steve Jobs and Facebook's Mark Zuckerberg are star examples."
author = "Marcus Buckingham"

[[quotes]]
quote = "Most great people have attained their greatest success just one step beyond their greatest failure."
author = "Napoleon Hill"

[[quotes]]
quote = "Success and failure are both part of life. Both are not permanent."
author = "Shah Rukh Khan"

[[quotes]]
quote = "The success of any great moral enterprise does not depend upon numbers."
author = "William Lloyd Garrison"
