[[quotes]]
quote = "If my writing comes to a halt, I head to the shops: I find them very inspirational. And if I get into real trouble with my plot, I go out for a pizza with my husband."
author = "Sophie Kinsella"

[[quotes]]
quote = "You are loved just for being who you are, just for existing. You don't have to do anything to earn it. Your shortcomings, your lack of self-esteem, physical perfection, or social and economic success - none of that matters. No one can take this love away from you, and it will always be here."
author = "Ram Dass"

[[quotes]]
quote = "I cannot give you the formula for success, but I can give you the formula for failure - which is: Try to please everybody."
author = "Herbert Bayard Swope"

[[quotes]]
quote = "My father, Oliver Hynes, was an educator. He was originally just a teacher, a very good one, but then he was promoted to be in charge of education for the entire area. He was always an inspirational teacher. He was my big personal supporter, always coming here for the Tony Awards. My mother, Carmel, was a homemaker."
author = "Garry Hynes"

[[quotes]]
quote = "If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success."
author = "John D. Rockefeller"

[[quotes]]
quote = "Success is like reaching an important birthday and finding you're exactly the same."
author = "Audrey Hepburn"

[[quotes]]
quote = "Ah, but a man's reach should exceed his grasp, Or what's a heaven for?"
author = "Robert Browning"

[[quotes]]
quote = "The optimist underestimates how difficult it is to achieve real change, believing that anything is possible and it's possible now. Only by confronting head-on the reality that all progress is going to be obstructed by vested interests and corrupted by human venality can we create realistic programmes that actually have a chance of success."
author = "Julian Baggini"

[[quotes]]
quote = "A hero is someone who has given his or her life to something bigger than oneself."
author = "Joseph Campbell"

[[quotes]]
quote = "As you walk in God's divine wisdom, you will surely begin to see a greater measure of victory and good success in your life."
author = "Joseph Prince"

[[quotes]]
quote = "The only journey is the one within."
author = "Rainer Maria Rilke"
