[[quotes]]
quote = "Therefore, if one were to consider that there was virtually no possibility of success through the US-Japan negotiations, the military and economic pressures would only force Japan into further crisis if time were allowed to pass in vain."
author = "Hideki Tojo"

[[quotes]]
quote = "I believe in living today. Not in yesterday, nor in tomorrow."
author = "Loretta Young"

[[quotes]]
quote = "The power of imagination makes us infinite."
author = "John Muir"

[[quotes]]
quote = "Either move or be moved."
author = "Ezra Pound"

[[quotes]]
quote = "I don't want to be married to someone who feels inferior to my success or because I make more money than he does."
author = "Grace Kelly"

[[quotes]]
quote = "When love and skill work together, expect a masterpiece."
author = "John Ruskin"

[[quotes]]
quote = "I believe it is in my nature to dance by virtue of the beat of my heart, the pulse of my blood and the music in my mind."
author = "Robert Fulghum"

[[quotes]]
quote = "Whether you're successful or not, you'll never actually feel the joys of accomplishment unless you love yourself. Success can be very difficult to deal with. You have to stay in the center. If you let your success define you, then you're really just setting yourself up for failure."
author = "Goldie Hawn"

[[quotes]]
quote = "Diligence is the mother of good fortune."
author = "Benjamin Disraeli"

[[quotes]]
quote = "I'm always asked, 'What's the secret to success?' But there are no secrets. Be humble. Be hungry. And always be the hardest worker in the room."
author = "Dwayne Johnson"

[[quotes]]
quote = "Success isn't always going to be a huge contract; success is going to be if you just live out your purpose in life."
author = "Allan Houston"
