[[quotes]]
quote = "Our success as a global brand has been directly related to how we select locations where we are confident our particular clients desire to be. Los Cabos, Mexico is the ideal Engel & Volkers market, growing in popularity among world luxury travelers seeking exceptional properties for second home opportunities."
author = "Anthony Hitt"

[[quotes]]
quote = "My goal in coming to General Motors was to help restore profitability, build a strong market position and position this iconic company for success. We are clearly on that path."
author = "Edward Whitacre, Jr."

[[quotes]]
quote = "Your ordinary acts of love and hope point to the extraordinary promise that every human life is of inestimable value."
author = "Desmond Tutu"

[[quotes]]
quote = "Success isn't always about greatness. It's about consistency. Consistent hard work leads to success. Greatness will come."
author = "Dwayne Johnson"

[[quotes]]
quote = "Success is not to be pursued; it is to be attracted by the person you become."
author = "Jim Rohn"

[[quotes]]
quote = "It is always the simple that produces the marvelous."
author = "Amelia Barr"

[[quotes]]
quote = "Be not entangled in this world of days and nights; Thou hast another time and space as well."
author = "Muhammad Iqbal"

[[quotes]]
quote = "The negative side of the American Dream comes when people pursue success at any cost, which in turn destroys the vision and the dream."
author = "Azar Nafisi"

[[quotes]]
quote = "We have it in our power to begin the world over again."
author = "Thomas Paine"

[[quotes]]
quote = "Be thine own palace, or the world's thy jail."
author = "John Donne"

[[quotes]]
quote = "We're born with success. It is only others who point out our failures, and what they attribute to us as failure."
author = "Whoopi Goldberg"
