[[quotes]]
quote = "Too many people measure how successful they are by how much money they make or the people that they associate with. In my opinion, true success should be measured by how happy you are."
author = "Richard Branson"

[[quotes]]
quote = "Overcoming fear is the first step to success for entrepreneurs. The winners all exemplify that, and the hard work and commitment they have shown underlines what is needed to set up a business."
author = "Richard Branson"

[[quotes]]
quote = "In most things success depends on knowing how long it takes to succeed."
author = "Charles de Montesquieu"

[[quotes]]
quote = "Success is getting and achieving what you want. Happiness is wanting and being content with what you get."
author = "Bernard Meltzer"

[[quotes]]
quote = "Fame or perceived success - it all comes from groupthink."
author = "Chance The Rapper"

[[quotes]]
quote = "Success is not built on success. It's built on failure. It's built on frustration. Sometimes its built on catastrophe."
author = "Sumner Redstone"

[[quotes]]
quote = "Do whatever you do intensely."
author = "Robert Henri"

[[quotes]]
quote = "The essential element of successful strategy is that it derives its success from the differences between competitors with a consequent difference in their behavior."
author = "Bruce Henderson"

[[quotes]]
quote = "I think you can have moderate success by copying something else, but if you really want to knock it out of the park, you have to do something different and take chances."
author = "Lee Ann Womack"

[[quotes]]
quote = "Success in management requires learning as fast as the world is changing."
author = "Warren Bennis"

[[quotes]]
quote = "Don't give up. Don't lose hope. Don't sell out."
author = "Christopher Reeve"
