[[quotes]]
quote = "Instead of this confusion, we need the unifying force of an official language, English, which is the language of success in America."
author = "Ernest Istook"

[[quotes]]
quote = "Let me tell you the secret that has led me to my goal. My strength lies solely in my tenacity."
author = "Louis Pasteur"

[[quotes]]
quote = "You wanna know what scares people? Success. When you don't make moves and when you don't climb up the ladder, everybody loves you because you're not competition."
author = "Nicki Minaj"

[[quotes]]
quote = "The Patriot Act is essential to our continued success in the war on terror here at home."
author = "Mike Pence"

[[quotes]]
quote = "It really is an honor if I can be inspirational to a younger singer or person. It means I've done my job."
author = "Aretha Franklin"

[[quotes]]
quote = "You change your life by changing your heart."
author = "Max Lucado"

[[quotes]]
quote = "Reading was very important to me as a kid. It was very inspirational to me. I went to a school where that wasn't encouraged so much, but my parents encouraged that, and it has made me part of who I am."
author = "Sasha Grey"

[[quotes]]
quote = "In oneself lies the whole world and if you know how to look and learn, the door is there and the key is in your hand. Nobody on earth can give you either the key or the door to open, except yourself."
author = "Jiddu Krishnamurti"

[[quotes]]
quote = "No matter how many goals you have achieved, you must set your sights on a higher one."
author = "Jessica Savitch"

[[quotes]]
quote = "Success is the sum of small efforts - repeated day in and day out."
author = "Robert Collier"

[[quotes]]
quote = "Success makes men rigid and they tend to exalt stability over all the other virtues; tired of the effort of willing they become fanatics about conservatism."
author = "Walter Lippmann"
