[[quotes]]
quote = "There is probably a perverse pride in my administration... that we were going to do the right thing, even if short-term it was unpopular. And I think anybody who's occupied this office has to remember that success is determined by an intersection in policy and politics and that you can't be neglecting of marketing and P.R. and public opinion."
author = "Barack Obama"

[[quotes]]
quote = "Obedience brings success; exact obedience brings miracles."
author = "Russell M. Nelson"

[[quotes]]
quote = "Your success story is a bigger story than whatever you're trying to say on stage. Success makes life easier. It doesn't make living easier."
author = "Bruce Springsteen"

[[quotes]]
quote = "The more man meditates upon good thoughts, the better will be his world and the world at large."
author = "Confucius"

[[quotes]]
quote = "Yes I have made a lot of money and I have a lot of respect, my films have done well, and I know there are loads of loads of people who look up to me and really love me. I really just thought this is like a strange dream. I have never thought this is a success - I don't have a standard."
author = "Shah Rukh Khan"

[[quotes]]
quote = "Before anything else, preparation is the key to success."
author = "Alexander Graham Bell"

[[quotes]]
quote = "There have been many different artists that have been inspirational. I suppose the question is directed to what was the reason why I went into fantasy illustration."
author = "Boris Vallejo"

[[quotes]]
quote = "Desire is the key to motivation, but it's the determination and commitment to unrelenting pursuit of your goal - a commitment to excellence - that will enable you to attain the success you seek."
author = "Mario Andretti"

[[quotes]]
quote = "Success to me is being a good person, treating people well."
author = "David LaChapelle"

[[quotes]]
quote = "One may miss the mark by aiming too high as too low."
author = "Thomas Fuller"

[[quotes]]
quote = "The most glorious moments in your life are not the so-called days of success, but rather those days when out of dejection and despair you feel rise in you a challenge to life, and the promise of future accomplishments."
author = "Gustave Flaubert"
