[[quotes]]
quote = "A champion is someone who gets up when he can't."
author = "Jack Dempsey"

[[quotes]]
quote = "Inside, I've got a real purist desire and dream about the music. I like the idea of being able to carve out a kind of magical, colourful, artistic, inspirational life. And the reality just turns out to be quite different, working with the business to bring this thing you have created into the world."
author = "Damien Rice"

[[quotes]]
quote = "In inner-city, low-income communities of color, there's such a high correlation in terms of educational quality and success."
author = "Bill Gates"

[[quotes]]
quote = "It is never too late to be what you might have been."
author = "George Eliot"

[[quotes]]
quote = "Space is an inspirational concept that allows you to dream big."
author = "Peter Diamandis"

[[quotes]]
quote = "Hitch your wagon to a star."
author = "Ralph Waldo Emerson"

[[quotes]]
quote = "Success is always temporary. When all is said and one, the only thing you'll have left is your character."
author = "Vince Gill"

[[quotes]]
quote = "There is simply no substitute for hard work when it comes to achieving success."
author = "Heather Bresch"

[[quotes]]
quote = "I will always desire to play with Bruce Springsteen. He's the most inspirational, most dedicated, most committed and most focused artist I've ever seen. I like to be around people like that."
author = "Max Weinberg"

[[quotes]]
quote = "Personally, I can't see the appeal in trekking down to D.C. for a networking extravaganza, even if it is built around a special moment in American history. While I find the election of Barack Obama inspirational, I don't have a desire to memorialize it with overly effusive celebration."
author = "Jamie Johnson"

[[quotes]]
quote = "If you don't like how things are, change it! You're not a tree."
author = "Jim Rohn"
