[[quotes]]
quote = "The only thing that ultimately matters is to eat an ice-cream cone, play a slide trombone, plant a small tree, good God, now you're free."
author = "Ray Manzarek"

[[quotes]]
quote = "Whatever ought to be, can be."
author = "James Rouse"

[[quotes]]
quote = "The measure of success is happiness and peace of mind."
author = "Bobby Davro"

[[quotes]]
quote = "As long as I'm not selling out the people that ride or die with me, I'm glad I'm not an MC. I'm a motivational speaker. I'm not that rapper dude."
author = "Young Jeezy"

[[quotes]]
quote = "Look at a football field. It looks like a big movie screen. This is theatre. Football combines the strategy of chess. It's part ballet. It's part battleground, part playground. We clarify, amplify and glorify the game with our footage, the narration and that music, and in the end create an inspirational piece of footage."
author = "Steve Sabol"

[[quotes]]
quote = "A person with a new idea is a crank until the idea succeeds."
author = "Mark Twain"

[[quotes]]
quote = "It is only in sorrow bad weather masters us; in joy we face the storm and defy it."
author = "Amelia Barr"

[[quotes]]
quote = "The only way to permanently change the temperature in the room is to reset the thermostat. In the same way, the only way to change your level of financial success 'permanently' is to reset your financial thermostat. But it is your choice whether you choose to change."
author = "T. Harv Eker"

[[quotes]]
quote = "As my family story shows, Latinos have been a blessing for USA for many generations. The future of America depends in part on the success of the Latino community, and this opportunity is just one more signifier of that."
author = "Julian Castro"

[[quotes]]
quote = "My success has been something I've worked a long time at and it's been a gradual process. I compare it to the idea of someone losing a lot of weight over a period of a few years. You don't really notice the weight loss overall but if you compare photos from then and now there's a big difference."
author = "Ray William Johnson"

[[quotes]]
quote = "I grew up in a very spiritual home in a Liberty City neighborhood of Miami, FL. I was raised in the church, and my mother was a very inspirational person in my life."
author = "Robert Battle"
