[[quotes]]
quote = "The function of leadership is to produce more leaders, not more followers."
author = "Ralph Nader"

[[quotes]]
quote = "Success is liking yourself, liking what you do, and liking how you do it."
author = "Maya Angelou"

[[quotes]]
quote = "As we look ahead into the next century, leaders will be those who empower others."
author = "Bill Gates"

[[quotes]]
quote = "A real entrepreneur is somebody who has no safety net underneath them."
author = "Henry Kravis"

[[quotes]]
quote = "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself."
author = "Mark Caine"

[[quotes]]
quote = "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy."
author = "Tony Robbins"

[[quotes]]
quote = "When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am afraid."
author = "Audre Lorde"

[[quotes]]
quote = "Whenever you find yourself on the side of the majority, it is time to pause and reflect."
author = "Mark Twain"

[[quotes]]
quote = "The successful warrior is the average man, with laser-like focus."
author = "Bruce Lee"

[[quotes]]
quote = "There is no traffic jam along the extra mile."
author = "Roger Staubach"

[[quotes]]
quote = "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success."
author = "Dale Carnegie"
