[[quotes]]
quote = "You take all the things that frighten you, and when you can get them to work for you all of sudden people are calling you a success."
author = "Randy Bachman"

[[quotes]]
quote = "Do something you really like, and hopefully it pays the rent. As far as I'm concerned, that's success."
author = "Tom Petty"

[[quotes]]
quote = "Success produces confidence; confidence relaxes industry, and negligence ruins the reputation which accuracy had raised."
author = "Ben Jonson"

[[quotes]]
quote = "Post-operatively the transplanted kidney functioned immediately with a dramatic improvement in the patient's renal and cardiopulmonary status. This spectacular success was a clear demonstration that organ transplantation could be life-saving."
author = "Joseph Murray"

[[quotes]]
quote = "No act of kindness, no matter how small, is ever wasted."
author = "Aesop"

[[quotes]]
quote = "I'm not a defender of old or new football managers. I believe in good ones and bad ones, those that achieve success and those that don't."
author = "Jose Mourinho"

[[quotes]]
quote = "Success is not assured, but America is resolute: this is the best chance for peace we are likely to see for some years to come - and we are acting to help Israelis and Palestinians seize this chance."
author = "Condoleezza Rice"

[[quotes]]
quote = "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do."
author = "Bob Dylan"

[[quotes]]
quote = "The key to success is action, and the essential in action is perseverance."
author = "Sun Yat-sen"

[[quotes]]
quote = "We know from research that growth is actually contagious, so if you want to reach your goals, you've got to get around people that are going in the same direction you want to be going, and you will catch the success."
author = "Henry Cloud"

[[quotes]]
quote = "A graduation ceremony is an event where the commencement speaker tells thousands of students dressed in identical caps and gowns that 'individuality' is the key to success."
author = "Robert Orben"
