[[quotes]]
quote = "Put your heart, mind, and soul into even your smallest acts. This is the secret of success."
author = "Swami Sivananda"

[[quotes]]
quote = "One of the things that I did before I ran for president is I was a professional speaker. Not a motivational speaker - an inspirational speaker. Motivation comes from within. You have to be inspired. That's what I do. I inspire people, I inspire the public, I inspire my staff. I inspired the organizations I took over to want to succeed."
author = "Herman Cain"

[[quotes]]
quote = "Success breeds success."
author = "Mia Hamm"

[[quotes]]
quote = "Success in the majority of circumstances depends on knowing how long it takes to succeed."
author = "Charles de Montesquieu"

[[quotes]]
quote = "I have learned that success is to be measured not so much by the position that one has reached in life as by the obstacles which he has had to overcome while trying to succeed."
author = "Booker T. Washington"

[[quotes]]
quote = "There is no force like success, and that is why the individual makes all effort to surround himself throughout life with the evidence of it; as of the individual, so should it be of the nation."
author = "Marcus Garvey"

[[quotes]]
quote = "In order to succeed you must fail, so that you know what not to do the next time."
author = "Anthony J. D'Angelo"

[[quotes]]
quote = "The turning point was when I hit my 30th birthday. I thought, if really want to write, it's time to start. I picked up the book How to Write a Novel in 90 Days. The author said to just write three pages a day, and I figured, I can do this. I never got past Page 3 of that book."
author = "James Rollins"

[[quotes]]
quote = "If I had permitted my failures, or what seemed to me at the time a lack of success, to discourage me I cannot see any way in which I would ever have made progress."
author = "Calvin Coolidge"

[[quotes]]
quote = "I believe that being successful means having a balance of success stories across the many areas of your life. You can't truly be considered successful in your business life if your home life is in shambles."
author = "Zig Ziglar"

[[quotes]]
quote = "I've been known to write 10 pages a day for 10 days running before I take a breath. I am not a disciplined writer. I'm one of those people who laughingly call themselves inspirational writers, which basically means someone who has no control over their own creative process."
author = "Catherine Ryan Hyde"
