[[quotes]]
quote = "What material success does is provide you with the ability to concentrate on other things that really matter. And that is being able to make a difference, not only in your own life, but in other people's lives."
author = "Oprah Winfrey"

[[quotes]]
quote = "To love means loving the unlovable. To forgive means pardoning the unpardonable. Faith means believing the unbelievable. Hope means hoping when everything seems hopeless."
author = "Gilbert K. Chesterton"

[[quotes]]
quote = "We are here to make another world."
author = "W. Edwards Deming"

[[quotes]]
quote = "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success."
author = "James Cameron"

[[quotes]]
quote = "The person who makes a success of living is the one who sees his goal steadily and aims for it unswervingly."
author = "Cecil B. DeMille"

[[quotes]]
quote = "In the United States, I am a great success, but I am not a celebrity."
author = "Paulo Coelho"

[[quotes]]
quote = "The fame of heroes owes little to the extent of their conquests and all to the success of the tributes paid to them."
author = "Jean Genet"

[[quotes]]
quote = "Without failure there is no sweetness in success. There's no understanding of it."
author = "Glenn Beck"

[[quotes]]
quote = "What we need is more people who specialize in the impossible."
author = "Theodore Roethke"

[[quotes]]
quote = "Our ideals are our better selves."
author = "Amos Bronson Alcott"

[[quotes]]
quote = "Success is measured by your discipline and inner peace."
author = "Mike Ditka"
