[[quotes]]
quote = "If there is any one secret of success, it lies in the ability to get the other person's point of view and see things from that person's angle as well as from your own."
author = "Henry Ford"

[[quotes]]
quote = "Enthusiasm moves the world."
author = "Arthur Balfour"

[[quotes]]
quote = "I found it interesting that as people become more technically oriented all over the world, at the same time people are becoming increasingly spiritual. The success of the Da Vinci code - even though it was a great yawn - also showed people's interest in religion."
author = "Barbara Walters"

[[quotes]]
quote = "Problems or successes, they all are the results of our own actions. Karma. The philosophy of action is that no one else is the giver of peace or happiness. One's own karma, one's own actions are responsible to come to bring either happiness or success or whatever."
author = "Maharishi Mahesh Yogi"

[[quotes]]
quote = "The toughest thing about success is that you've got to keep on being a success."
author = "Irving Berlin"

[[quotes]]
quote = "Socialism has no moral justification whatsoever; poor people are not morally superior to rich people, nor are they owed anything by rich people simply because of their lack of success. Charity is not a socialist concept - it is a religious one, an acknowledgment of God's sovereignty over property, a sovereignty the Left utterly rejects."
author = "Ben Shapiro"

[[quotes]]
quote = "When you win, nothing hurts."
author = "Joe Namath"

[[quotes]]
quote = "I'm extremely ambitious. I don't know why people are afraid to say that. I won't sell my soul to the devil, but I do want success and I don't think that's bad."
author = "Jada Pinkett Smith"

[[quotes]]
quote = "I view art as an inspirational tool."
author = "Thomas Kincade"

[[quotes]]
quote = "March on. Do not tarry. To go forward is to move toward perfection. March on, and fear not the thorns, or the sharp stones on life's path."
author = "Khalil Gibran"

[[quotes]]
quote = "A place for everything, everything in its place."
author = "Benjamin Franklin"
