[[quotes]]
quote = "I was perceived to be a first- to third-rounder. I kind of had a tough junior year and fell to the fifth round. At that time, it was motivational."
author = "Ryan Howard"

[[quotes]]
quote = "I did an A Level in Theatre Studies and had a really inspirational teacher, and then I just went on to university."
author = "Jessica Raine"

[[quotes]]
quote = "Turn your face to the sun and the shadows fall behind you."
author = "Unknown"

[[quotes]]
quote = "Be gentle to all and stern with yourself."
author = "Saint Teresa of Avila"

[[quotes]]
quote = "You simply have to put one foot in front of the other and keep going. Put blinders on and plow right ahead."
author = "George Lucas"

[[quotes]]
quote = "Almost no one is foolish enough to imagine that he automatically deserves great success in any field of activity; yet almost everyone believes that he automatically deserves success in marriage."
author = "Sydney J. Harris"

[[quotes]]
quote = "I dwell in possibility."
author = "Emily Dickinson"

[[quotes]]
quote = "The greatest trap in our life is not success, popularity or power, but self-rejection."
author = "Henri Nouwen"

[[quotes]]
quote = "If you want to conquer fear, don't sit home and think about it. Go out and get busy."
author = "Dale Carnegie"

[[quotes]]
quote = "Dullness in matters of government is a good sign, and not a bad one - in particular, dullness in parliamentary government is a test of its excellence, an indication of its success."
author = "Walter Bagehot"

[[quotes]]
quote = "How glorious a greeting the sun gives the mountains!"
author = "John Muir"
