[[quotes]]
quote = "Growing up in a group home, and with an undiagnosed learning disability to boot, the odds of success were not on my side. But when I joined the high school football team, I learned the value of discipline, focus, persistence, and teamwork - all skills that have proven vital to my career as a C.E.O. and social entrepreneur."
author = "Darell Hammond"

[[quotes]]
quote = "Success is an absurd, erratic thing. She arrives when one least expects her and after she has come may depart again almost because of a whim."
author = "Alice Foote MacDougall"

[[quotes]]
quote = "The line between failure and success is so fine that we scarcely know when we pass it: so fine that we are often on the line and do not know it."
author = "Elbert Hubbard"

[[quotes]]
quote = "Success is falling nine times and getting up ten."
author = "Jon Bon Jovi"

[[quotes]]
quote = "If you believe in yourself and have dedication and pride - and never quit, you'll be a winner. The price of victory is high but so are the rewards."
author = "Paul Bryant"

[[quotes]]
quote = "I know not age, nor weariness nor defeat."
author = "Rose Kennedy"

[[quotes]]
quote = "Indomitable perseverance in a business, properly understood, always ensures ultimate success."
author = "Cyrus McCormick"

[[quotes]]
quote = "To begin, begin."
author = "William Wordsworth"

[[quotes]]
quote = "Let us remember: One book, one pen, one child, and one teacher can change the world."
author = "Malala Yousafzai"

[[quotes]]
quote = "The past cannot be changed. The future is yet in your power."
author = "Unknown"

[[quotes]]
quote = "To be wholly devoted to some intellectual exercise is to have succeeded in life."
author = "Robert Louis Stevenson"
