[[quotes]]
quote = "Never did a government commence under auspices so favorable, nor ever was success so complete."
author = "James Monroe"

[[quotes]]
quote = "No experience is a cause of success or failure. We do not suffer from the shock of our experiences, so-called trauma - but we make out of them just what suits our purposes."
author = "Alfred Adler"

[[quotes]]
quote = "I've had a lot of success; I've had failures, so I learn from the failure."
author = "Gordon Ramsay"

[[quotes]]
quote = "Our worldly successes cannot be guaranteed, but our ability to achieve spiritual success is entirely up to us, thanks to the grace of God. The best advice I know is to give is to give those worldly things your best but never your all - reserve the ultimate hope for the only one who can grant it."
author = "Mitt Romney"

[[quotes]]
quote = "Everyone here has the sense that right now is one of those moments when we are influencing the future."
author = "Steve Jobs"

[[quotes]]
quote = "Success is the result of perfection, hard work, learning from failure, loyalty, and persistence."
author = "Colin Powell"

[[quotes]]
quote = "The most authentic thing about us is our capacity to create, to overcome, to endure, to transform, to love and to be greater than our suffering."
author = "Ben Okri"

[[quotes]]
quote = "Countless as the sands of the sea are human passions."
author = "Nikolai Gogol"

[[quotes]]
quote = "Success isn't permanent and failure isn't fatal."
author = "Mike Ditka"

[[quotes]]
quote = "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy."
author = "Norman Vincent Peale"

[[quotes]]
quote = "We need to accept that the commandments of God aren't just a long list of good ideas. They aren't 'life hacks' from an Internet blog or motivational quotes from a Pinterest board."
author = "Dieter F. Uchtdorf"
