[[quotes]]
quote = "Whoever is happy will make others happy too."
author = "Anne Frank"

[[quotes]]
quote = "The success of the young entrepreneur will be the key to India's transformation in the new millennium."
author = "Dhirubhai Ambani"

[[quotes]]
quote = "Nothing succeeds like success. Get a little success, and then just get a little more."
author = "Maya Angelou"

[[quotes]]
quote = "Those who cannot work with their hearts achieve but a hollow, half-hearted success that breeds bitterness all around."
author = "A. P. J. Abdul Kalam"

[[quotes]]
quote = "I honestly think it is better to be a failure at something you love than to be a success at something you hate."
author = "George Burns"

[[quotes]]
quote = "Anything that won't sell, I don't want to invent. Its sale is proof of utility, and utility is success."
author = "Thomas A. Edison"

[[quotes]]
quote = "Entrepreneurs can't forecast accurately, because they are trying something fundamentally new. So they will often be laughably behind plan - and on the brink of success."
author = "Eric Ries"

[[quotes]]
quote = "For success, attitude is equally as important as ability."
author = "Walter Scott"

[[quotes]]
quote = "Survival was my only hope, success my only revenge."
author = "Patricia Cornwell"

[[quotes]]
quote = "Only stupid people are changed by success."
author = "Jurgen Klopp"

[[quotes]]
quote = "The most important single ingredient in the formula of success is knowing how to get along with people."
author = "Theodore Roosevelt"
