[[quotes]]
quote = "If we get our self-esteem from superficial places, from our popularity, appearance, business success, financial situation, health, any of these, we will be disappointed, because no one can guarantee that we'll have them tomorrow."
author = "Kathy Ireland"

[[quotes]]
quote = "Opportunity does not knock, it presents itself when you beat down the door."
author = "Kyle Chandler"

[[quotes]]
quote = "Hopefully I'll continue to have the success I've had."
author = "Tiger Woods"

[[quotes]]
quote = "Books are challenging and inspirational to me."
author = "Amy Sedaris"

[[quotes]]
quote = "Hip-hop is more about attaining wealth. People respect success. They respect big. They don't even have to like your music. If you're big enough, people are drawn to you."
author = "Jay-Z"

[[quotes]]
quote = "Sometimes we may ask God for success, and He gives us physical and mental stamina. We might plead for prosperity, and we receive enlarged perspective and increased patience, or we petition for growth and are blessed with the gift of grace. He may bestow upon us conviction and confidence as we strive to achieve worthy goals."
author = "David A. Bednar"

[[quotes]]
quote = "To these ideals which were instilled in me when I was a youth, I attribute in a large degree the success that was mine on the bicycle tracks of the world."
author = "Major Taylor"

[[quotes]]
quote = "At the end of the day, the most overwhelming key to a child's success is the positive involvement of parents."
author = "Jane D. Hull"

[[quotes]]
quote = "I will love the light for it shows me the way, yet I will endure the darkness because it shows me the stars."
author = "Og Mandino"

[[quotes]]
quote = "I'm happy to be on a winning team. My individual success, that lasts for a short period of time. The success of being a part of the South, of Atlanta, which is now the hot bed of music, that's what's gonna last the longest. The fact that I contributed to planting our flag and moving music to my city, that's what I'm most proud of."
author = "T.I."

[[quotes]]
quote = "For success of any mission, it is necessary to have creative leadership. Creative leadership is vital for government, non-governmental organisations as well as for industries."
author = "A. P. J. Abdul Kalam"
