[[quotes]]
quote = "Real success is being totally indulgent about your own trip. You put your blinders on about the garbage and go full speed ahead."
author = "Betsey Johnson"

[[quotes]]
quote = "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence."
author = "Confucius"

[[quotes]]
quote = "America is the most grandiose experiment the world has seen, but, I am afraid, it is not going to be a success."
author = "Sigmund Freud"

[[quotes]]
quote = "When I meet with the founders of a new company, my advice is almost always, 'Do fewer things.' It's true of partnerships, marketing opportunities, anything that's taking up your time. The vast majority of things are distractions, and very few really matter to your success."
author = "Evan Williams"

[[quotes]]
quote = "It is during our darkest moments that we must focus to see the light."
author = "Aristotle"

[[quotes]]
quote = "You create your opportunities by asking for them."
author = "Shakti Gawain"

[[quotes]]
quote = "Do your work with your whole heart, and you will succeed - there's so little competition."
author = "Elbert Hubbard"

[[quotes]]
quote = "We're in a situation where talented, motivated school leavers and graduates can send off a hundred CVs and not get a reply, and where a trip to the Job Centre is depressing rather than inspirational. And you know what, that just feels wrong."
author = "Jameela Jamil"

[[quotes]]
quote = "There are glimpses of heaven to us in every act, or thought, or word, that raises us above ourselves."
author = "Robert Quillen"

[[quotes]]
quote = "When one side benefits more than the other, that's a win-lose situation. To the winner it might look like success for a while, but in the long run, it breeds resentment and distrust."
author = "Stephen Covey"

[[quotes]]
quote = "People think your success is just a matter of having a pretty face. But it's easy to be chewed up and spat out. You've got to stay ahead of the game to be able to stay in it."
author = "Kate Moss"
