[[quotes]]
quote = "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much."
author = "Jim Rohn"

[[quotes]]
quote = "If you genuinely want something, don't wait for it--teach yourself to be impatient."
author = "Gurbaksh Chahal"

[[quotes]]
quote = "Don't let the fear of losing be greater than the excitement of winning."
author = "Robert Kiyosaki"

[[quotes]]
quote = "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you!"
author = "T. Harv Eker"

[[quotes]]
quote = "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something--your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life."
author = "Steve Jobs"

[[quotes]]
quote = "Two roads diverged in a wood and I  took the one less traveled by, and that made all the difference."
author = "Robert Frost "

[[quotes]]
quote = "The number one reason people fail in life is because they listen to their friends, family, and neighbors."
author = "Napoleon Hill"

[[quotes]]
quote = "The reason most people never reach their goals is that they don't define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them."
author = "Denis Waitley"

[[quotes]]
quote = "In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it."
author = "Jane Smiley"

[[quotes]]
quote = "Success does not consist in never making mistakes but in never making the same one a second time."
author = "George Bernard Shaw"

[[quotes]]
quote = "I don't want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well."
author = "Diane Ackerman"
