[[quotes]]
quote = "I am an enthusiast, but not a crank in the sense that I have some pet theories as to the proper construction of a flying machine. I wish to avail myself of all that is already known and then, if possible, add my mite to help on the future worker who will attain final success."
author = "Wilbur Wright"

[[quotes]]
quote = "I've always tried to go a step past wherever people expected me to end up."
author = "Beverly Sills"

[[quotes]]
quote = "The victor belongs to the spoils."
author = "F. Scott Fitzgerald"

[[quotes]]
quote = "How easy to be amiable in the midst of happiness and success."
author = "William Ellery Channing"

[[quotes]]
quote = "Enjoy your sweat because hard work doesn't guarantee success, but without it you don't have a chance."
author = "Alex Rodriguez"

[[quotes]]
quote = "I'd rather attempt to do something great and fail than to attempt to do nothing and succeed."
author = "Robert H. Schuller"

[[quotes]]
quote = "People of mediocre ability sometimes achieve outstanding success because they don't know when to quit. Most men succeed because they are determined to."
author = "George Allen, Sr."

[[quotes]]
quote = "The person interested in success has to learn to view failure as a healthy, inevitable part of the process of getting to the top."
author = "Joyce Brothers"

[[quotes]]
quote = "The successful man doesn't use others, other people use the successful man, for above all the success is of service."
author = "Mark Caine"

[[quotes]]
quote = "My career started young and I was really ambitious, and then I had success and I hung out with people who were much older. I think I might have been temporally misplaced, so I thought I was 40. It was a premature midlife crisis."
author = "Elizabeth Gilbert"

[[quotes]]
quote = "Live your beliefs and you can turn the world around."
author = "Henry David Thoreau"
