[[quotes]]
quote = "It's as if inside the White House the belief in Obama's inspirational charisma is still such that every time the ugliness of brute politics intrudes, it's a startling revelation."
author = "Tina Brown"

[[quotes]]
quote = "When you see something that is technically sweet, you go ahead and do it and you argue about what to do about it only after you have had your technical success. That is the way it was with the atomic bomb."
author = "J. Robert Oppenheimer"

[[quotes]]
quote = "I look forward to making tangible and inspirational contributions to the Houston Technology Center's initiatives. HTC is an engine behind Houston's and Texas' continued growth."
author = "Walter O'Brien"

[[quotes]]
quote = "Mankind is made great or little by its own will."
author = "Friedrich Schiller"

[[quotes]]
quote = "Success comes to those who dedicate everything to their passion in life. To be successful, it is also very important to be humble and never let fame or money travel to your head."
author = "A. R. Rahman"

[[quotes]]
quote = "I don't dwell on success. Maybe that's one reason I'm successful."
author = "Calvin Klein"

[[quotes]]
quote = "What lies behind you and what lies in front of you, pales in comparison to what lies inside of you."
author = "Ralph Waldo Emerson"

[[quotes]]
quote = "A human being has so many skins inside, covering the depths of the heart. We know so many things, but we don't know ourselves! Why, thirty or forty skins or hides, as thick and hard as an ox's or bear's, cover the soul. Go into your own ground and learn to know yourself there."
author = "Meister Eckhart"

[[quotes]]
quote = "The most absurd and reckless aspirations have sometimes led to extraordinary success."
author = "Luc de Clapiers"

[[quotes]]
quote = "We should not give up and we should not allow the problem to defeat us."
author = "A. P. J. Abdul Kalam"

[[quotes]]
quote = "We can change our lives. We can do, have, and be exactly what we wish."
author = "Tony Robbins"
