[[quotes]]
quote = "I am stable when my private life is a success."
author = "Don Johnson"

[[quotes]]
quote = "A critical factor in its success was that the X developers were willing to give the sources away for free in accordance with the hacker ethic, and able to distribute them over the Internet."
author = "Eric S. Raymond"

[[quotes]]
quote = "The key to accepting responsibility for your life is to accept the fact that your choices, every one of them, are leading you inexorably to either success or failure, however you define those terms."
author = "Neal Boortz"

[[quotes]]
quote = "There is only one corner of the universe you can be certain of improving, and that's your own self."
author = "Aldous Huxley"

[[quotes]]
quote = "Sustainability is the key to our survival on this planet and will also determine success on all levels."
author = "Shari Arison"

[[quotes]]
quote = "This is just rap. I'm not trying to make people think I'm some sort of scientific wizard or inspirational poet."
author = "Action Bronson"

[[quotes]]
quote = "Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you."
author = "George Whitefield"

[[quotes]]
quote = "Success for me its to raise happy, healthy human beings."
author = "Kelly LeBrock"

[[quotes]]
quote = "Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig."
author = "Marcus Aurelius"

[[quotes]]
quote = "Nothing recedes like success."
author = "Walter Winchell"

[[quotes]]
quote = "If we did all the things we are capable of, we would literally astound ourselves."
author = "Thomas A. Edison"
