[[quotes]]
quote = "To be successful you have to be lucky, or a little mad, or very talented, or find yourself in a rapid growth field."
author = "Edward de Bono"

[[quotes]]
quote = "I've failed over and over and over again in my life and that is why I succeed."
author = "Michael Jordan"

[[quotes]]
quote = "The longer you hang in there, the greater the chance that something will happen in your favor. No matter how hard it seems, the longer you persist, the more likely your success."
author = "Jack Canfield"

[[quotes]]
quote = "To be successful, you have to have your heart in your business and your business in your heart."
author = "Thomas J. Watson"

[[quotes]]
quote = "I was motivated to be different in part because I was different."
author = "Donna Brazile"

[[quotes]]
quote = "God lets you be successful because he trusts you that you will do the right thing with it. Now, does he get disappointed often? All the time, because people get there and they forget how they got it."
author = "Steve Harvey"

[[quotes]]
quote = "Be yourself. Follow your instincts. Success depends, at least in part, on the ability to 'carry it off.'"
author = "Donald Rumsfeld"

[[quotes]]
quote = "A manager is a guide. He takes a group of people and says, 'With you I can make us a success; I can show you the way.'"
author = "Arsene Wenger"

[[quotes]]
quote = "Success is what you do with your ability. It's how you use your talent."
author = "George Allen, Sr."

[[quotes]]
quote = "Focused, hard work is the real key to success. Keep your eyes on the goal, and just keep taking the next step towards completing it. If you aren't sure which way to do something, do it both ways and see which works better."
author = "John Carmack"

[[quotes]]
quote = "Just as you wouldn't leave the house without taking a shower, you shouldn't start the day without at least 10 minutes of sacred practice: prayer, meditation, inspirational reading."
author = "Marianne Williamson"
