[[quotes]]
quote = "I think it's real easy to be famous these days; it's not real easy to sustain success."
author = "Jerry Jeff Walker"

[[quotes]]
quote = "Shoot for the moon and if you miss you will still be among the stars."
author = "Les Brown"

[[quotes]]
quote = "We all learn lessons in life. Some stick, some don't. I have always learned more from rejection and failure than from acceptance and success."
author = "Henry Rollins"

[[quotes]]
quote = "A key to achieving success is to assemble a strong and stable management team."
author = "Vivek Wadhwa"

[[quotes]]
quote = "We may encounter many defeats but we must not be defeated."
author = "Maya Angelou"

[[quotes]]
quote = "Be passionate and bold. Always keep learning. You stop doing useful things if you don't learn. So the last part to me is the key, especially if you have had some initial success. It becomes even more critical that you have the learning 'bit' always switched on."
author = "Satya Nadella"

[[quotes]]
quote = "You really have to work hard and apply yourself and by applying yourself and working hard and being diligent, you can achieve success."
author = "Julie Benz"

[[quotes]]
quote = "Whatever success I may have attained is due to the fact that since I was old enough to work at all, my ambition has never deserted me."
author = "Anna Held"

[[quotes]]
quote = "Honesty is the cornerstone of all success, without which confidence and ability to perform shall cease to exist."
author = "Mary Kay Ash"

[[quotes]]
quote = "Learning and innovation go hand in hand. The arrogance of success is to think that what you did yesterday will be sufficient for tomorrow."
author = "William Pollard"

[[quotes]]
quote = "Set yourself earnestly to see what you are made to do, and then set yourself earnestly to do it."
author = "Phillips Brooks"
