[[quotes]]
quote = "If you ask me what I came into this life to do, I will tell you: I came to live out loud."
author = "Emile Zola"

[[quotes]]
quote = "Beginning today, treat everyone you meet as if they were going to be dead by midnight. Extend to them all the care, kindness and understanding you can muster, and do it with no thought of any reward. Your life will never be the same again."
author = "Og Mandino"

[[quotes]]
quote = "I've learned that mistakes can often be as good a teacher as success."
author = "Jack Welch"

[[quotes]]
quote = "A friend of mine said something powerful at his grandfather's funeral. He said that the greatest lesson from his grandfather's life was that he died empty, because he accomplished everything he wanted, with no regrets. I think that, along with leaving a legacy, would be the greatest sign of success."
author = "Marvin Sapp"

[[quotes]]
quote = "The best form of flattery is to be admired, imitated or respected. I've always felt proud our fans look up to us or feel we are inspirational."
author = "Cheryl James"

[[quotes]]
quote = "I believe that any type of education can be great, but an education about ourselves can create something wonderful. I am a comedian, but people have called me a motivational speaker. I don't really consider myself that at all."
author = "Andy Andrews"

[[quotes]]
quote = "How do you know you're going to do something, untill you do it?"
author = "J. D. Salinger"

[[quotes]]
quote = "Thought is the original source of all wealth, all success, all material gain, all great discoveries and inventions, and of all achievement."
author = "Claude M. Bristol"

[[quotes]]
quote = "I would like to wish the England squad every success. I would also very much like to extend those wishes to Martin Johnson, Brian Smith, Mike Ford, John Wells, Graham Rowntree and the rest of the England 2011 World Cup management team who have been fantastic and deserve people to know that."
author = "Jonny Wilkinson"

[[quotes]]
quote = "When the sun is shining I can do anything; no mountain is too high, no trouble too difficult to overcome."
author = "Wilma Rudolph"

[[quotes]]
quote = "Success isn't measured by money or power or social rank. Success is measured by your discipline and inner peace."
author = "Mike Ditka"
