[[quotes]]
quote = "Follow your dreams, work hard, practice and persevere. Make sure you eat a variety of foods, get plenty of exercise and maintain a healthy lifestyle."
author = "Sasha Cohen"

[[quotes]]
quote = "All men's gains are the fruit of venturing."
author = "Herodotus"

[[quotes]]
quote = "The very first step towards success in any occupation is to become interested in it."
author = "William Osler"

[[quotes]]
quote = "Before everything else, getting ready is the secret of success."
author = "Henry Ford"

[[quotes]]
quote = "Coming to Nashville has been so motivating and inspirational. Just watching people live and breathe their music and create something that they can feel from start to finish."
author = "Madi Diaz"

[[quotes]]
quote = "I am decidedly of the opinion that in very many instances we can trace such a necessary connexion, especially among birds, and often with more complete success than in the case which I have here attempted to explain."
author = "Alfred Russel Wallace"

[[quotes]]
quote = "I'm thrilled to continue my partnership with U by Kotex for Generation Know while helping to empower girls. I've always been a motivational resource for my younger sisters and hope I can positively impact and inspire other young girls too."
author = "Khloe Kardashian"

[[quotes]]
quote = "The most beautiful thing in the world is, of course, the world itself."
author = "Wallace Stevens"

[[quotes]]
quote = "My biggest success is getting over the things that have tried to destroy and take me out of this life. Those are my biggest successes. It has nothing to do with work."
author = "Tyler Perry"

[[quotes]]
quote = "You must do the things you think you cannot do."
author = "Eleanor Roosevelt"

[[quotes]]
quote = "Rockefeller once explained the secret of success. 'Get up early, work late - and strike oil.'"
author = "Joey Adams"
