[[quotes]]
quote = "We crave instant success these days. If you are a really good sprinter and long jumper, you don't want to spend two or three years on a whole new set of events. You're used to doing well and it's difficult to give that up."
author = "Daley Thompson"

[[quotes]]
quote = "But the best teams I've encountered have one important thing in common: their team structure and processes cover a full range of distinct competencies necessary for success."
author = "Jesse James Garrett"

[[quotes]]
quote = "Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better."
author = "Samuel Beckett"

[[quotes]]
quote = "I did stand-up comedy for 18 years. Ten of those years were spent learning, four years were spent refining, and four years were spent in wild success. I was seeking comic originality, and fame fell on me as a byproduct. The course was more plodding than heroic."
author = "Steve Martin"

[[quotes]]
quote = "Well, the idea is that failure is an inevitable partner on the road to success and, if you're not willing to confront failure, you can never find out how good you are."
author = "Peter Guber"

[[quotes]]
quote = "There are people who make things happen, there are people who watch things happen, and there are people who wonder what happened. To be successful, you need to be a person who makes things happen."
author = "Jim Lovell"

[[quotes]]
quote = "Success is achieved by developing our strengths, not by eliminating our weaknesses."
author = "Marilyn vos Savant"

[[quotes]]
quote = "What is success? I think it is a mixture of having a flair for the thing that you are doing; knowing that it is not enough, that you have got to have hard work and a certain sense of purpose."
author = "Margaret Thatcher"

[[quotes]]
quote = "Action leads to Attention. that in the short-term releases Rewarding brain chemicals and in the long term improves reproductive success."
author = "Keith Henson"

[[quotes]]
quote = "Every skill you acquire doubles your odds of success."
author = "Scott Adams"

[[quotes]]
quote = "Success is when you see something, and you say, 'I want to do that,' and then you do it. It's being happy with what you do and doing what you love every day."
author = "Alessia Cara"
