[[quotes]]
quote = "It's inspirational to see someone who is dying smile."
author = "Arlen Specter"

[[quotes]]
quote = "I'm not an inspirational quote kind of person."
author = "Christine Teigen"

[[quotes]]
quote = "I thank you God for this most amazing day, for the leaping greenly spirits of trees, and for the blue dream of sky and for everything which is natural, which is infinite, which is yes."
author = "e. e. cummings"

[[quotes]]
quote = "I want anyone who believes in life, liberty, pursuit of happiness to succeed. And I want any force, any person, any element of an overarching Big Government that would stop your success, I want that organization, that element or that person to fail. I want you to succeed."
author = "Rush Limbaugh"

[[quotes]]
quote = "I have amazing friends who have led inspirational lives."
author = "Andrew Shue"

[[quotes]]
quote = "My powers are ordinary. Only my application brings me success."
author = "Isaac Newton"

[[quotes]]
quote = "Success is little more than a chemical compound of man with moment."
author = "Philip Guedalla"

[[quotes]]
quote = "We must let go of the life we have planned, so as to accept the one that is waiting for us."
author = "Joseph Campbell"

[[quotes]]
quote = "You have reached the pinnacle of success as soon as you become uninterested in money, compliments, or publicity."
author = "Thomas Wolfe"

[[quotes]]
quote = "The only way to discover the limits of the possible is to go beyond them into the impossible."
author = "Arthur C. Clarke"

[[quotes]]
quote = "Crave for a thing, you will get it. Renounce the craving, the object will follow you by itself."
author = "Swami Sivananda"
