[[quotes]]
quote = "To be prepared is half the victory."
author = "Miguel de Cervantes"

[[quotes]]
quote = "Give me a couple of years, and I'll make that actress an overnight success."
author = "Samuel Goldwyn"

[[quotes]]
quote = "It will, of course, be understood that directly or indirectly, soon or late, every advance in the sciences of human nature will contribute to our success in controlling human nature and changing it to the advantage of the common weal."
author = "Edward Thorndike"

[[quotes]]
quote = "Success depends upon previous preparation, and without such preparation there is sure to be failure."
author = "Confucius"

[[quotes]]
quote = "I'm not really easy to live with! There needs to be unlimited patience and unconditional love. Men I've known before loved my independent spirit and were proud of my success, to the point that they'd become jealous of the time I devote to my career."
author = "Milla Jovovich"

[[quotes]]
quote = "Always continue the climb. It is possible for you to do whatever you choose, if you first get to know who you are and are willing to work with a power that is greater than ourselves to do it."
author = "Ella Wheeler Wilcox"

[[quotes]]
quote = "Most success springs from an obstacle or failure. I became a cartoonist largely because I failed in my goal of becoming a successful executive."
author = "Scott Adams"

[[quotes]]
quote = "A government for the people must depend for its success on the intelligence, the morality, the justice, and the interest of the people themselves."
author = "Grover Cleveland"

[[quotes]]
quote = "My mind's my kingdom."
author = "Francis Quarles"

[[quotes]]
quote = "Currently, only 70 percent of our high school students earn diplomas with their peers, and less than one-third of our high school students graduate prepared for success in a four-year college."
author = "Ruben Hinojosa"

[[quotes]]
quote = "Every song you're trying to find something that going to connect in different ways but for me the songs that I'm really drawn to are inspirational, songs that lift you and that everybody can relate to no matter where you're from."
author = "Rodney Atkins"
