[[quotes]]
quote = "You must expect great things of yourself before you can do them."
author = "Michael Jordan"

[[quotes]]
quote = "Motivation is what gets you started. Habit is what keeps you going."
author = "Jim Ryun"

[[quotes]]
quote = "People rarely succeed unless they have fun in what they are doing."
author = "Dale Carnegie"

[[quotes]]
quote = "There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul."
author = "Ella Wheeler Wilcox"

[[quotes]]
quote = "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter."
author = "Francis Chan"

[[quotes]]
quote = "You've got to get up every morning with determination if you're going to go to bed with satisfaction."
author = "George Lorimer"

[[quotes]]
quote = "A goal is not always meant to be reached; it often serves simply as something to aim at."
author = "Bruce Lee"

[[quotes]]
quote = "Success is ... knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others."
author = "John C. Maxwell"

[[quotes]]
quote = "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice."
author = "Wayne Dyer"

[[quotes]]
quote = "To accomplish great things, we must not only act, but also dream, not only plan, but also believe."
author = "Anatole France"

[[quotes]]
quote = "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all."
author = "Dale Carnegie"
