[[quotes]]
quote = "The first principle of success is desire - knowing what you want. Desire is the planting of your seed."
author = "Robert Collier"

[[quotes]]
quote = "My initial goal for the 1984 opening ceremonies was a show that would be majestic, inspirational, and emotional - a 20 goosebump experience."
author = "David L. Wolper"

[[quotes]]
quote = "Nothing is worth more than this day."
author = "Johann Wolfgang von Goethe"

[[quotes]]
quote = "When you get into a tight place and everything goes against you, till it seems as though you could not hang on a minute longer, never give up then, for that is just the place and time that the tide will turn."
author = "Harriet Beecher Stowe"

[[quotes]]
quote = "Thus they have an idol that they petition for victory in war; another for success in their labors; and so for everything in which they seek or desire prosperity, they have their idols, which they honor and serve."
author = "Hernan Cortes"

[[quotes]]
quote = "It's the steady, quiet, plodding ones who win in the lifelong race."
author = "Robert W. Service"

[[quotes]]
quote = "The success of each of us benefits us all, and the success of us all benefits each of us individually."
author = "Walter Ulbricht"

[[quotes]]
quote = "Let us realize that: the privilege to work is a gift, the power to work is a blessing, the love of work is success!"
author = "David O. McKay"

[[quotes]]
quote = "Set your sights high, the higher the better. Expect the most wonderful things to happen, not in the future but right now. Realize that nothing is too good. Allow absolutely nothing to hamper you or hold you up in any way."
author = "Eileen Caddy"

[[quotes]]
quote = "Super-ambitious goals tend to be unifying and energizing to people; but only if they believe there's a chance of success."
author = "Peter Diamandis"

[[quotes]]
quote = "Your attitude will go a long way in determining your success, your recognition, your reputation and your enjoyment in being a lawyer."
author = "Joe Jamail"
