[[quotes]]
quote = "Life is a series of punches. It presents a lot of challenges. It presents a lot of hardship, but the people that are able to take those punches and able to move forward are the ones that really do have a lot of success and have a lot of joy in their life and have a lot of stories to tell, too."
author = "Josh Turner"

[[quotes]]
quote = "If a man does not keep pace with his companions, perhaps it is because he hears a different drummer. Let him step to the music which he hears, however measured or far away."
author = "Henry David Thoreau"

[[quotes]]
quote = "I want to see success right away. And I want to never give up, never stop."
author = "Joe Nichols"

[[quotes]]
quote = "The path from dreams to success does exist. May you have the vision to find it, the courage to get on to it, and the perseverance to follow it."
author = "Kalpana Chawla"

[[quotes]]
quote = "I realized I love motivating and I love empowering and I love inspiring people. I did that as an athlete for 18 years, and I am able to do that as a motivational speaker now as well as doing work on television."
author = "Dominique Dawes"

[[quotes]]
quote = "I think being directed and mentored by someone as inspirational as Paul Feig not only improves my performance but, as a whole, makes it what it is."
author = "Nargis Fakhri"

[[quotes]]
quote = "Every exit is an entry somewhere else."
author = "Tom Stoppard"

[[quotes]]
quote = "Our purpose in Vietnam is to prevent the success of aggression. It is not conquest, it is not empire, it is not foreign bases, it is not domination. It is, simply put, just to prevent the forceful conquest of South Vietnam by North Vietnam."
author = "Lyndon B. Johnson"

[[quotes]]
quote = "We live in a world of constant juxtaposition between joy that's possible and pain that's all too common. We hope for love and success and abundance, but we never quite forget that there is always lurking the possibility of disaster."
author = "Marianne Williamson"

[[quotes]]
quote = "A goal is a dream with a deadline."
author = "Napoleon Hill"

[[quotes]]
quote = "I get invited to many more literary festivals than I used to because I'm associated with 'Slumdog Millionaire,' the brand. Many more doors have opened up for me as a result of the global success of the film, although I believe that I'm the same person that existed before it."
author = "Vikas Swarup"
