[[quotes]]
quote = "I remember one day sitting at the pool and suddenly the tears were streaming down my cheeks. Why was I so unhappy? I had success. I had security. But it wasn't enough. I was exploding inside."
author = "Ingrid Bergman"

[[quotes]]
quote = "Talent alone won't make you a success. Neither will being in the right place at the right time, unless you are ready. The most important question is: 'Are your ready?'"
author = "Johnny Carson"

[[quotes]]
quote = "I've been blessed to be somebody that's been climbing that success mountain top for years of hard work, you know, but now it's all connecting. And now, the whole world is watching, you know what I'm saying, and it feels good 'cause it's good energy. This is all positive vibes, and good vibes and good energy, so it feels incredible."
author = "DJ Khaled"

[[quotes]]
quote = "George loves the T Rex because it's the noisiest and the scariest."
author = "Kate Middleton"

[[quotes]]
quote = "Failures, repeated failures, are finger posts on the road to achievement. One fails forward toward success."
author = "C. S. Lewis"

[[quotes]]
quote = "The most important thing is being passionate about what you're doing and always give it your all. That is the key to success."
author = "Charlie White"

[[quotes]]
quote = "When I grew up here, there was no T-Hub. Probably, the closest to T was the Tank bund."
author = "Satya Nadella"

[[quotes]]
quote = "Possessed with a full confidence of the certain success which British valor must gain over such enemies, I have led you up these steep and dangerous rocks, only solicitous to show you the foe within your reach."
author = "James Wolfe"

[[quotes]]
quote = "Success is almost totally dependent upon drive and persistence. The extra energy required to make another effort or try another approach is the secret of winning."
author = "Denis Waitley"

[[quotes]]
quote = "A long apprenticeship is the most logical way to success. The only alternative is overnight stardom, but I can't give you a formula for that."
author = "Chet Atkins"

[[quotes]]
quote = "Not every difficult and dangerous thing is suitable for training, but only that which is conducive to success in achieving the object of our effort."
author = "Epictetus"
