[[quotes]]
quote = "Success is achieved and maintained by those who try and keep trying."
author = "W. Clement Stone"

[[quotes]]
quote = "The truth is on the march and nothing will stop it."
author = "Emile Zola"

[[quotes]]
quote = "'All in With Laila Ali' is educational, inspirational, compelling programming profiling individuals that have reached for the sky, pushed themselves to the limit and did things that you would think were impossible."
author = "Laila Ali"

[[quotes]]
quote = "We sing inspirational songs, songs of praise and worship, and about how good and how big God is. We are magnifying the Lord."
author = "Fred Hammond"

[[quotes]]
quote = "Whatever success I've had, I always like to top it."
author = "Bernie Mac"

[[quotes]]
quote = "I think that when we have a better educated society, when there is less violence in our cities, when people get back into the workforce and have the opportunity to take care of themselves and their families - that for me really is the kind of success and the kind of America that I think most of us still want, we aspire to."
author = "Michael Nutter"

[[quotes]]
quote = "Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step."
author = "Lao Tzu"

[[quotes]]
quote = "I love a lot of the New York bands, but Patti Smith stands out. I just read 'Just Kids' and it's an inspirational, well-written account of an emerging New York artist in the late seventies."
author = "James Iha"

[[quotes]]
quote = "The size of your success is measured by the strength of your desire; the size of your dream; and how you handle disappointment along the way."
author = "Robert Kiyosaki"

[[quotes]]
quote = "Success comes in waves."
author = "Guy Pearce"

[[quotes]]
quote = "The handicap of deafness is not in the ear; it is in the mind."
author = "Marlee Matlin"
