[[quotes]]
quote = "Do you want to know who you are? Don't ask. Act! Action will delineate and define you."
author = "Thomas Jefferson"

[[quotes]]
quote = "Plant thy foot firmly in the prints which His foot has made before thee."
author = "Joseph Barber Lightfoot"

[[quotes]]
quote = "Obstacles are necessary for success because in selling, as in all careers of importance, victory comes only after many struggles and countless defeats."
author = "Og Mandino"

[[quotes]]
quote = "Make treating yourself a priority and always remember your life is happening now. Don't put off all your dreams and pleasures to another day. In any balanced personal definition of success there has to be a powerful element of living life in the present."
author = "Mireille Guiliano"

[[quotes]]
quote = "The only yardstick for success our society has is being a champion. No one remembers anything else."
author = "John Madden"

[[quotes]]
quote = "The secret of success in life is for a man to be ready for his opportunity when it comes."
author = "Benjamin Disraeli"

[[quotes]]
quote = "If you want to increase your success rate, double your failure rate."
author = "Thomas J. Watson"

[[quotes]]
quote = "Find out who you are and be that person. That's what your soul was put on this Earth to be. Find that truth, live that truth and everything else will come."
author = "Ellen DeGeneres"

[[quotes]]
quote = "The man who has done his level best... is a success, even though the world may write him down a failure."
author = "B. C. Forbes"

[[quotes]]
quote = "Teachers need to be more inspirational. But it's also up to engineering to make itself more interesting."
author = "Bruce Dickinson"

[[quotes]]
quote = "Every day of my life I walk with the idea that I am black, no matter how successful I am. And our success is tempered by that; you're successful in this way given the fact you are black, and most blacks don't get to that point."
author = "Danny Glover"
