[[quotes]]
quote = "The only question to ask yourself is, how much are you willing to sacrifice to achieve this success?"
author = "Larry Flynt"

[[quotes]]
quote = "You are always free to change your mind and choose a different future, or a different past."
author = "Richard Bach"

[[quotes]]
quote = "Typically, if you reward something, you get more of it. You punish something, you get less of it. And our businesses have been built for the last 150 years very much on that kind of motivational scheme."
author = "Daniel H. Pink"

[[quotes]]
quote = "Success is all about persistence and doing the right thing for the long term."
author = "Bruce Rauner"

[[quotes]]
quote = "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don't quit."
author = "Conrad Hilton"

[[quotes]]
quote = "Give light, and the darkness will disappear of itself."
author = "Desiderius Erasmus"

[[quotes]]
quote = "Success comes when people act together; failure tends to happen alone."
author = "Deepak Chopra"

[[quotes]]
quote = "You may lose your wife, you may lose your dog, your mother may hate you. None of those things matter. What matters is that you achieve success and become free. Then you can do whatever you like."
author = "Kevin O'Leary"

[[quotes]]
quote = "Without continual growth and progress, such words as improvement, achievement, and success have no meaning."
author = "Benjamin Franklin"

[[quotes]]
quote = "My definition of success is to live your life in a way that causes you to feel a ton of pleasure and very little pain - and because of your lifestyle, have the people around you feel a lot more pleasure than they do pain."
author = "Tony Robbins"

[[quotes]]
quote = "I never could have achieved the success that I have without setting physical activity and health goals."
author = "Bonnie Blair"
