[[quotes]]
quote = "I would probably work with Drake as he is massively inspirational to me as a writer as well as an artist. If not him, then Susan Boyle!"
author = "Conor Maynard"

[[quotes]]
quote = "I find my greatest pleasure, and so my reward, in the work that precedes what the world calls success."
author = "Thomas A. Edison"

[[quotes]]
quote = "Know or listen to those who know."
author = "Baltasar Gracian"

[[quotes]]
quote = "Rap music's been around for too long now to be inspirational. The words are, but the music isn't."
author = "Alexander McQueen"

[[quotes]]
quote = "Grace is the beauty of form under the influence of freedom."
author = "Friedrich Schiller"

[[quotes]]
quote = "Each day provides its own gifts."
author = "Marcus Aurelius"

[[quotes]]
quote = "No skill shapes a child's future success in school or in life more than the ability to read."
author = "Bob Riley"

[[quotes]]
quote = "The chief executive officer is also the chief sales officer. He or she is responsible for the success of the company and making a profit. The closer the CEO is to the everyday selling process, bringing in business, the more successful the company will become."
author = "Jeffrey Gitomer"

[[quotes]]
quote = "A champion is afraid of losing. Everyone else is afraid of winning."
author = "Billie Jean King"

[[quotes]]
quote = "Find a good teacher that will keep the game fun. Work hard and don't be afraid to have success or disappointment. That is what golf is all about."
author = "Paula Creamer"

[[quotes]]
quote = "I am deliberate and afraid of nothing."
author = "Audre Lorde"
