[[quotes]]
quote = "Forward, as occasion offers. Never look round to see whether any shall note it... Be satisfied with success in even the smallest matter, and think that even such a result is no trifle."
author = "Marcus Aurelius"

[[quotes]]
quote = "I hate to be a failure. I hate and regret the failure of my marriages. I would gladly give all my millions for just one lasting marital success."
author = "J. Paul Getty"

[[quotes]]
quote = "The bird is powered by its own life and by its motivation."
author = "A. P. J. Abdul Kalam"

[[quotes]]
quote = "Go for it now. The future is promised to no one."
author = "Wayne Dyer"

[[quotes]]
quote = "If you wish to succeed in life, make perseverance your bosom friend, experience your wise counselor, caution your elder brother, and hope your guardian genius."
author = "Joseph Addison"

[[quotes]]
quote = "When Maurice touched a keyboard, it was like something from a movie, magical. He would always give you something from a movie, and you'd go, what did you just play... immediately inspirational writings, amazing. That's what we're going to miss."
author = "Robin Gibb"

[[quotes]]
quote = "Our daily decisions and habits have a huge impact upon both our levels of happiness and success."
author = "Shawn Achor"

[[quotes]]
quote = "Never give in and never give up."
author = "Hubert H. Humphrey"

[[quotes]]
quote = "People repeat behaviour that leads to flooding their brains with pleasurable chemicals. The short-term reward loop acts over hours to years, and the long-term reproductive success loop over generations."
author = "Keith Henson"

[[quotes]]
quote = "Success is often achieved by those who don't know that failure is inevitable."
author = "Coco Chanel"

[[quotes]]
quote = "Success is peace of mind which is a direct result of self-satisfaction in knowing you did your best to become the best you are capable of becoming."
author = "John Wooden"
