[[quotes]]
quote = "Giving back, doing motivational speeches and stuff like that, that's always made me feel good. If you repeatedly go out there, and you are the change that you want to see, then that's what you are."
author = "Keke Palmer"

[[quotes]]
quote = "Integrity is so perishable in the summer months of success."
author = "Vanessa Redgrave"

[[quotes]]
quote = "Cherish your visions and your dreams as they are the children of your soul, the blueprints of your ultimate achievements."
author = "Napoleon Hill"

[[quotes]]
quote = "I don't take success and failure seriously. The only thing I do seriously is march forward. If I fall, I get up and march again."
author = "Kareena Kapoor Khan"

[[quotes]]
quote = "Ideas shape the course of history."
author = "John Maynard Keynes"

[[quotes]]
quote = "The glow of one warm thought is to me worth more than money."
author = "Thomas Jefferson"

[[quotes]]
quote = "No student ever attains very eminent success by simply doing what is required of him: it is the amount and excellence of what is over and above the required, that determines the greatness of ultimate distinction."
author = "Charles Kendall Adams"

[[quotes]]
quote = "In a balanced organization, working towards a common objective, there is success."
author = "Arthur Helps"

[[quotes]]
quote = "It is true that the aristocracies seem to have abused their monopoly of legal knowledge; and at all events their exclusive possession of the law was a formidable impediment to the success of those popular movements which began to be universal in the western world."
author = "Henry James Sumner Maine"

[[quotes]]
quote = "Poverty was the greatest motivating factor in my life."
author = "Jimmy Dean"

[[quotes]]
quote = "I have more love, success, and security than I could ever dream of."
author = "George Michael"
