[[quotes]]
quote = "Deacon Jones has been the most inspirational person in my football career."
author = "Jack Youngblood"

[[quotes]]
quote = "And above all things, never think that you're not good enough yourself. A man should never think that. My belief is that in life people will take you at your own reckoning."
author = "Isaac Asimov"

[[quotes]]
quote = "Success is the sum of details."
author = "Harvey S. Firestone"

[[quotes]]
quote = "Things do not happen. Things are made to happen."
author = "John F. Kennedy"

[[quotes]]
quote = "That some achieve great success, is proof to all that others can achieve it as well."
author = "Abraham Lincoln"

[[quotes]]
quote = "Four years of football are calculated to breed in the average man more of the ingredients of success in life than almost any academic course he takes."
author = "Knute Rockne"

[[quotes]]
quote = "I think Spain will always remain inspirational, and I think French cuisine will continue to be very French and yet very relevant with its time and keep evolving. But the last thing you want for it is to become too trendy and confusing. It has too much history."
author = "Daniel Boulud"

[[quotes]]
quote = "Be Impeccable With Your Word. Speak with integrity. Say only what you mean. Avoid using the word to speak against yourself or to gossip about others. Use the power of your word in the direction of truth and love."
author = "Don Miguel Ruiz"

[[quotes]]
quote = "But I like not these great success of yours; for I know how jealous are the gods."
author = "Herodotus"

[[quotes]]
quote = "I had an inspirational teacher at my junior school: Peter Nixon. He was enthusiastic, knowledgeable and slightly scary - a good combination for a teacher."
author = "Stephen Mangan"

[[quotes]]
quote = "You can't wait for inspiration. You have to go after it with a club."
author = "Jack London"
