[[quotes]]
quote = "You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals."
author = "Booker T. Washington"

[[quotes]]
quote = "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable."
author = "Theodore N. Vail"

[[quotes]]
quote = "It is better to fail in originality than to succeed in imitation."
author = "Herman Melville"

[[quotes]]
quote = "What would you do if you weren't afraid."
author = "Spencer Johnson"

[[quotes]]
quote = "Little minds are tamed and subdued by misfortune; but great minds rise above it."
author = "Washington Irving"

[[quotes]]
quote = "Failure is the condiment that gives success its flavor."
author = "Truman Capote"

[[quotes]]
quote = "Don't let what you cannot do interfere with what you can do."
author = "John R. Wooden"

[[quotes]]
quote = "You may have to fight a battle more than once to win it."
author = "Margaret Thatcher"

[[quotes]]
quote = "A man can be as great as he wants to be. If you believe in yourself and have the courage, the determination, the dedication, the competitive drive and if you are willing to sacrifice the little things in life and pay the price for the things that are worthwhile, it can be done."
author = "Vince Lombardi"

[[quotes]]
quote = "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart."
author = "Helen Keller"

[[quotes]]
quote = "The best preparation for tomorrow is doing your best today."
author = "H. Jackson Brown, Jr."
