[[quotes]]
quote = "Thinking: the talking of the soul with itself."
author = "Plato"

[[quotes]]
quote = "Once you agree upon the price you and your family must pay for success, it enables you to ignore the minor hurts, the opponent's pressure, and the temporary failures."
author = "Vince Lombardi"

[[quotes]]
quote = "My goal in my career is to inspire people, is to get my music out there and have people enjoy it, and have people think of me as an inspirational artist."
author = "Christina Grimmie"

[[quotes]]
quote = "First-person narrators is the way I know how to write a book with the greatest power and chance of artistic success."
author = "Anne Rice"

[[quotes]]
quote = "Focus on being balanced - success is balance."
author = "Laila Ali"

[[quotes]]
quote = "We are taught you must blame your father, your sisters, your brothers, the school, the teachers - but never blame yourself. It's never your fault. But it's always your fault, because if you wanted to change you're the one who has got to change."
author = "Katharine Hepburn"

[[quotes]]
quote = "Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve."
author = "Mary Kay Ash"

[[quotes]]
quote = "Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree."
author = "Martin Luther"

[[quotes]]
quote = "Temporary success can be achieved in spite of lack of other fundamental qualities, but no advancements can be maintained without hard work."
author = "William Feather"

[[quotes]]
quote = "Even when disco went out, I could still make hits. Once I had so much success, every idea became concentrated. I had so much confidence. I knew how the bass should sound, what rhythms would work. The tempos I knew: 110 to 120 BPM. I knew they would dance in the clubs in New York or anywhere."
author = "Giorgio Moroder"

[[quotes]]
quote = "Do you remember any instance where tyranny was destroyed and freedom established on its ruins, among a people possessing so small a share of virtue and public spirit? I recollect none, and this more than the British arms makes me fearful of final success, without a reform."
author = "Patrick Henry"
