[[quotes]]
quote = "Perseverance is a great element of success. If you only knock long enough and loud enough at the gate, you are sure to wake up somebody."
author = "Henry Wadsworth Longfellow"

[[quotes]]
quote = "Entrepreneurship is like a computer game in which you have to master every level before achieving success. Startups repeatedly stumble and have to go back to the drawing board. The best way to skip some levels and to increase the odds of survival is to learn from others who have already played the game."
author = "Vivek Wadhwa"

[[quotes]]
quote = "By now, you've probably caught on to something: my mother is always standing by with just the right Scripture or inspirational saying to get me through any tough situation."
author = "Gabby Douglas"

[[quotes]]
quote = "No one who achieves success does so without acknowledging the help of others. The wise and confident acknowledge this help with gratitude."
author = "Alfred North Whitehead"

[[quotes]]
quote = "Honesty and loyalty are key. If two people can be honest with each other about everything, that's probably the biggest key to success."
author = "Taylor Lautner"

[[quotes]]
quote = "I think the end goal, hopefully, is to take advantage of the attention I've gotten along the way and use it for good and build some communities, and as I get older I can continue to do things and be surrounded by things that are inspirational to me."
author = "Reggie Watts"

[[quotes]]
quote = "Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky."
author = "Rabindranath Tagore"

[[quotes]]
quote = "It's our nature: Human beings like success but they hate successful people."
author = "Carrot Top"

[[quotes]]
quote = "There's no one particular road that will lead you to success. I think everybody will find it differently."
author = "Marina and the Diamonds"

[[quotes]]
quote = "Success is about enjoying what you have and where you are, while pursuing achievable goals."
author = "Bo Bennett"

[[quotes]]
quote = "The three ordinary things that we often don't pay enough attention to, but which I believe are the drivers of all success, are hard work, perseverance, and basic honesty."
author = "Azim Premji"
