[[quotes]]
quote = "Failure is the key to success; each mistake teaches us something."
author = "Morihei Ueshiba"

[[quotes]]
quote = "Success comes from knowing that you did your best to become the best that you are capable of becoming."
author = "John Wooden"

[[quotes]]
quote = "Change can either challenge or threaten us. Your beliefs pave your way to success or block you."
author = "Marsha Sinetar"

[[quotes]]
quote = "You can't build a reputation on what you are going to do."
author = "Henry Ford"

[[quotes]]
quote = "The key to success is to keep growing in all areas of life - mental, emotional, spiritual, as well as physical."
author = "Julius Erving"

[[quotes]]
quote = "It's both rebellion and conformity that attack you with success."
author = "Amy Tan"

[[quotes]]
quote = "I like motivational books, because I like the go-getting American spirit - your destiny is in your own hands, life is what you make it, don't accept your limitations, jump before you're pushed, leap before you look."
author = "Louise Mensch"

[[quotes]]
quote = "I believe that if one always looked at the skies, one would end up with wings."
author = "Gustave Flaubert"

[[quotes]]
quote = "Though I had success in my research both when I was mad and when I was not, eventually I felt that my work would be better respected if I thought and acted like a 'normal' person."
author = "John Forbes Nash, Jr."

[[quotes]]
quote = "Benazir Bhutto was an inspirational leader and an inspirational woman."
author = "Malala Yousafzai"

[[quotes]]
quote = "Success is blocked by concentrating on it and planning for it... Success is shy - it won't come out while you're watching."
author = "Tennessee Williams"
