[[quotes]]
quote = "I wish the Peace Corps and its volunteers continued success and perseverance. We are grateful for their contributions to society and dedication to providing assistance where it is needed. May the Peace Corps continue its legacy of service, both at home and abroad."
author = "Kenny Marchant"

[[quotes]]
quote = "We must walk consciously only part way toward our goal, and then leap in the dark to our success."
author = "Henry David Thoreau"

[[quotes]]
quote = "Ambition is the path to success, persistence is the vehicle you arrive in."
author = "William Eardley IV"

[[quotes]]
quote = "There is an immutable conflict at work in life and in business, a constant battle between peace and chaos. Neither can be mastered, but both can be influenced. How you go about that is the key to success."
author = "Phil Knight"

[[quotes]]
quote = "The weeds keep multiplying in our garden, which is our mind ruled by fear. Rip them out and call them by name."
author = "Sylvia Browne"

[[quotes]]
quote = "They succeed, because they think they can."
author = "Virgil"

[[quotes]]
quote = "There is just a lot of creativity and theatricality in performers who happen to be gay. Maybe there's a success in numbers, so by the law of averages we are going to get these jobs."
author = "Neil Patrick Harris"

[[quotes]]
quote = "Successful people breed success."
author = "Phil Crosby"

[[quotes]]
quote = "Think of yourself as on the threshold of unparalleled success. A whole, clear, glorious life lies before you. Achieve! Achieve!"
author = "Andrew Carnegie"

[[quotes]]
quote = "I've done a lot of albums and I kinda know when I'm onto something that was inspirational for me to record and create, and this was one of those projects where I really enjoyed making the album."
author = "Lee Ritenour"

[[quotes]]
quote = "If one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours."
author = "Henry David Thoreau"
