[[quotes]]
quote = "One man cannot practice many arts with success."
author = "Plato"

[[quotes]]
quote = "You do not pay the price of success, you enjoy the price of success."
author = "Zig Ziglar"

[[quotes]]
quote = "Procrastination is one of the most common and deadliest of diseases and its toll on success and happiness is heavy."
author = "Wayne Gretzky"

[[quotes]]
quote = "It's a moment that I'm after, a fleeting moment, but not a frozen moment."
author = "Andrew Wyeth"

[[quotes]]
quote = "Success is just being happy. And I try so many different things. I do a lot of different things. Because I think God has helped me to love myself. I know who God is, and I love God."
author = "Herschel Walker"

[[quotes]]
quote = "Whether you come from a council estate or a country estate, your success will be determined by your own confidence and fortitude."
author = "Michelle Obama"

[[quotes]]
quote = "Only those who have learned the power of sincere and selfless contribution experience life's deepest joy: true fulfillment."
author = "Tony Robbins"

[[quotes]]
quote = "After I won the Oscar, my salary doubled, my friends tripled, my children became more popular at school, my butcher made a pass at me, and my maid hit me up for a raise."
author = "Shirley Jones"

[[quotes]]
quote = "My store, Wine Library, outsells big national chains. How do you think we do it? It started with hustle. I always say that our success wasn't due to my hundreds of online videos about wine that went viral, but to the hours I spent talking to people online afterward, making connections and building relationships."
author = "Gary Vaynerchuk"

[[quotes]]
quote = "The funny thing about having all this so-called success is that behind it is a certain horrible emptiness."
author = "Sam Shepard"

[[quotes]]
quote = "The first and most important step toward success is the feeling that we can succeed."
author = "Nelson Boswell"
