[[quotes]]
quote = "I always like a woman in power in politics. I think they're pretty inspirational in terms of looks to begin with. It's very calculated."
author = "Chris Benz"

[[quotes]]
quote = "It's not enough that I should succeed - others should fail."
author = "David Merrick"

[[quotes]]
quote = "The system that enables the most people to earn the most success is free enterprise, by matching up people's skills, interests, and abilities. In contrast, redistribution simply spreads money around. Even worse, it attenuates the ability to earn success by perverting economic incentives."
author = "Arthur C. Brooks"

[[quotes]]
quote = "Never lose sight of the fact that the most important yardstick of your success will be how you treat other people - your family, friends, and coworkers, and even strangers you meet along the way."
author = "Barbara Bush"

[[quotes]]
quote = "Failures to heroic minds are the stepping stones to success."
author = "Thomas Chandler Haliburton"

[[quotes]]
quote = "The way a team plays as a whole determines its success. You may have the greatest bunch of individual stars in the world, but if they don't play together, the club won't be worth a dime."
author = "Babe Ruth"

[[quotes]]
quote = "When I ran the stock exchange, it was the most successful it's been in its 200-plus-year history. And I was rewarded for success; I would not have been rewarded if we failed."
author = "Richard Grasso"

[[quotes]]
quote = "Watches are the only jewelry men can wear, unless you're Mr. T."
author = "Gordon Bethune"

[[quotes]]
quote = "Our success educationally, industrially and politically is based upon the protection of a nation founded by ourselves. And the nation can be nowhere else but in Africa."
author = "Marcus Garvey"

[[quotes]]
quote = "I'm better than P. T. Barnum and Colonel Parker put together."
author = "Evel Knievel"

[[quotes]]
quote = "I want to be motivational and inspirational for everybody: my big aim is more women on bicycles."
author = "Marianne Vos"
