[[quotes]]
quote = "What is success? It is a toy balloon among children armed with pins."
author = "Gene Fowler"

[[quotes]]
quote = "As my father used to tell me, the only true sign of success in life is being able to do for a living that which makes you happy."
author = "Al Yankovic"

[[quotes]]
quote = "There are two ways of spreading light: to be the candle or the mirror that reflects it."
author = "Edith Wharton"

[[quotes]]
quote = "I don't like being choreographed to a T. I like to take steps and make them my own."
author = "John Cameron Mitchell"

[[quotes]]
quote = "Memories of our lives, of our works and our deeds will continue in others."
author = "Rosa Parks"

[[quotes]]
quote = "If at first you don't succeed, try, try again. Then quit. There's no point in being a damn fool about it."
author = "W. C. Fields"

[[quotes]]
quote = "No self-respecting woman should wish or work for the success of a party who ignores her sex."
author = "Susan B. Anthony"

[[quotes]]
quote = "Success is not a destination, but the road that you're on. Being successful means that you're working hard and walking your walk every day. You can only live your dream by working hard towards it. That's living your dream."
author = "Marlon Wayans"

[[quotes]]
quote = "Failure is a part of success."
author = "Hank Aaron"

[[quotes]]
quote = "The measure of success is not whether you have a tough problem to deal with, but whether it is the same problem you had last year."
author = "John Foster Dulles"

[[quotes]]
quote = "Raising children is an uncertain thing; success is reached only after a life of battle and worry."
author = "Democritus"
