[[quotes]]
quote = "The secret of success is to be in harmony with existence, to be always calm to let each wave of life wash us a little farther up the shore."
author = "Cyril Connolly"

[[quotes]]
quote = "We relish news of our heroes, forgetting that we are extraordinary to somebody too."
author = "Helen Hayes"

[[quotes]]
quote = "My success isn't a result of arrogance - it's a result of belief."
author = "Conor McGregor"

[[quotes]]
quote = "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible."
author = "Francis of Assisi"

[[quotes]]
quote = "The essential elements of giving are power and love - activity and affection - and the consciousness of the race testifies that in the high and appropriate exercise of these is a blessedness greater than any other."
author = "Mark Hopkins"

[[quotes]]
quote = "The only thing I'm addicted to is winning. This bootleg cult, arrogantly referred to as Alcoholics Anonymous, reports a 5 percent success rate. My success rate is 100 percent."
author = "Charlie Sheen"

[[quotes]]
quote = "Few things are more important to each individual's future success or to our nation's prosperity than education."
author = "Mark Kennedy"

[[quotes]]
quote = "The secret of our success is that we never, never give up."
author = "Wilma Mankiller"

[[quotes]]
quote = "It's good to test yourself and develop your talents and ambitions as fully as you can and achieve greater success; but I think success is the feeling you get from a job well done, and the key thing is to do the work."
author = "Peter Thiel"

[[quotes]]
quote = "Accept the challenges so that you can feel the exhilaration of victory."
author = "George S. Patton"

[[quotes]]
quote = "Don't think, just do."
author = "Horace"
