[[quotes]]
quote = "I'd rather be a failure at something I love than a success at something I hate."
author = "George Burns"

[[quotes]]
quote = "My father was an immigrant who literally walked across Europe to get out of Russia. He fought in World War I. He was wounded in action. My father was a great success even though he never had money. He was a very determined man, a great role model."
author = "Arlen Specter"

[[quotes]]
quote = "Old age is like everything else. To make a success of it, you've got to start young."
author = "Theodore Roosevelt"

[[quotes]]
quote = "In hindsight, I slid into arrogance based upon past success."
author = "Reed Hastings"

[[quotes]]
quote = "All you need in this life is ignorance and confidence, and then success is sure."
author = "Mark Twain"

[[quotes]]
quote = "To design the future effectively, you must first let go of your past."
author = "Charles J. Givens"

[[quotes]]
quote = "If someone says 'grunge' or 'punk,' you know what the sound is, but if you say 'No Wave,' it's kind of mysterious. That was the most interesting part and should have been the most inspirational thing about it... here's this collective sonic insanity, and none of it sounds anything alike."
author = "Lydia Lunch"

[[quotes]]
quote = "Success is the sweetest revenge."
author = "Vanessa Williams"

[[quotes]]
quote = "The time I had waited probably made the difference between success and failure."
author = "Anna Neagle"

[[quotes]]
quote = "There is progress whether ye are going forward or backward! The thing is to move!"
author = "Edgar Cayce"

[[quotes]]
quote = "Well, you would have to say what is the criteria to determine the success of any merger? It would have to be that the companies are stronger financially, that they took market share, and they are on a very steady footing in terms of their performance."
author = "Kevin Rollins"
