[[quotes]]
quote = "Success is a process, a quality of mind and way of being, an outgoing affirmation of life."
author = "Alex Noble"

[[quotes]]
quote = "Your success and happiness lies in you. Resolve to keep happy, and your joy and you shall form an invincible host against difficulties."
author = "Helen Keller"

[[quotes]]
quote = "Happy people are ignoramuses and glory is nothing else but success, and to achieve it one only has to be cunning."
author = "Mikhail Lermontov"

[[quotes]]
quote = "Whenever an individual or a business decides that success has been attained, progress stops."
author = "Thomas J. Watson"

[[quotes]]
quote = "Formula for success: rise early, work hard, strike oil."
author = "J. Paul Getty"

[[quotes]]
quote = "The best way out is always through."
author = "Robert Frost"

[[quotes]]
quote = "We're not afraid of risking what was our success yesterday in order to explore some new field. We're adventurous. We like the challenge of unknown territory, unknown artistic field, and that's what stimulates us."
author = "Guy Laliberte"

[[quotes]]
quote = "Personal satisfaction is the most important ingredient of success."
author = "Denis Waitley"

[[quotes]]
quote = "Brand is not a product, that's for sure; it's not one item. It's an idea, it's a theory, it's a meaning, it's how you carry yourself. It's aspirational, it's inspirational."
author = "Kevin Plank"

[[quotes]]
quote = "Life affords no higher pleasure than that of surmounting difficulties, passing from one step of success to another, forming new wishes and seeing them gratified."
author = "Samuel Johnson"

[[quotes]]
quote = "When you delegate work to the member of the team, your job is to clearly frame success and describe the objectives."
author = "Steven Sinofsky"
