[[quotes]]
quote = "What great thing would you attempt if you knew you could not fail?"
author = "Robert H. Schuller"

[[quotes]]
quote = "There is only one success - to be able to spend your life in your own way."
author = "Christopher Morley"

[[quotes]]
quote = "I grew up in a bookless house - my parents didn't read poetry, so if I hadn't had the chance to experience it at school I'd never have experienced it. But I loved English, and I was very lucky in that I had inspirational English teachers, Miss Scriven and Mr. Walker, and they liked us to learn poems by heart, which I found I loved doing."
author = "Carol Ann Duffy"

[[quotes]]
quote = "To know even one life has breathed easier because you have lived. This is to have succeeded."
author = "Bessie Anderson Stanley"

[[quotes]]
quote = "You weren't born just to live a life and to die; you were born to accomplish something specifically. Matter of fact, success is making it to the end of your purpose; that is success... Success is not just existing. Success is making it to the end of why you were born."
author = "Myles Munroe"

[[quotes]]
quote = "The supreme quality for leadership is unquestionably integrity. Without it, no real success is possible, no matter whether it is on a section gang, a football field, in an army, or in an office."
author = "Dwight D. Eisenhower"

[[quotes]]
quote = "No bird soars too high if he soars with his own wings."
author = "William Blake"

[[quotes]]
quote = "The culture of a workplace - an organization's values, norms and practices - has a huge impact on our happiness and success."
author = "Adam Grant"

[[quotes]]
quote = "Success for me means being able to work. I don't look at so much at what I've done as much as I look to what I will do."
author = "Phylicia Rashad"

[[quotes]]
quote = "Fear of failure, it's the greatest motivational tool. It drives me and drives me and drives me."
author = "Jerry West"

[[quotes]]
quote = "The thermometer of success is merely the jealousy of the malcontents."
author = "Salvador Dali"
