[[quotes]]
quote = "Success is where preparation and opportunity meet."
author = "Bobby Unser"

[[quotes]]
quote = "Discipline is the soul of an army. It makes small numbers formidable; procures success to the weak, and esteem to all."
author = "George Washington"

[[quotes]]
quote = "To the mind that is still, the whole universe surrenders."
author = "Lao Tzu"

[[quotes]]
quote = "I'm different, and I have to be a warrior to be that way. But I have had some success; I hope I have touched the lives of some wonderful people, all by being what I see as myself but some others people see as different."
author = "Johnny Weir"

[[quotes]]
quote = "Honesty and integrity are absolutely essential for success in life - all areas of life. The really good news is that anyone can develop both honesty and integrity."
author = "Zig Ziglar"

[[quotes]]
quote = "I'm still craving approval from my parents. It took a lot of success for me to realize it was never coming. It's just not in their nature."
author = "Andrew Stanton"

[[quotes]]
quote = "There is little success where there is little laughter."
author = "Andrew Carnegie"

[[quotes]]
quote = "Every day is a new opportunity. You can build on yesterday's success or put its failures behind and start over again. That's the way life is, with a new game every day, and that's the way baseball is."
author = "Bob Feller"

[[quotes]]
quote = "Keep your feet on the ground, but let your heart soar as high as it will. Refuse to be average or to surrender to the chill of your spiritual environment."
author = "Arthur Helps"

[[quotes]]
quote = "The number of stressors has multiplied exponentially: traffic, money, success, work/life balance, the economy, the environment, parenting, family conflict, relationships, disease. As the nature of human life has become far more complicated, our ancient stress response hasn't been able to keep up."
author = "Andrew J. Bernstein"

[[quotes]]
quote = "Money won't create success, the freedom to make it will."
author = "Nelson Mandela"
