[[quotes]]
quote = "Young people need the hands-on training that comes with a summer job. They need to know how to dress for success and nail job interviews. But most of all, they need mentorship, guidance, and inspiration."
author = "Hilda Solis"

[[quotes]]
quote = "There is nothing impossible to him who will try."
author = "Alexander the Great"

[[quotes]]
quote = "Success is only meaningful and enjoyable if it feels like your own."
author = "Michelle Obama"

[[quotes]]
quote = "Success is the progressive realization of predetermined, worthwhile, personal goals."
author = "Paul J. Meyer"

[[quotes]]
quote = "If opportunity doesn't knock, build a door."
author = "Milton Berle"

[[quotes]]
quote = "When you have a dream, you've got to grab it and never let go."
author = "Carol Burnett"

[[quotes]]
quote = "Do not wait to strike till the iron is hot; but make it hot by striking."
author = "William Butler Yeats"

[[quotes]]
quote = "I like to put on hardcore when I have to clean my apartment, which I hate to do, but it's motivational. I like old heavy metal when I'm outside working on my car. Music has definite functions for me."
author = "Peter Steele"

[[quotes]]
quote = "Success is steady progress toward one's personal goals."
author = "Jim Rohn"

[[quotes]]
quote = "Give Obama a script he has made his own, and he is the motivational speaker to end all speakers. Tony Robbins cloned with Honest Abe."
author = "Tina Brown"

[[quotes]]
quote = "The moment we believe that success is determined by an ingrained level of ability as opposed to resilience and hard work, we will be brittle in the face of adversity."
author = "Joshua Waitzkin"
