[[quotes]]
quote = "There's no escalators - there's only staircases to success. There is no substitute for hard work."
author = "Lilly Singh"

[[quotes]]
quote = "What we achieve inwardly will change outer reality."
author = "Plutarch"

[[quotes]]
quote = "People tell you the world looks a certain way. Parents tell you how to think. Schools tell you how to think. TV. Religion. And then at a certain point, if you're lucky, you realize you can make up your own mind. Nobody sets the rules but you. You can design your own life."
author = "Carrie-Anne Moss"

[[quotes]]
quote = "Failure is not our only punishment for laziness; there is also the success of others."
author = "Jules Renard"

[[quotes]]
quote = "The Wright brothers flew right through the smoke screen of impossibility."
author = "Charles Kettering"

[[quotes]]
quote = "Success seems to be largely a matter of hanging on after others have let go."
author = "William Feather"

[[quotes]]
quote = "To be ready to fail is to be prepared for success."
author = "Jose Bergamin"

[[quotes]]
quote = "They can conquer who believe they can."
author = "Virgil"

[[quotes]]
quote = "Keep your face always toward the sunshine - and shadows will fall behind you."
author = "Walt Whitman"

[[quotes]]
quote = "I think baking is very rewarding, and if you follow a good recipe, you will get success."
author = "Mary Berry"

[[quotes]]
quote = "Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world."
author = "Desmond Tutu"
