[[quotes]]
quote = "Every city across the country that has successfully renewed and revitalized itself points to a robust education system as its fundamental key to success."
author = "Alan Autry"

[[quotes]]
quote = "Divorce is never a pleasant experience. You look upon it as a failure. But I learned to be a different person once we broke up. Sometimes you learn more from failure than you do from success."
author = "Michael Crawford"

[[quotes]]
quote = "Half a century ago, the amazing courage of Rosa Parks, the visionary leadership of Martin Luther King, and the inspirational actions of the civil rights movement led politicians to write equality into the law and make real the promise of America for all her citizens."
author = "David Cameron"

[[quotes]]
quote = "A true friend is one who overlooks your failures and tolerates your success!"
author = "Doug Larson"

[[quotes]]
quote = "Challenge is the pathway to engagement and progress in our lives. But not all challenges are created equal. Some challenges make us feel alive, engaged, connected, and fulfilled. Others simply overwhelm us. Knowing the difference as you set bigger and bolder challenges for yourself is critical to your sanity, success, and satisfaction."
author = "Brendon Burchard"

[[quotes]]
quote = "Success is a terrible thing and a wonderful thing. If you can enjoy it, it's wonderful. If it starts eating away at you, and they're waiting for more from me, or what can I do to top this, then you're in trouble. Just do what you love. That's all I want to do."
author = "Gene Wilder"

[[quotes]]
quote = "Humility is the true key to success. Successful people lose their way at times. They often embrace and overindulge from the fruits of success. Humility halts this arrogance and self-indulging trap. Humble people share the credit and wealth, remaining focused and hungry to continue the journey of success."
author = "Rick Pitino"

[[quotes]]
quote = "If people ask me for the ingredients of success, I say one is talent, two is stubbornness or determination, and third is sheer luck. You have to have two out of the three. Any two will probably do."
author = "Fred Saberhagen"

[[quotes]]
quote = "The meaning I picked, the one that changed my life: Overcome fear, behold wonder."
author = "Richard Bach"

[[quotes]]
quote = "Once I knew only darkness and stillness... my life was without past or future... but a little word from the fingers of another fell into my hand that clutched at emptiness, and my heart leaped to the rapture of living."
author = "Helen Keller"

[[quotes]]
quote = "Success is simple. Do what's right, the right way, at the right time."
author = "Arnold H. Glasow"
