[[quotes]]
quote = "We do not realise that we are children of eternity. If we did, then success would be no success, and failure would be no failure to us."
author = "Joseph Barber Lightfoot"

[[quotes]]
quote = "Well, certainly one of the ironies of the success of affirmative action is that the middle class within the black community no longer lives within 'black community' by and large."
author = "Henry Louis Gates"

[[quotes]]
quote = "All my music is inspirational. You just gotta listen to the words and get what you can get out of it."
author = "Young Jeezy"

[[quotes]]
quote = "Nobody travels on the road to success without a puncture or two."
author = "Navjot Singh Sidhu"

[[quotes]]
quote = "Our success in Singapore was a Herculean effort by the whole team. Now I am determined to deliver on all we promised. I will be watching like a hawk."
author = "Sebastian Coe"

[[quotes]]
quote = "I know where I'm going and I know the truth, and I don't have to be what you want me to be. I'm free to be what I want."
author = "Muhammad Ali"

[[quotes]]
quote = "Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable."
author = "John Wooden"

[[quotes]]
quote = "One goes through school, college, medical school and one's internship learning little or nothing about goodness but a good deal about success."
author = "Ashley Montagu"

[[quotes]]
quote = "If you create incredible value and information for others that can change their lives - and you always stay focused on that service - the financial success will follow."
author = "Brendon Burchard"

[[quotes]]
quote = "Winning isn't everything, but it beats anything in second place."
author = "William C. Bryant"

[[quotes]]
quote = "Love and desire are the spirit's wings to great deeds."
author = "Johann Wolfgang von Goethe"
