[[quotes]]
quote = "Success is having to worry about every damn thing in the world, except money."
author = "Johnny Cash"

[[quotes]]
quote = "The cost of our success is the exhaustion of natural resources, leading to energy crises, climate change, pollution, and the destruction of our habitat. If you exhaust natural resources, there will be nothing left for your children. If we continue in the same direction, humankind is headed for some frightful ordeals, if not extinction."
author = "Christian de Duve"

[[quotes]]
quote = "One of the rewards of success is freedom, the ability to do whatever you like."
author = "Sting"

[[quotes]]
quote = "How can they say my life is not a success? Have I not for more than sixty years got enough to eat and escaped being eaten?"
author = "Logan Pearsall Smith"

[[quotes]]
quote = "Belief creates the actual fact."
author = "William James"

[[quotes]]
quote = "I am not afraid of tomorrow, for I have seen yesterday and I love today!"
author = "William Allen White"

[[quotes]]
quote = "If you always put limit on everything you do, physical or anything else. It will spread into your work and into your life. There are no limits. There are only plateaus, and you must not stay there, you must go beyond them."
author = "Bruce Lee"

[[quotes]]
quote = "Happiness lies in the joy of achievement and the thrill of creative effort."
author = "Franklin D. Roosevelt"

[[quotes]]
quote = "Achieve success in any area of life by identifying the optimum strategies and repeating them until they become habits."
author = "Charles J. Givens"

[[quotes]]
quote = "If you're going through hell, keep going."
author = "Winston Churchill"

[[quotes]]
quote = "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will."
author = "Vince Lombardi"
