[[quotes]]
quote = "Just remember, you can't climb the ladder of success with your hands in your pockets."
author = "Arnold Schwarzenegger"

[[quotes]]
quote = "We fall forward to succeed."
author = "Mary Kay Ash"

[[quotes]]
quote = "The American Dream is one of success, home ownership, college education for one's children, and have a secure job to provide these and other goals."
author = "Leonard Boswell"

[[quotes]]
quote = "Success requires first expending ten units of effort to produce one unit of results. Your momentum will then produce ten units of results with each unit of effort."
author = "Charles J. Givens"

[[quotes]]
quote = "Success is not a function of the size of your title but the richness of your contribution."
author = "Robin S. Sharma"

[[quotes]]
quote = "Success is full of promise till one gets it, and then it seems like a nest from which the bird has flown."
author = "Henry Ward Beecher"

[[quotes]]
quote = "All I can do will only ever be a faint image of what I see and my success will always be less than my failure or perhaps equal to the failure."
author = "Alberto Giacometti"

[[quotes]]
quote = "It is the combination of reasonable talent and the ability to keep going in the face of defeat that leads to success."
author = "Martin Seligman"

[[quotes]]
quote = "Tomorrow is the most important thing in life. Comes into us at midnight very clean. It's perfect when it arrives and it puts itself in our hands. It hopes we've learned something from yesterday."
author = "John Wayne"

[[quotes]]
quote = "Whatever you vividly imagine, ardently desire, sincerely believe, and enthusiastically act upon... must inevitably come to pass!"
author = "Paul J. Meyer"

[[quotes]]
quote = "Being happy is of the utmost importance. Success in anything is through happiness."
author = "Maharishi Mahesh Yogi"
