[[quotes]]
quote = "I tried out various experiments described in treatises on physics and chemistry, and the results were sometimes unexpected. At times, I would be encouraged by a little unhoped-for success; at others, I would be in the deepest despair because of accidents and failures resulting from my inexperience."
author = "Marie Curie"

[[quotes]]
quote = "One might think that the money value of an invention constitutes its reward to the man who loves his work. But... I continue to find my greatest pleasure, and so my reward, in the work that precedes what the world calls success."
author = "Thomas A. Edison"

[[quotes]]
quote = "In the end, you make your reputation and you have your success based upon credibility and being able to provide people who are really hungry for information what they want."
author = "Brit Hume"

[[quotes]]
quote = "Never continue in a job you don't enjoy. If you're happy in what you're doing, you'll like yourself, you'll have inner peace. And if you have that, along with physical health, you will have had more success than you could possibly have imagined."
author = "Johnny Carson"

[[quotes]]
quote = "My childhood, adolescence and high school days are unusually important. If there has ever been a time that I developed a uniqueness and sense of humor and the ability to organize, it was then. In those early days, I developed the skills that gave me a certain degree of success in American politics."
author = "Lee Atwater"

[[quotes]]
quote = "Why be a man when you can be a success?"
author = "Bertolt Brecht"

[[quotes]]
quote = "Nothing succeeds like the appearance of success."
author = "Christopher Lasch"

[[quotes]]
quote = "I thought 'Moulin Rouge' was inspirational, and 'Jesus Christ Superstar' I loved."
author = "Pierce Brosnan"

[[quotes]]
quote = "Your personal life, your professional life, and your creative life are all intertwined. I went through a few very difficult years where I felt like a failure. But it was actually really important for me to go through that. Struggle, for me, is the most inspirational thing in the world at the end of the day - as long as you treat it that way."
author = "Skylar Grey"

[[quotes]]
quote = "The leaders who we admire who have been able to bring great change in the past - Gandhi, Martin Luther King, Nelson Mandela - they're all inspirational religious leaders and smart tacticians. It would be nice to find the Muslim Gandhi, wouldn't it?"
author = "Dennis C. Blair"

[[quotes]]
quote = "Much effort, much prosperity."
author = "Euripides"
