[[quotes]]
quote = "The real success in golf lies in turning three shots into two."
author = "Bobby Locke"

[[quotes]]
quote = "Don't confuse fame with success. Madonna is one; Helen Keller is the other."
author = "Erma Bombeck"

[[quotes]]
quote = "Of all things visible, the highest is the heaven of the fixed stars."
author = "Nicolaus Copernicus"

[[quotes]]
quote = "Future peace, prosperity and confidence depend not just on ourselves but on the success of all nations. Hence, we are all partners, no matter what our backgrounds, cultures, faiths and histories."
author = "Hassanal Bolkiah"

[[quotes]]
quote = "A rejection is nothing more than a necessary step in the pursuit of success."
author = "Bo Bennett"

[[quotes]]
quote = "Reach for it. Push yourself as far as you can."
author = "Christa McAuliffe"

[[quotes]]
quote = "Our goals can only be reached through a vehicle of a plan, in which we must fervently believe, and upon which we must vigorously act. There is no other route to success."
author = "Pablo Picasso"

[[quotes]]
quote = "Religious speech is extreme, emotional, and motivational. It is anti-literal, relying on metaphor, allusion, and other rhetorical devices, and it assumes knowledge within a community of believers."
author = "Amy Waldman"

[[quotes]]
quote = "Despite the success cult, men are most deeply moved not by the reaching of the goal but by the grandness of the effort involved in getting there - or failing to get there."
author = "Max Lerner"

[[quotes]]
quote = "My tastes and inspirational artists were always rather eclectic and diverse."
author = "Taylor Dayne"

[[quotes]]
quote = "If a man has been his mother's undisputed darling he retains throughout life the triumphant feeling, the confidence in success, which not seldom brings actual success along with it."
author = "Sigmund Freud"
