[[quotes]]
quote = "Life is what happens to you while you’re busy making other plans."
author = "John Lennon"

[[quotes]]
quote = "We become what we think about."
author = "Earl Nightingale"

[[quotes]]
quote = "The most common way people give up their power is by thinking they don’t have any."
author = "Alice Walker"

[[quotes]]
quote = "The mind is everything. What you think you become."
author = "Buddha"

[[quotes]]
quote = "The best time to plant a tree was 20 years ago. The second best time is now."
author = "Chinese Proverb"

[[quotes]]
quote = "An unexamined life is not worth living."
author = "Socrates"

[[quotes]]
quote = "Eighty percent of success is showing up."
author = "Woody Allen"

[[quotes]]
quote = "Difficulties strengthen the mind, as labor does the body."
author = "Seneca"

[[quotes]]
quote = "There is no easy way from the earth to the stars"
author = "Seneca"

[[quotes]]
quote = "It is the power of the mind to be unconquerable."
author = "Seneca"

[[quotes]]
quote = "What man actually needs is not a tensionless state but rather the striving and struggling for some goal worthy of him."
author = "Viktor Frankl"
