[[quotes]]
quote = "If the world seems cold to you, kindle fires to warm it."
author = "Lucy Larcom"

[[quotes]]
quote = "If you want to be truly successful invest in yourself to get the knowledge you need to find your unique factor. When you find it and focus on it and persevere your success will blossom."
author = "Sydney Madwed"

[[quotes]]
quote = "Your success depends mainly upon what you think of yourself and whether you believe in yourself."
author = "William J. H. Boetcker"

[[quotes]]
quote = "I had hoped when my life was chronicled, it would be an inspirational story."
author = "Om Puri"

[[quotes]]
quote = "By failing to prepare, you are preparing to fail."
author = "Benjamin Franklin"

[[quotes]]
quote = "We all obviously need others to look up to, and be inspirational to us. Ford did a great job as far as putting the presidency back where it belonged, getting the trust back after Nixon. And President Reagan has been one of the most influential presidents."
author = "Steve Garvey"

[[quotes]]
quote = "Two roads diverged in a wood and I - I took the one less traveled by, and that has made all the difference."
author = "Robert Frost"

[[quotes]]
quote = "My first book was called, 'Mountain, Get Out of My Way,' where I did an autobiographical sketch, if you will, looking back at myself and looking back at things in my life, and juxtaposing them against things that are happening in other people's lives and trying to be motivational."
author = "Montel Williams"

[[quotes]]
quote = "How wonderful it is that nobody need wait a single moment before starting to improve the world."
author = "Anne Frank"

[[quotes]]
quote = "We should measure welfare's success by how many people leave welfare, not by how many are added."
author = "Ronald Reagan"

[[quotes]]
quote = "Roosevelt's declaration that Americans had 'nothing to fear but fear itself' was a glorious piece of inspirational rhetoric and just as gloriously wrong."
author = "Russell Baker"
