[[quotes]]
quote = "Enjoying success requires the ability to adapt. Only by being open to change will you have a true opportunity to get the most from your talent."
author = "Nolan Ryan"

[[quotes]]
quote = "'Tis pleasant, sure, to see one's name in print. A book's a book, although there's nothing in 't."
author = "Lord Byron"

[[quotes]]
quote = "Faith is love taking the form of aspiration."
author = "William Ellery Channing"

[[quotes]]
quote = "Success in training the boy depends largely on the Scoutmaster's own personal example."
author = "Robert Baden-Powell"

[[quotes]]
quote = "When I was working at the Sprint store, I got laid off. I was bummed out, but I stayed positive. I used the money I had earned while working there to make my first album. Without that job, maybe 'Corazon Sin Cara' would never had been made. It's a very inspirational story."
author = "Prince Royce"

[[quotes]]
quote = "Applause waits on success."
author = "Benjamin Franklin"

[[quotes]]
quote = "Health is the greatest possession. Contentment is the greatest treasure. Confidence is the greatest friend. Non-being is the greatest joy."
author = "Lao Tzu"

[[quotes]]
quote = "Good ideas are like Nike sports shoes. They may facilitate success for an athlete who possesses them, but on their own they are nothing but an overpriced pair of sneakers. Sports shoes don't win races. Athletes do."
author = "Felix Dennis"

[[quotes]]
quote = "I am not a has-been. I am a will be."
author = "Lauren Bacall"

[[quotes]]
quote = "To be a good loser is to learn how to win."
author = "Carl Sandburg"

[[quotes]]
quote = "Someone is sitting in the shade today because someone planted a tree a long time ago."
author = "Warren Buffett"
