[[quotes]]
quote = "Hope is some extraordinary spiritual grace that God gives us to control our fears, not to oust them."
author = "Vincent McNabb"

[[quotes]]
quote = "Being kind is the most important thing I've ever been taught. That's what my parents always told me - more important than ambition or success is being kind to people. The cornerstone of my life. What I aspire to is to be kind."
author = "Rafe Spall"

[[quotes]]
quote = "The development of our human resources is an area in which we need to do well as it is decisive in determining the success of our diversification programme."
author = "Hassanal Bolkiah"

[[quotes]]
quote = "Follow your bliss and the universe will open doors where there were only walls."
author = "Joseph Campbell"

[[quotes]]
quote = "Step by step and the thing is done."
author = "Charles Atlas"

[[quotes]]
quote = "I learned that we can do anything, but we can't do everything... at least not at the same time. So think of your priorities not in terms of what activities you do, but when you do them. Timing is everything."
author = "Dan Millman"

[[quotes]]
quote = "You don't look out there for God, something in the sky, you look in you."
author = "Alan Watts"

[[quotes]]
quote = "How does one measure the success of a museum?"
author = "J. Paul Getty"

[[quotes]]
quote = "Your positive action combined with positive thinking results in success."
author = "Shiv Khera"

[[quotes]]
quote = "One of the things that happens in the business is that success is a very strange thing in that if you are involved in something very successful the next person wants you to repeat it."
author = "Elmer Bernstein"

[[quotes]]
quote = "Success doesn't mean that you are healthy, success doesn't mean that you're happy, success doesn't mean that you're rested. Success really doesn't mean that you look good, or feel good, or are good."
author = "Victoria Principal"
