[[quotes]]
quote = "Tell me, why is the media here so negative? Why are we in India so embarrassed to recognise our own strengths, our achievements? We are such a great nation. We have so many amazing success stories but we refuse to acknowledge them. Why?"
author = "A. P. J. Abdul Kalam"

[[quotes]]
quote = "Success is 99 percent failure."
author = "Soichiro Honda"

[[quotes]]
quote = "Well I think any author or musician is anxious to have legitimate sales of their products, partly so they're rewarded for their success, partly so they can go on and do new things."
author = "Bill Gates"

[[quotes]]
quote = "Basically, when you get to my age, you'll really measure your success in life by how many of the people you want to have love you actually do love you."
author = "Warren Buffett"

[[quotes]]
quote = "Every story I create, creates me. I write to create myself."
author = "Octavia E. Butler"

[[quotes]]
quote = "Success is a great deodorant."
author = "Elizabeth Taylor"

[[quotes]]
quote = "You might well remember that nothing can bring you success but yourself."
author = "Napoleon Hill"

[[quotes]]
quote = "Success and failure are equally disastrous."
author = "Tennessee Williams"

[[quotes]]
quote = "What's on my playlist when I'm fighting is not so much hip-hop. Sometimes, it's something more inspirational. I get a chance to think about what I'm fighting for, like, my family. It takes me to that state because a lot of times, it's a spiritual warfare for me."
author = "Tyron Woodley"

[[quotes]]
quote = "The government will see that human spaceflight is useful - for science and the economy - and inspirational."
author = "Helen Sharman"

[[quotes]]
quote = "Nothing good comes in life or athletics unless a lot of hard work has preceded the effort. Only temporary success is achieved by taking short cuts."
author = "Roger Staubach"
