[[quotes]]
quote = "We've stayed really normal and down to Earth I think, and haven't let the success thing go to our head."
author = "Ashley Olsen"

[[quotes]]
quote = "Success - keeping your mind awake and your desire asleep."
author = "Walter Scott"

[[quotes]]
quote = "I want to build a legacy at the WWE, but I definitely want to continue to grow the Bella Empire. I want it to go beyond the ring. I would love to be a motivational speaker."
author = "Nikki Bella"

[[quotes]]
quote = "Happiness is a butterfly, which when pursued, is always just beyond your grasp, but which, if you will sit down quietly, may alight upon you."
author = "Nathaniel Hawthorne"

[[quotes]]
quote = "My success just evolved from working hard at the business at hand each day."
author = "Johnny Carson"

[[quotes]]
quote = "True success is overcoming the fear of being unsuccessful."
author = "Paul Sweeney"

[[quotes]]
quote = "There are physical characteristics which are inherited. These include things like good looks, high intelligence, physical coordination. These attributes contribute to success in life, and success in life is a determinant of optimism."
author = "Martin Seligman"

[[quotes]]
quote = "Part of the secret of a success in life is to eat what you like and let the food fight it out inside."
author = "Mark Twain"

[[quotes]]
quote = "Before success comes in any man's life, he's sure to meet with much temporary defeat and, perhaps some failures. When defeat overtakes a man, the easiest and the most logical thing to do is to quit. That's exactly what the majority of men do."
author = "Napoleon Hill"

[[quotes]]
quote = "It is not the style of clothes one wears, neither the kind of automobile one drives, nor the amount of money one has in the bank, that counts. These mean nothing. It is simply service that measures success."
author = "George Washington Carver"

[[quotes]]
quote = "It doesn't matter whether you are pursuing success in business, sports, the arts, or life in general: The bridge between wishing and accomplishing is discipline."
author = "Harvey Mackay"
