[[quotes]]
quote = "Money does not guarantee success."
author = "Jose Mourinho"

[[quotes]]
quote = "I feel lucky because I was a nerd, which I talk about in the book, but I had academic success, so through that, because that's what my parents put a great deal of value on, I had a great childhood because I sort of fulfilled the expectations of being good at school."
author = "Mindy Kaling"

[[quotes]]
quote = "Israel was not created in order to disappear - Israel will endure and flourish. It is the child of hope and the home of the brave. It can neither be broken by adversity nor demoralized by success. It carries the shield of democracy and it honors the sword of freedom."
author = "John F. Kennedy"

[[quotes]]
quote = "I've found that luck is quite predictable. If you want more luck, take more chances. Be more active. Show up more often."
author = "Brian Tracy"

[[quotes]]
quote = "Ultimately, leadership is not about glorious crowning acts. It's about keeping your team focused on a goal and motivated to do their best to achieve it, especially when the stakes are high and the consequences really matter. It is about laying the groundwork for others' success, and then standing back and letting them shine."
author = "Chris Hadfield"

[[quotes]]
quote = "Elegance is not a dispensable luxury but a factor that decides between success and failure."
author = "Edsger Dijkstra"

[[quotes]]
quote = "In business, you can have one massive success that earns $50 million overnight, and that's it. You're successful. End of story. But in the music business, you have to keep on doing it."
author = "Noel Gallagher"

[[quotes]]
quote = "From what we get, we can make a living; what we give, however, makes a life."
author = "Arthur Ashe"

[[quotes]]
quote = "If you look at a building by Mies van der Rohe, it might look very simple, but up close, the sheer quality of construction, materials and thought are inspirational."
author = "David Chipperfield"

[[quotes]]
quote = "I think people who are creative are the luckiest people on earth. I know that there are no shortcuts, but you must keep your faith in something Greater than You, and keep doing what you love. Do what you love, and you will find the way to get it out to the world."
author = "Judy Collins"

[[quotes]]
quote = "I'm very fond of the British cinema. I'm a big fan of Martin Campbell and Daniel Craig. I actually find Daniel very inspirational, especially on the physical side of things. He really inspired me to get back into shape when I started to add on a few pounds. I think he's a great role model."
author = "Steven Bauer"
