[[quotes]]
quote = "I suppose your security is your success and your key to success is your fine palate."
author = "Gordon Ramsay"

[[quotes]]
quote = "The secret of success is sincerity."
author = "Jean Giraudoux"

[[quotes]]
quote = "In actuality, California could be a wonderful place to live. In fact, if you're highly educated and ambitious, you can do quite well here while enjoying the sun and the fun. The only problem: California will then blame you for your success and recommend that all your cash be removed from you."
author = "Ben Shapiro"

[[quotes]]
quote = "My dad told me, 'It takes fifteen years to be an overnight success', and it took me seventeen and a half years."
author = "Adrien Brody"

[[quotes]]
quote = "The breaking of a wave cannot explain the whole sea."
author = "Vladimir Nabokov"

[[quotes]]
quote = "Go out and do something. It isn’t your room that’s a prison, it’s yourself."
author = "Sylvia Plath"

[[quotes]]
quote = "A man sees in the world what he carries in his heart."
author = "Johann Wolfgang von Goethe"

[[quotes]]
quote = "Nobody knows what you feel inside unless you tell them."
author = "Banksy"

[[quotes]]
quote = "Do it or don’t do it — you will regret both."
author = "Søren Kierkegaard"

[[quotes]]
quote = "The saddest thing that can happen to a person is to find out their memories are lies."
author = "Juan Gabriel Vásquez"

[[quotes]]
quote = "You are beautiful because you let yourself feel, and that is a brave thing indeed."
author = "Shinji Moon"
