[[quotes]]
quote = "New beginnings are often disguised as painful endings."
author = "Lao Tzu"

[[quotes]]
quote = "People think you’re crazy if you talk about things they don’t understand."
author = "Elvis Presley"

[[quotes]]
quote = "You are not free until you have no need to impress anybody."
author = "Joyce Meyer"

[[quotes]]
quote = "Whatever it is you’re seeking won’t come in the form you’re expecting."
author = "Haruki Murakami"

[[quotes]]
quote = "Don’t be afraid. There are exquisite things in store for you. This is merely the beginning."
author = "Oscar Wilde"

[[quotes]]
quote = "People grow when they are loved well. If you want to help others heal, love them without an agenda."
author = "Mike McHargue"

[[quotes]]
quote = "The truth is rarely pure and never simple."
author = "Oscar Wilde"

[[quotes]]
quote = "People do not seem to realise that their opinion of the world is also a confession of their character."
author = "Ralph Waldo Emerson"

[[quotes]]
quote = "We are all broken, that’s how the light gets in."
author = "Ernest Hemingway"

[[quotes]]
quote = "Having a soft heart in a cruel world is courage, not weakness."
author = "Katherine Henson"

[[quotes]]
quote = "It’s so much darker when a light goes out than it would have been if it had never shone."
author = "John Steinbeck"
