[[quotes]]
quote = "Don’t allow your wounds to turn you into a person you are not."
author = "Paulo Coelho"

[[quotes]]
quote = "The bad news is time flies. The good news is you’re the pilot."
author = "Michael Atshuler"

[[quotes]]
quote = "A work well begun is half-ended."
author = "Plato"

[[quotes]]
quote = "When nothing seems to help, I go and look at a stonecutter hammering away at his rock, perhaps a hundred times without as much as a crack showing in it. Yet at the hundred and first blow it will split in two, and I know it was not that last blow that did it, but all that had gone before."
author = "Jacob Riis"

[[quotes]]
quote = "We have committed the Golden Rule to memory; let us now commit it to life."
author = "Edwin Markham"

[[quotes]]
quote = "Ideas are a dime a dozen. People who implement them are priceless."
author = "Mary Kay Ash"

[[quotes]]
quote = "Purpose and laughter are the twins that must not separate. Each is empty without the other."
author = "Robert Greenleaf"

[[quotes]]
quote = "The only thing even in this world is the number of hours in a day. The difference in winning or losing is what you do with those hours."
author = "Woody Hayes"

[[quotes]]
quote = "Life offers no guarantees... just choices; no certainty... but consequences; no predictable outcomes... just the privilege of pursuit."
author = "Tim Connor"

[[quotes]]
quote = "No pessimist ever discovered the secret of the stars, or sailed to an uncharted land, or opened a new doorway for the human spirit."
author = "Helen Keller"

[[quotes]]
quote = "Discipline is the bridge between goals and accomplishment. "
author = "Jim Rohn"
