[[quotes]]
quote = "The dream is free. The hustle is sold separately."
author = "Unknown"

[[quotes]]
quote = "Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose. You are already naked. There is no reason not to follow your heart."
author = "Steve Jobs"

[[quotes]]
quote = "You can’t use up creativity. The more you use, the more you have."
author = "Maya Angelou"

[[quotes]]
quote = "I always did something I was a little not ready to do. I think that’s how you grow. When there’s that moment of, ‘Wow, I’m not really sure I can do this,’ and you push through those moments, that’s when you have a breakthrough."
author = "Marissa Mayer"

[[quotes]]
quote = "Never let go of that fiery sadness called desire."
author = "Patti Smith"

[[quotes]]
quote = "Challenges are gifts that force us to search for a new center of gravity. Don’t fight them. Just find a new way to stand."
author = "Oprah Winfrey"

[[quotes]]
quote = "What would you do if you weren’t afraid?"
author = "Sheryl Sandberg"

[[quotes]]
quote = "I don’t count my sit-ups; I only start counting when it starts hurting because they’re the only ones that count."
author = "Muhammad Ali"

[[quotes]]
quote = "One, remember to look up at the stars and not down at your feet. Two, never give up work. Work gives you meaning and purpose and life is empty without it. Three, if you are lucky enough to find love, remember it is there and don’t throw it away."
author = "Stephen Hawking"

[[quotes]]
quote = "Innovation distinguishes between a leader and a follower."
author = "Steve Jobs"

[[quotes]]
quote = "I have not failed. I’ve just found 10,000 ways that won’t work."
author = "Thomas Edison"
