[[quotes]]
quote = "If you hear a voice within you say 'you cannot paint', then by all means paint and that voice will be silenced."
author = "Vincent Van Gogh"

[[quotes]]
quote = "Service to others is the rent you pay for your room here on earth"
author = "Muhammad Ali"

[[quotes]]
quote = "One of the hardest decision you'll ever face in life is choosing whether to walk away or try harder."
author = "Ziad K. Abdelnour"

[[quotes]]
quote = "Don't worry if people don't like you. Most people are struggling to like themselves."
author = "Unknown"

[[quotes]]
quote = "Note to self: Keep going. You’re doing great. You might not be where you want to be yet, but that’s okay. Just take it one step at a time and keep believing in yourself. And remember: No matter what happens, you can still enjoy your life and be happy."
author = "Lori Deschene"

[[quotes]]
quote = "People have a way of becoming what you encourage them to be, not what you nag them to be."
author = "Scudder N. Parker"

[[quotes]]
quote = "I am only one, but I am one. I cannot do everything, but I can do something. And I will not let what I cannot do interfere with what I can do."
author = "Edward Everett Hale"

[[quotes]]
quote = "Don’t wait for your feelings to change to take the action. Take the action and your feelings will change."
author = "Barbara Baron"

[[quotes]]
quote = "Better to do something imperfectly than to do nothing flawlessly."
author = "Robert H. Schuller"

[[quotes]]
quote = "Begin doing what you want to do now. We are not living in eternity. We have only this moment, sparkling like a star in our hand-and melting like a snowflake."
author = "Francis Bacon Sr."

[[quotes]]
quote = "Always concentrate on how far you’ve come, rather than how far you have left to go."
author = "Unknown"
