[[quotes]]
quote = "If you find something very difficult to achieve yourself, don't imagine it impossible-for anything possible and proper for another person can be achieved as easily by you."
author = "Marcus Aurelius"

[[quotes]]
quote = "First say to yourself what you would be; and then do what you have to do."
author = "Epictetus"

[[quotes]]
quote = "To be like the rock that the waves keep crashing over. It stands unmoved and the raging of the sea falls still around it."
author = "Marcus Aurelius"

[[quotes]]
quote = "Many are harmed by fear itself, and many may have come to their fate while dreading fate"
author = "Seneca"

[[quotes]]
quote = "If it’s endurable, then endure it. Stop complaining."
author = "Marcus Aurelius"

[[quotes]]
quote = "To bear trials with a calm mind robs misfortune of its strength and burden."
author = "Seneca"

[[quotes]]
quote = "If you would be a good reader, read; if a writer, write."
author = "Epictetus"

[[quotes]]
quote = "...but if a thing is humanly possible, consider it to be within your reach."
author = "Marcus Aurelius"

[[quotes]]
quote = "How long are you going to wait before you demand the best for yourself"
author = "Epictetus"

[[quotes]]
quote = "Fire tries gold, misfortune tries brave men."
author = "Seneca"

[[quotes]]
quote = "True good fortune is what you make for yourself. Good fortune: good character, good intentions, good actions."
author = "Marcus Aurelius"
