[[quotes]]
quote = "Do not go where the path may lead, go instead where there is no path and leave a trail."
author = "Ralph Waldo Emerson"

[[quotes]]
quote = "If you are not willing to risk the usual, you will have to settle for the ordinary."
author = "Jim Rohn"

[[quotes]]
quote = "Music doesn’t lie. If there is something to be changed in this world, then it can only happen through music."
author = "Jimi Hendrix"

[[quotes]]
quote = "When all the original blues guys are gone, you start to realize that someone has to tend to the tradition. I recognize that I have some responsibility to keep the music alive, and it’s a pretty honorable position to be in."
author = "Eric Clapton"

[[quotes]]
quote = "A guitar is like an old friend that is there with me."
author = "B.B. King"

[[quotes]]
quote = "To achieve great things, two things are needed; a plan, and not quite enough time."
author = "Leonard Bernstein"

[[quotes]]
quote = "I am hitting my head against the walls, but the walls are giving way."
author = "Gustav Mahler"

[[quotes]]
quote = "I can't understand why people are frightened of new ideas. I'm frightened of the old ones."
author = "John Cage"

[[quotes]]
quote = "Imagination creates reality."
author = "Richard Wagner"

[[quotes]]
quote = "Please, no matter how we advance technologically, please don't abandon the book. There is nothing in our material world more beautiful than the book."
author = "Patti Smith"

[[quotes]]
quote = "Music is my religion."
author = " Jimi Hendrix"
