[[quotes]]
quote = "There is nothing permanent except change."
author = "Heraclitus"

[[quotes]]
quote = "Nothing exists except atoms and empty space; everything else is just opinion."
author = "Democritus"

[[quotes]]
quote = "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times, I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed."
author = "Michael Jordan"

[[quotes]]
quote = "Fear is not evil. It tells you what weakness is. And once you know your weakness, you can become stronger as well as kinder."
author = "Unknown"

[[quotes]]
quote = "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin."
author = "Mother Teresa"

[[quotes]]
quote = "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to'."
author = "Lao Tzu"

[[quotes]]
quote = "Simplicity is a great virtue but it requires hard work to achieve it and education to appreciate it. And to make matters worse: complexity sells better."
author = "Edsger W. Dijkstra"

[[quotes]]
quote = "Happiness in intelligent people is the rarest thing I know."
author = " Ernest Hemingway"

[[quotes]]
quote = "Happiness is when what you think, what you say, and what you do are in harmony."
author = "Mahatma Gandhi"

[[quotes]]
quote = "Every man has his secret sorrows which the world knows not; and often times we call a man cold when he is only sad."
author = "Henry Wadsworth Longfellow"

[[quotes]]
quote = "If something stands between you and your success, move it. Never be denied."
author = "Dwayne “The Rock” Johnson, professional wrestler and actor"
