[[quotes]]
quote = "You dream. You plan. You reach. There will be obstacles. There will be doubters. There will be mistakes. But with hard work, with belief, with confidence and trust in yourself and those around you, there are no limits."
author = "Michael Phelps, swimmer and Olympic gold medalist"

[[quotes]]
quote = "Bodybuilding is an art, your body is the canvas, weights are your brush and nutrition is your paint. We all have the ability to turn a self-portrait into a masterpiece."
author = "Kai Greene"

[[quotes]]
quote = "Strength does not come from winning. Your struggles develop your strengths."
author = "Arnold Schwarzenegger"

[[quotes]]
quote = " I hated every minute of training, but I said, ”Don’t quit. Suffer now and live the rest of your life as a champion."
author = "Mahummad Ali"

[[quotes]]
quote = "When one person hesitates because he feels inferior, the other is busy making mistakes and becoming superior"
author = "Henry C Link"

[[quotes]]
quote = "The mind always fails first, not the body. The secret is to make your mind work for you, not against you."
author = "Arnold Schwarzenegger"

[[quotes]]
quote = "Go hard or go home"
author = "Phil Heath"

[[quotes]]
quote = "Blood, Sweat and Respect. First Two You Give, Last One You Earn"
author = " Dwayne Johnson | The Rock"

[[quotes]]
quote = "Let Actions Do Your Talkin For You, (Unless Your Telling A Good Dirty Joke)"
author = "Dwayne Johnson | The Rock"

[[quotes]]
quote = "Stay hungry, stay foolish"
author = "Steve Jobs"

[[quotes]]
quote = "Always forgive your enemies - nothing annoys them so much."
author = "Oscar Wilde"
