[[quotes]]
quote = "Life is like riding a bicycle. In order to maintain balance, you must keep moving."
author = "Albert Einstein"

[[quotes]]
quote = "Chains of habit are too light to be felt until they are too heavy to be broken."
author = "Warren Buffett"

[[quotes]]
quote = "The most important investment you can make is in yourself."
author = "Warren Buffett"

[[quotes]]
quote = "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us."
author = "Helen Keller"

[[quotes]]
quote = "He who conquers others is strong, he who conquers himself is mighty."
author = "Lao Tsu"

[[quotes]]
quote = "You only live once, but if you do it right, once is enough."
author = "Mae West"

[[quotes]]
quote = "Don’t complain about what you don’t have. Use what you’ve got. To be less than your best is a sin."
author = "Oprah Winfrey"

[[quotes]]
quote = "The true delight is in the finding out rather than in the knowing."
author = "Isaac Asimov"

[[quotes]]
quote = "People should pursue what they're passionate about. That will make them happier than pretty much anything else."
author = "Elon Musk"

[[quotes]]
quote = "You never lose a dream. It just incubates as a hobby."
author = "Larry Page"

[[quotes]]
quote = "If you're changing the world, you're working on important things. You're excited to get up in the morning."
author = "Larry Page"
