[[quotes]]
quote = "The biggest risk is not taking any risk... In a world that changing really quickly, the only strategy that is guaranteed to fail is not taking risks."
author = "Mark Zuckerberg"

[[quotes]]
quote = "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough."
author = "Mark Zuckerberg"

[[quotes]]
quote = "That brain of mine is something more than merely mortal, as time will show."
author = "Ada Lovelace"

[[quotes]]
quote = "Be yourself; everyone else is already taken."
author = "Oscar Wilde"

[[quotes]]
quote = "We are all in the gutter, but some of us are looking at the stars."
author = "Oscar Wilde"

[[quotes]]
quote = "I may not have gone where I intended to go, but I think I have ended up where I needed to be."
author = "Douglas Adams"

[[quotes]]
quote = "The impossible often has a kind of integrity which the merely improbable lacks."
author = "Douglas Adams"

[[quotes]]
quote = "Sometimes I think we're alone in the universe, and sometimes I think we're not. In either case the idea is quite staggering."
author = "Arthur C. Clarke"

[[quotes]]
quote = "Who controls the past controls the future. Who controls the present controls the past."
author = "George Orwell"

[[quotes]]
quote = "If liberty means anything at all, it means the right to tell people what they do not want to hear."
author = "George Orwell"

[[quotes]]
quote = "Life is tough but so are you."
author = "Anonymous"
