[[quotes]]
quote = "Everyday may not be good but there is something good in everyday."
author = "Anonymous"

[[quotes]]
quote = "Be the reason someone smiles today."
author = "Anonymous"

[[quotes]]
quote = "Comfort is the enemy of achievement."
author = "Farrah Gray"

[[quotes]]
quote = "Luck is where opportunity meets preparation."
author = "Seneca"

[[quotes]]
quote = "Courage is knowing what not to fear."
author = "Plato"

[[quotes]]
quote = "The measure of a man is what he does with power."
author = "Plato"

[[quotes]]
quote = "The beginning is the most important part of the work."
author = "Plato"

[[quotes]]
quote = "Today is not the day I die."
author = "Oberyn Martell"

[[quotes]]
quote = "I don't stop when I am tired, I stop when I am done."
author = "James Bond"

[[quotes]]
quote = "Rhetoric is the art of ruling the minds of men."
author = "Plato"

[[quotes]]
quote = "Philosophy is the highest music."
author = "Plato"
