[[quotes]]
quote = "All men's souls are immortal, but the souls of the righteous are immortal and divine."
author = "Socrates"

[[quotes]]
quote = "You have to be odd to be number one."
author = "Dr. Suess"

[[quotes]]
quote = "Life happens wherever you are, whether you make it or not."
author = "Iroh"

[[quotes]]
quote = "It is usually best to admit mistakes when they occur, and to seek to restore honor.."
author = "Iroh"

[[quotes]]
quote = "Sometimes the best way to solve your own problems is to help someone else."
author = "Iroh"

[[quotes]]
quote = "Push yourself because no one else is going to do it for you."
author = "Unknown"

[[quotes]]
quote = "Your goals don't care how you feel."
author = "Unknown"

[[quotes]]
quote = "Sweat is fat crying."
author = "Unknown"

[[quotes]]
quote = "Be better than you were yesterday."
author = "Unknown"

[[quotes]]
quote = "Rome wasn't built in a day."
author = "Unknown"

[[quotes]]
quote = "Acting like you dont care is not letting it go"
author = "Penelope Douglas"
