[[quotes]]
quote = "If a writer falls in love with you, you can never die."
author = "Mik Everett"

[[quotes]]
quote = "Dont lose a woman that has seen your flaws and still loves you."
author = "Nizar Qabbani"

[[quotes]]
quote = "All suffering originates from craving, from attachment, from desire."
author = "Edgar Allan Poe"

[[quotes]]
quote = "Stop letting people who do so little for you control so much of your mind and emotions."
author = "Will Smith"

[[quotes]]
quote = "You dont have to explain your dreams, they belong to you."
author = "Paulo Coelho"

[[quotes]]
quote = "Sometimes not telling people anything is a good thing."
author = "Jason Myers"

[[quotes]]
quote = "The more you love, the more you suffer."
author = "Vincent van Gogh"

[[quotes]]
quote = "It always takes two. For relationships to work, for them to break apart, for them to be fixed."
author = "Emily Giffin"

[[quotes]]
quote = "Its better to have nobody than someone who is half there, or who doesnt want to be there."
author = "Angelina Jolie"

[[quotes]]
quote = "Dont settle. Dont finish crappy books. If you dont like the menu, leave the restaurant. If youre not on the right path, get off it."
author = "Chris Brogan"

[[quotes]]
quote = "We all romanticize the people we adore."
author = "John Green"
