[[quotes]]
quote = "The cure for anything is salt water. Sweat, tears or the ocean."
author = "Isak Dinesen"

[[quotes]]
quote = "Ten years from now, make sure you can say that you chose your life, you didnt settle for it."
author = "Mandy Hale"

[[quotes]]
quote = "People will love you. People will hate you. And none of it will have anything to do with you."
author = "Abraham Hicks"

[[quotes]]
quote = "Never apologize for burning too brightly or collapsing into yourself every night. That is how galaxies are made."
author = "Tyler Kent White"

[[quotes]]
quote = "Eventually soul mates meet, for they have the same hiding place."
author = "Robert Brault"

[[quotes]]
quote = "Do the scary thing first, and get scared later."
author = "Lemony Snicket"

[[quotes]]
quote = "When you have a bad day, a really bad day, try and treat the world better than it treated you."
author = "Patrick Stump"

[[quotes]]
quote = "You are not weak just because your heart feels so heavy."
author = "Andrea Gibson"

[[quotes]]
quote = "The way to get started is to quit talking ans begin doing."
author = "Walt Disney Company"

[[quotes]]
quote = "Do what is right, not what is easy nor what is popular."
author = "Roy T. Bennett"

[[quotes]]
quote = "Success is not how high you have climbed, but how you make a positive difference to the world."
author = "Roy T. Bennett"
