[[quotes]]
quote = "Create. Not for the money. Not for the fame. Not for the recognition. But for the pure joy of creating something and sharing it."
author = "Ernest Barbaric"

[[quotes]]
quote = "Champions extend their limits and make things happen."
author = "Amit Ray"

[[quotes]]
quote = "Anyone can exist. Most fools do. It takes guts to truly Live."
author = "RMV"

[[quotes]]
quote = "Pour on, I will endure."
author = "William Shakespeare"

[[quotes]]
quote = "This feat I also had no idea how to accomplish, but ignorance had never stopped me from taking action before."
author = "Viet Thanh Nguyen"

[[quotes]]
quote = "Sacred joy exists in any suffering."
author = "Lailah Gift Akita"

[[quotes]]
quote = "Many people will try to Sell you a Dream, its Your place to let them know you Already have one"
author = "Kalon Jackson"

[[quotes]]
quote = "You cannot move things by not moving."
author = "Suzy Kassem"

[[quotes]]
quote = "Butterflies don't know their wings' Colors, but others see their Splendor."
author = "Mohith Agadi"

[[quotes]]
quote = "If you want to be successful, put yourself in a discomfort zone."
author = "Sharfaraz Ahmed"

[[quotes]]
quote = "Sometimes all the players get a bad hand. You just have to be determined enough to see the game through."
author = "Dean Wilson"
