[[quotes]]
quote = "The impediment to action advances action. What stands in the way becomes the way."
author = "Marcus Aurelius"

[[quotes]]
quote = "It is not because things are difficult that we do not dare, it is because we do not dare that they are difficult."
author = "Seneca"

[[quotes]]
quote = "When we are no longer able to change a situation, we are challenged to change ourselves."
author = "Viktor Frankl"

[[quotes]]
quote = "It is a rough road that leads to the heights of greatness."
author = "Seneca"

[[quotes]]
quote = "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present."
author = "Marcus Aurelius"

[[quotes]]
quote = "Choose not to be harmed—and you won’t feel harmed. Don’t feel harmed—and you haven’t been."
author = "Marcus Aurelius"

[[quotes]]
quote = "No man is more unhappy than he who never faces adversity. For he is not permitted to prove himself"
author = "Seneca"

[[quotes]]
quote = "It's not what happens to you, but how you react to it that matters."
author = "Epictetus"

[[quotes]]
quote = "No great thing is created suddenly."
author = "Epictetus"

[[quotes]]
quote = "There is no shame in making an honest effort."
author = "Epictetus"

[[quotes]]
quote = "The Way Get Started Is To Quit Talking And Begin Doing."
author = "Walt Disney"
