[[quotes]]
quote = "Despair and disappointment are the parent of countless inspired, inspiring, triumphant creations."
author = "Rasheed Ogunlaru"

[[quotes]]
quote = "There is a miracle in your mess, don't let the mess make you miss the miracle."
author = "Patience Johnson"

[[quotes]]
quote = "Wishes don't bring riches; work make things work."
author = "Ifeanyi Enoch Onuoha"

[[quotes]]
quote = "If you know your goal and work for it you will reach the peak."
author = "Jounayet Rahman"

[[quotes]]
quote = "Believe you can and you're half way there."
author = "Theodore Roosevelt"

[[quotes]]
quote = "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. As with all matters of the heart, you’ll know when you find it."
author = "Steve Jobs"

[[quotes]]
quote = "Quality is much better than quantity. One home run is much better than two doubles."
author = "Steve Jobs"

[[quotes]]
quote = "You have to trust in something - your gut, destiny, life, karma, whatever.This approach has never let me down."
author = "Steve Jobs"

[[quotes]]
quote = "Hard work spotlights the character of people: some turn up their sleeves, some turn up their noses, and some don't turn up at all."
author = "Sam Ewing"

[[quotes]]
quote = "If you live long enough, you'll make mistakes. But if you learn from them, you'll be a better person. It's how you handle adversity, not how it affects you. The main thing is never quit, never quit, never quit."
author = "Bill Clinton"

[[quotes]]
quote = "If you give people tools, and they use their natural abilities and their curiosity, they will develop things in ways that will surprise you very much beyond what you might have expected."
author = "Bill Gates"
