[[quotes]]
quote = "It's fine to celebrate success, but it is more important to heed the lessons of failure."
author = "Bill Gates"

[[quotes]]
quote = "I'm a greater believer in luck, and I find the harder I work the more I have of it."
author = "Thomas Jefferson"

[[quotes]]
quote = "Perseverance is the hard work you do after you get tired of doing the hard work you already did."
author = "Newt Gingrich"

[[quotes]]
quote = "Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work."
author = "Stephen King"

[[quotes]]
quote = "It's hard to beat a person who never gives up."
author = "Babe Ruth"

[[quotes]]
quote = "The future rewards those who press on. I don't have time to feel sorry for myself. I don't have time to complain. I'm going to press on."
author = "Barack Obama"

[[quotes]]
quote = "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek."
author = "Barack Obama"

[[quotes]]
quote = "The reason a lot of people do not recognize opportunity is because it usually goes around wearing overalls looking like hard work."
author = "Thomas A. Edison"

[[quotes]]
quote = "I do not know anyone who has got to the top without hard work. That is the recipe. It will not always get you to the top, but it should get you pretty near."
author = "Margaret Thatcher"

[[quotes]]
quote = "Nothing ever comes to one, that is worth having, except as a result of hard work."
author = "Booker T. Washington"

[[quotes]]
quote = "When I was young, I observed that nine out of ten things I did were failures. So I did ten times more work."
author = "George Bernard Shaw"
