[[quotes]]
quote = "Opportunities are usually disguised as hard work, so most people don't recognize them."
author = "Ann Landers"

[[quotes]]
quote = "For every two minutes of glamour, there are eight hours of hard work."
author = "Jessica Savitch"

[[quotes]]
quote = "I've got a theory that if you give 100 percent all of the time, somehow things will work out in the end."
author = "Larry Bird"
