[[quotes]]
quote = "The Pessimist Sees Difficulty In Every Opportunity. The Optimist Sees Opportunity In Every Difficulty."
author = "Winston Churchill"

[[quotes]]
quote = "Don’t Let Yesterday Take Up Too Much Of Today."
author = "Will Rogers"

[[quotes]]
quote = "If You Are Working On Something That You Really Care About, You Don’t Have To Be Pushed. The Vision Pulls You."
author = "Steve Jobs"

[[quotes]]
quote = "People Who Are Crazy Enough To Think They Can Change The World, Are The Ones Who Do."
author = "Rob Siltanen"

[[quotes]]
quote = "We May Encounter Many Defeats But We Must Not Be Defeated."
author = "Maya Angelou"

[[quotes]]
quote = "Knowing Is Not Enough; We Must Apply. Wishing Is Not Enough; We Must Do."
author = "Johann Wolfgang Von Goethe"

[[quotes]]
quote = "Imagine Your Life Is Perfect In Every Respect; What Would It Look Like?"
author = "Brian Tracy"

[[quotes]]
quote = "We Generate Fears While We Sit. We Overcome Them By Action."
author = "Dr. Henry Link"

[[quotes]]
quote = "Whether You Think You Can Or Think You Can’t, You’re Right."
author = "Henry Ford"

[[quotes]]
quote = "Security Is Mostly A Superstition. Life Is Either A Daring Adventure Or Nothing."
author = "Helen Keller"

[[quotes]]
quote = "The Man Who Has Confidence In Himself Gains The Confidence Of Others."
author = "Hasidic Proverb"
