[[quotes]]
quote = "The Only Limit To Our Realization Of Tomorrow Will Be Our Doubts Of Today."
author = "Franklin D. Roosevelt"

[[quotes]]
quote = "Creativity Is Intelligence Having Fun."
author = "Albert Einstein"

[[quotes]]
quote = "What You Lack In Talent Can Be Made Up With Desire, Hustle And Giving 110% All The Time."
author = "Don Zimmer"

[[quotes]]
quote = "Do What You Can With All You Have, Wherever You Are."
author = "Theodore Roosevelt"

[[quotes]]
quote = "You Are Never Too Old To Set Another Goal Or To Dream A New Dream."
author = "C.S. Lewis"

[[quotes]]
quote = "To See What Is Right And Not Do It Is A Lack Of Courage."
author = "Confucious"

[[quotes]]
quote = "If you’re going through hell keep going."
author = "Winston Churchill"

[[quotes]]
quote = "Ten people who speak make more noise than ten thousand who are silent."
author = "Napoleon Bonaparte"

[[quotes]]
quote = "We can't help everyone, but everyone can help someone."
author = "Ronald Reagan"

[[quotes]]
quote = "Believe that you can do it cause you can do it."
author = "Bob Ross"

[[quotes]]
quote = "Take a method and try it. If it fails, admit it frankly, and try another. But by all means, try something."
author = "Franklin D. Roosevelt"
