[[quotes]]
quote = "The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe."
author = "Bob Ross"

[[quotes]]
quote = "It always seems impossible until it is done."
author = "Nelson Mandela"

[[quotes]]
quote = "Don't be afraid to give up the good to go for the great."
author = "John D. Rockefeller"

[[quotes]]
quote = "It is better to be hated for what you are than to be loved for what you are not."
author = "André Gide"

[[quotes]]
quote = "You must be the change you wish to see in the world."
author = "Mahatma Gandhi"

[[quotes]]
quote = "Never, never, never give up."
author = "Winston Churchill"

[[quotes]]
quote = "You don't have to be great to start, but you have to start to be great."
author = "Zig Ziglar"

[[quotes]]
quote = "I believe every human has a finite number of heartbeats. I don't intend to waste any of mine."
author = "Neil Armstrong"

[[quotes]]
quote = "Do not pray for easy lives. Pray to be stronger men."
author = "John F. Kennedy"

[[quotes]]
quote = "One today is worth two tomorrows."
author = "Benjamin Franklin"

[[quotes]]
quote = "We rise by lifting others."
author = "Robert G. Ingersoll"
