[[quotes]]
quote = "Failure will never overtake me if my determination to succeed is strong enough."
author = "Og Mandino"

[[quotes]]
quote = "Always do your best. What you plant now, you will harvest later."
author = "Og Mandino"

[[quotes]]
quote = "In order to succeed, we must first believe that we can."
author = "Nikos Kazantzakis"

[[quotes]]
quote = "Nothing is impossible, the word itself says, “I’m possible!”"
author = "Audrey Hepburn"

[[quotes]]
quote = "Try to be a rainbow in someone's cloud."
author = "Maya Angelou"

[[quotes]]
quote = "The very best thing you can do for the whole world is to make the most of yourself."
author = "Wallace D. Wattles"

[[quotes]]
quote = "... because all things have contributed to your advancement, you should include all things in your gratitude."
author = "Wallace D. Wattles"

[[quotes]]
quote = "Thoughts become things. If you see it in your mind, you will hold it in your hand."
author = "Bob Proctor, You Were Born Rich"

[[quotes]]
quote = "Be like a postage stamp. Stick to it until you get there"
author = "Bob Proctor"

[[quotes]]
quote = "Set a goal to achieve something that is so big, so exhilarating that it excites you and scares you at the same time."
author = "Bob Proctor"

[[quotes]]
quote = "Impossible is a word to be found only in the dictionary of fools."
author = "Napoleon Bonaparte"
