[[quotes]]
quote = "My best friend is the one who brings out the best in me."
author = "Henry Ford"

[[quotes]]
quote = "An investment in knowledge pays the best interest."
author = "Benjamin Franklin"

[[quotes]]
quote = "Look at the sky. We are not alone. The whole universe is friendly to us and conspires only to give the best to those who dream and work."
author = "A.P.J. Abdul Kalam"

[[quotes]]
quote = "In any moment of decision, the best thing you can do is the right thing, the next best thing is the wrong thing, and the worst thing you can do is nothing."
author = "Theodore Roosevelt"

[[quotes]]
quote = "Believe you can and you're halfway there."
author = "Theodore Roosevelt"

[[quotes]]
quote = "At his best, man is the noblest of all animals; separated from law and justice he is the worst."
author = "Aristotle"

[[quotes]]
quote = "In the practice of tolerance, one's enemy is the best teacher."
author = "Dalai Lama"

[[quotes]]
quote = "The only real failure in life is not to be true to the best one knows."
author = "Buddha"

[[quotes]]
quote = "The best cure for the body is a quiet mind."
author = "Napoleon Bonaparte"

[[quotes]]
quote = "Education is the best provision for old age."
author = "Aristotle"

[[quotes]]
quote = "The best road to progress is freedom's road."
author = "John F. Kennedy"
