[[quotes]]
quote = "Life is about making an impact, not making an income."
author = "Kevin Kruse"

[[quotes]]
quote = "Every child is an artist.  The problem is how to remain an artist once he grows up."
author = "Pablo Picasso"

[[quotes]]
quote = "You can never cross the ocean until you have the courage to lose sight of the shore."
author = "Christopher Columbus"

[[quotes]]
quote = "Either you run the day, or the day runs you."
author = "Jim Rohn"

[[quotes]]
quote = "The best revenge is massive success."
author = "Frank Sinatra"

[[quotes]]
quote = "Life shrinks or expands in proportion to one's courage."
author = "Anais Nin"

[[quotes]]
quote = "Be who you are and say what you feel, because those who mind don’t matter and those who matter don’t mind."
author = "Dr. Seuss"

[[quotes]]
quote = "Do your own thing on your own terms and get what you came here for."
author = "Oliver James"

[[quotes]]
quote = "The difficult is what takes a little time; the impossible is what takes a little longer."
author = "Fridtjof Nansen"

[[quotes]]
quote = "Braving obstacles and hardships is nobler than retreat to tranquility."
author = "Khalil Gibran"

[[quotes]]
quote = "Cultivation of mind should be the ultimate aim of human existence."
author = "B. R. Ambedkar"
