[[quotes]]
quote = "You have brains in your head and feet in your shoes, you can steer yourself in any direction you choose."
author = "Dr. Seuss"

[[quotes]]
quote = "The mind that tries to shape tomorrow beyond its capacities will find no rest."
author = "Rumi"

[[quotes]]
quote = "One day you will wake up and there won't be any more time to do the things you've always wanted. Do it now"
author = "Paulo Coelho"

[[quotes]]
quote = "The measure of who we are is what we do with what we have."
author = "Vince Lombardi"

[[quotes]]
quote = "As we express our gratitude, we must never forget that the highest appreciation is not to utter words, but to live by them."
author = "John F. Kennedy"

[[quotes]]
quote = "Don't watch the clock; do what it does. Keep going."
author = "Sam Levenson"

[[quotes]]
quote = "Success is not the result of spontaneous combustion. You must set yourself on fire."
author = "Reggie Leach"

[[quotes]]
quote = "Always remember that the future comes one day at a time."
author = "Dean Acheson"

[[quotes]]
quote = "Motivation is what gets you started. Habit is what keeps you going. "
author = "Jim Ryun"

[[quotes]]
quote = "The greatest mistake you can make in life is to be continually fearing you will make one."
author = "Elbert Hubbard"

[[quotes]]
quote = "The secret to happiness is freedom. And the secret to freedom is courage. "
author = "Thucydides"
