[[quotes]]
quote = "The struggle ends when the gratitude begins."
author = "Unknown"

[[quotes]]
quote = "Obsessed is a word that the lazy use to describe the dedicated. "
author = "Unknown"

[[quotes]]
quote = "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. "
author = "Jimmy Dean"

[[quotes]]
quote = "Set your goals high, and don't stop till you get there."
author = "Bo Jackson"

[[quotes]]
quote = "Your life does not get better by chance, it gets better by change."
author = "Anonymous"

[[quotes]]
quote = "I never knew a man come to greatness or eminence who lay abed late in the morning. "
author = "Johnathan Swift"

[[quotes]]
quote = "No matter how you feel, Get up, dress up, show up and never give up."
author = "Anonymous"

[[quotes]]
quote = "To be beautiful means to be yourself. You don't need to be accepted by others. You need to be yourself. "
author = "Thich Nhat Hanh"

[[quotes]]
quote = "Believe that life is worth living and your belief will help create the fact."
author = "William James"

[[quotes]]
quote = "You're going to go through tough times - that's life. But I say, 'Nothing happens to you, it happens for you.' See the positive in negative events. "
author = " Joel Osteen"

[[quotes]]
quote = "Yesterday is not ours to recover, but tomorrow is ours to win or lose."
author = "Lyndon B. Johnson"
