[[quotes]]
quote = "Half our life is spent trying to find something to do with the time we have rushed through life trying to save."
author = "Will Rogers"

[[quotes]]
quote = "It is better to take many small steps in the right direction than to make a great leap forward only to stumble backward."
author = "Proverb"

[[quotes]]
quote = "Act as if what you do makes a difference. It does."
author = "William James"

[[quotes]]
quote = "Don’t be afraid to go out on a limb. That’s where the fruit is."
author = "H. Jackson Browne"

[[quotes]]
quote = "To have striven, to have made the effort, to have been true to certain ideals–this alone is worth the struggle."
author = "William Penn"

[[quotes]]
quote = "Action may not always bring happiness; but there is no happiness without action."
author = "Benjamin Disraeli"

[[quotes]]
quote = "What matters is the value we’ve created in our lives, the people we’ve made happy and how much we’ve grown as people."
author = "Daisaku Ikeda"

[[quotes]]
quote = "A diamond is just a piece of charcoal that handled stress exceptionally well."
author = "Unknown"

[[quotes]]
quote = "Think like a man of action; act like a man of thought."
author = "Henri L. Bergson"

[[quotes]]
quote = "If you get up one more time than you fall, you will make it through"
author = "Chinese Proverb"

[[quotes]]
quote = "He is able who thinks he is able."
author = "Buddha"
