[[quotes]]
quote = "I demolish my bridges behind me...then there is no choice but to move forward."
author = "Fridtjof Nansen"

[[quotes]]
quote = "Life is 10% what happens to you and 90% how you react to it."
author = "Charles R. Swindoll"

[[quotes]]
quote = "The way to get started is to quit talking and begin doing."
author = "Walt Disney"

[[quotes]]
quote = "Even if you fall on your face you’re still moving forward."
author = "Victor Kiam"

[[quotes]]
quote = "Well done is better than well said."
author = "Benjamin Franklin"

[[quotes]]
quote = "It’s always too early to quit."
author = "Norman Vincent Peale"

[[quotes]]
quote = "Leap, and the net will appear."
author = "John Burroughs"

[[quotes]]
quote = "One finds limits by pushing them."
author = "Herbert Simon"

[[quotes]]
quote = "The wise does at once what the fool does at last."
author = "Baltasar Gracian"

[[quotes]]
quote = "Do not watch the clock. Do what it does. Keep going."
author = "Sam Levenson"

[[quotes]]
quote = "I’ve failed over and over and over again. And that is why I succeed."
author = "Michael Jordan"
