[[quotes]]
quote = "The secret of getting ahead is getting started."
author = "Mark Twain"

[[quotes]]
quote = "Either you run the day or the day runs you."
author = "Jim Rohn"

[[quotes]]
quote = "I’d rather attempt to do something great and fail, than to attempt nothing and succeed."
author = "Robert H. Schuller"

[[quotes]]
quote = "Your own resolution to succeed is more important than any other."
author = "Abraham Lincoln"

[[quotes]]
quote = "There is always room at the top."
author = "Daniel Webster"

[[quotes]]
quote = "You can’t build a reputation on what you are going to do."
author = "Henry Ford"

[[quotes]]
quote = "Success is going from failure to failure with no loss of enthusiasm."
author = "Winston Churchill"

[[quotes]]
quote = "Small deeds done are better than great deeds planned."
author = "Peter Marshall"

[[quotes]]
quote = "When you stop chasing the wrong things you give the right things a chance to catch you."
author = "Lolly Daskal"

[[quotes]]
quote = "You just can’t beat the person who never gives up."
author = "Babe Ruth"

[[quotes]]
quote = "The more we do the more we can do."
author = "William Hazlitt"
