[[quotes]]
quote = "Fortune sides with him who dares."
author = "Virgil"

[[quotes]]
quote = "The secret to success is to know something nobody else knows."
author = "Aristotle Onassis"

[[quotes]]
quote = "Don't be distracted by criticism. Remember--the only taste of success some people get is to take a bite out of you."
author = "Zig Ziglar"

[[quotes]]
quote = "Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down."
author = "Charles F. Kettering"

[[quotes]]
quote = "If you really look closely, most overnight successes took a long time."
author = "Steve Jobs"

[[quotes]]
quote = "Without self-discipline, success is impossible, period."
author = "Lou Holtz"

[[quotes]]
quote = "Life is either a daring adventure or nothing."
author = "Helen Keller"

[[quotes]]
quote = "If you quit ONCE it becomes a habit.Never quit!!!"
author = " Michael Jordan"

[[quotes]]
quote = "It is good to dream big but your dreams will never see the light of day if you sleep big too. "
author = "Anonymous"

[[quotes]]
quote = "One day you will wake up and there won't be any more time to do the things you've always wanted. Do it now "
author = " Paulo Coelho"

[[quotes]]
quote = "Put your heart, mind, and soul into even your smallest acts. This is the secret of success. "
author = "Swami Sivananda"
