[[quotes]]
quote = "You're going to go through tough times - that's life. But I say, 'Nothing happens to you, it happens for you.' See the positive in negative events."
author = "Joel Osteen"

[[quotes]]
quote = "To be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others."
author = "Nelson Mandela"

[[quotes]]
quote = "It always seems impossible until it's done. "
author = "Nelson Mandela"

[[quotes]]
quote = "Do more of what makes you happy. "
author = "Carmel McConnell"

[[quotes]]
quote = "If you spend too much time thinking about a thing, you'll never get it done."
author = "Bruce Lee"

[[quotes]]
quote = "You can't climb the ladder of success with your hands in your pockets."
author = "Arnold Schwarzenegger"

[[quotes]]
quote = "It is possible to commit no mistakes and still lose. That is not a weakness; that is life. "
author = "Jean Luc Picard"

[[quotes]]
quote = "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world."
author = "Albert Einstein"

[[quotes]]
quote = "Wake up early and tackle the day before it tackles you. Be on offense, not defense."
author = "Evan Carmichael"

[[quotes]]
quote = "You can have anything you want if you are willing to give up the belief that you can't have it."
author = " Robert Anthony"

[[quotes]]
quote = "Successful people are not gifted; they just work hard, then succeed on purpose. "
author = "G.K.Nielson"
