[[quotes]]
quote = "Do it now.Sometimes 'later' becomes 'never'. "
author = "Anonymous"

[[quotes]]
quote = "FEarly to bed and early to rise, makes a man healthy, wealthy and wise."
author = "Benjamin Franklin"

[[quotes]]
quote = "Never put off till tomorrow what you can do today. "
author = "Thomas Jefferson"

[[quotes]]
quote = "It does not matter how slowly you go as long as you do not stop."
author = "Confucius"

[[quotes]]
quote = "Visualize this thing that you want, see it, feel it, believe in it. Make your mental blue print, and begin to build."
author = "R Collier"

[[quotes]]
quote = "Good things happen to those who hustle."
author = "Anais Nin"

[[quotes]]
quote = "Human beings, by changing the inner attitudes of their minds, can change the outer aspects of their lives."
author = "William James"

[[quotes]]
quote = "Life brings simple pleasures to us every day. It is up to us to make them wonderful memories."
author = "Cathy Allen"

[[quotes]]
quote = "Don't let your sorrow come higher than your knees."
author = "Swedish Proverb"

[[quotes]]
quote = "Begin somewhere; you cannot build a reputation on what you intend to do."
author = "Liz Smith"

[[quotes]]
quote = "Learn all you can from the mistakes of others. You won't have time to make them all yourself."
author = "Alfred Sheinwold"
