[[quotes]]
quote = "A winner makes commitments. A loser makes promises."
author = "Unknown"

[[quotes]]
quote = "Hope sees the invisible, feels the intangible, and achieves the impossible."
author = "Charles Caleb Colton"

[[quotes]]
quote = "It's good to do uncomfortable things. It's weight training for life."
author = "Anne Lamott"

[[quotes]]
quote = "A word of encouragement during a failure is worth more than an hour of praise after success."
author = "Unknown"

[[quotes]]
quote = "The greatest test of courage on earth is to bear defeat without losing heart."
author = "Robert Green Ingersoll"

[[quotes]]
quote = "The past does not equal the future."
author = "Anthony Robbins"

[[quotes]]
quote = "The difference between the impossible and the possible lies in a person's determination."
author = "Tommy Lasorda"

[[quotes]]
quote = "If you put off everything till you're sure of it, you'll never get anything done."
author = "Norman Vincent Peale"

[[quotes]]
quote = "The future belongs to those who believe in the beauty of their dreams."
author = "Eleanor Roosevelt"

[[quotes]]
quote = "Don’t watch the clock; do what it does. Keep going."
author = "Sam Levenson"

[[quotes]]
quote = "Change your life today. Don’t gamble on the future, act now, without delay."
author = "Simone de Beauvoir"
