[[quotes]]
quote = "Start where you are. Use what you have. Do what you can."
author = "Arthur Ashe"

[[quotes]]
quote = "Why should you continue going after your dreams? Because seeing the look on the faces of the people who said you couldn’t will be priceless."
author = "Kevin Ngo"

[[quotes]]
quote = "Never give up, for that is just the place and time that the tide will turn."
author = "Harriet Beecher Stow"

[[quotes]]
quote = "Cautious, careful people, always casting about to preserve their reputations can never effect a reform."
author = "Susan B. Anthony"

[[quotes]]
quote = "When the whole world is silent, even one voice becomes powerful."
author = "Malala Yousafzai"

[[quotes]]
quote = "Make the most of yourself by fanning the tiny, inner sparks of possibility into flames of achievement."
author = "Golda Meir"

[[quotes]]
quote = "Knowing what must be done does away with fear."
author = "Rosa Parks"

[[quotes]]
quote = "Creativity takes courage."
author = "Henri Matisse"

[[quotes]]
quote = "Every artist was first an amateur."
author = "Ralph Waldo Emerson"

[[quotes]]
quote = "We don't make mistakes, just happy little accidents."
author = "Bob Ross"

[[quotes]]
quote = "I am seeking, I am striving, I am in it with all my heart."
author = "Vincent Van Gogh"
