[[quotes]]
quote = "They always say time changes things, but you actually have to change them yourself."
author = "Andy Warhol"

[[quotes]]
quote = "Art washes away from the soul the dust of everyday life."
author = "Pablo Picasso"

[[quotes]]
quote = "The main thing is to be moved, to love, to hope, to tremble, to live."
author = "Auguste Rodin"

[[quotes]]
quote = "To be an artist is to believe in life."
author = "Henry Moore"

[[quotes]]
quote = "Whether you succeed or not is irrelevant, there is no such thing.  Making your unknown known is the important thing."
author = "Georgia O'Keeffe"

[[quotes]]
quote = "What moves men of genius, or rather what inspires their work, is not new ideas, but their obsession with the idea that what has already been said is still not enough."
author = "Eugene Delecroix"

[[quotes]]
quote = "If I create from the heart, nearly everything works; if from the head, almost nothing."
author = "Marc Chagall"

[[quotes]]
quote = "Don’t think about making art, just get it done.  Let everyone else decide if it’s good or bad, whether they love it or hate it.  While they are deciding, make even more art."
author = "Andy Warhol"

[[quotes]]
quote = "If people knew how hard I worked to get my mastery, it wouldn't seem so wonderful at all."
author = "Michaelangelo"

[[quotes]]
quote = "One can have no smaller or greater mastery than mastery of oneself."
author = "Lenoardo da Vinci"

[[quotes]]
quote = "To send light into the darkness of men's hearts - such is the duty of the artist."
author = "Schumann"
