[[quotes]]
quote = "Great things are done by a series of small things brought together."
author = "Vincent van Gogh"

[[quotes]]
quote = "Inspiration does exist but it must find you working."
author = "Pablo Picasso"

[[quotes]]
quote = "Everything has its beauty, but not everyone sees it."
author = "Andy Warhol"

[[quotes]]
quote = "The world of reality has its limits; the world of imagination is boundless."
author = "Jean-Jacques Rousseau"

[[quotes]]
quote = "Do not fear mistakes - there are none."
author = "Miles Davis"

[[quotes]]
quote = "I would rather die of passion than of boredom."
author = "Vincent van Gogh"

[[quotes]]
quote = "An ounce of practice is better than tons of teaching."
author = "Mahatma Gandhi"

[[quotes]]
quote = "The trouble is you think you have time."
author = "Buddha"

[[quotes]]
quote = "The more real you get, the more unreal the world gets."
author = "John Lennon"

[[quotes]]
quote = "Decide that you want it more than you are afraid of it."
author = "Bill Cosby"

[[quotes]]
quote = "Don't give up, Today is hard. Tomorrow will be worse. Day after tomorrow will be sunshine."
author = "Jack Ma"
