[[quotes]]
quote = "If you don't give up, you still have a chance."
author = "Jack Ma"

[[quotes]]
quote = "The only way to work is to love what you do."
author = "Steve Jobs"

[[quotes]]
quote = "Be stubborn about your goals, and flexible about your methods."
author = "Author Unknown"

[[quotes]]
quote = "A dream becomes a goal when action is taken toward its achievement."
author = "Bo Bennet"

[[quotes]]
quote = "The goal is not to get rich. The goal is to live rich."
author = "Darren Hardy"

[[quotes]]
quote = "You can’t go back and make a brand new start. But, you can start now and make a brand new ending."
author = "Anonymous"

[[quotes]]
quote = "Today, figure out what makes you happy and do more of it. Figure out what doesn't and do less of it."
author = "Mandy Hale"

[[quotes]]
quote = "Dont let someone else’s opinion of you become your reality."
author = "Les Brown"

[[quotes]]
quote = "The biggest adventure you can take is to live the life of your dreams."
author = "Oprah Winfrey."

[[quotes]]
quote = "Success does not come to you, you go to it."
author = "Marva Collins."

[[quotes]]
quote = "Success is stumbling from failure to failure with no loss of enthusiasm."
author = "Winston Churchill."
