[[quotes]]
quote = "No matter how hard the past, you can always begin again."
author = "Buddha"

[[quotes]]
quote = "Life is like riding a bicycle. To keep your balance you must keep moving."
author = "Einstein"

[[quotes]]
quote = "Excellence can be obtained if you care more than others think is wise, risk more than others think is safe, dream more than others think is practical, expect more than others think is possible."
author = "Unknown"

[[quotes]]
quote = "Don’t fear failure so much that you refuse to try new things. The saddest summary of life contains three descriptions: could have, might have, and should have."
author = "Unknown"

[[quotes]]
quote = "From small beginnings come great things."
author = "Proverb"

[[quotes]]
quote = "Don’t be pushed by your problems; be led by your dreams."
author = "Unknown"

[[quotes]]
quote = "More powerful than the will to win is the courage to begin."
author = "Unknown"

[[quotes]]
quote = "What lies behind us and what lies before us are tiny matters compared to what lies within us."
author = "Ralph Waldo Emerson"

[[quotes]]
quote = "Fear is a natural reaction to moving closer to the truth."
author = "Pema Chodron"

[[quotes]]
quote = "Commitment in the face of conflict produces character."
author = "Unknown"

[[quotes]]
quote = "Don’t let today’s disappointments cast a shadow on tomorrow’s dreams."
author = "Unknown"
