[[quotes]]
quote = "If you are not willing to risk the usual, you will have to settle for ordinary."
author = "Jim Rohn."

[[quotes]]
quote = "If you want to shine like a sun, first burn like a sun."
author = "APJ Abdul Kalam"

[[quotes]]
quote = "Failure is an opportunity to begin again more intelligently."
author = "Henry Ford."

[[quotes]]
quote = "Only I can change my life. No one can do it for me."
author = "Carol Burnett"

[[quotes]]
quote = "Not how long, but how well you have lived is the main thing."
author = "Seneca"

[[quotes]]
quote = "The energy of the mind is the essence of life."
author = "Aristotle"

[[quotes]]
quote = "Love all, trust a few, do wrong to none."
author = "William Shakespeare"

[[quotes]]
quote = "In 20 years, you probably won't even remember this."
author = "Anonymous"

[[quotes]]
quote = "Never cowardly or cruel. Never give up, never give in."
author = "Doctor Who"

[[quotes]]
quote = "Do what you feel in your heart to be right, for you'll be criticized anyway."
author = "Eleanor Roosevelt."

[[quotes]]
quote = "Plant your garden and decorate your own soul, instead of waiting for someone to bring you flowers."
author = "Jose Luis Borges"
