[[quotes]]
quote = "Nothing in life is to be feared; it is only to be understood. Now is the time to understand more so that we may fear less."
author = "Marie Curie"

[[quotes]]
quote = "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship."
author = "Buddha"

[[quotes]]
quote = "Life is really simple, but we insist on making it complicated."
author = "Confucius"

[[quotes]]
quote = "This too, shall pass."
author = "Anonymous"

[[quotes]]
quote = "There is only one happiness in life – to love and to be loved."
author = "George Sand"

[[quotes]]
quote = "The only person you should try to be better than is the person you were yesterday."
author = "Anonymous"

[[quotes]]
quote = "Never be bullied into silence. Never allow yourself to be made a victim. Accept no one's definition of your life; define yourself."
author = "Harvey Fierstein"

[[quotes]]
quote = "Life's too mysterious to take too serious."
author = "Mary Engelbreit"

[[quotes]]
quote = "It's not about how hard you can hit; it's about how hard you can get hit and keep moving forward."
author = "Rocky Balboa"

[[quotes]]
quote = "It's OK to not be OK, as long as you don't stay that way."
author = "Anonymous"

[[quotes]]
quote = "May I never be complete. May I never be content. May I never be perfect."
author = "Chuck Palahniuk"
