[[quotes]]
quote = "Technology is a useful servant but a dangerous master."
author = "Christian Lous Lange"

[[quotes]]
quote = "The science of today is the technology of tomorrow"
author = "Edward Teller"

[[quotes]]
quote = "The only constant in the technology industry is change"
author = "Marc Benioff"

[[quotes]]
quote = "It's kind of fun to do the impossible."
author = "Walt Disney"

[[quotes]]
quote = "All our dreams can come true, if we have the courage to pursue them."
author = "Walt Disney"

[[quotes]]
quote = "We keep moving forward, opening new doors, and doing new things, because we're curious and curiosity keeps leading us down new paths."
author = "Walt Disney"

[[quotes]]
quote = "You can design and create, and build the most wonderful place in the world. But it takes people to make the dream a reality."
author = "Walt Disney"

[[quotes]]
quote = "When you believe in a thing, believe in it all the way, implicitly and unquestionable."
author = "Walt Disney"

[[quotes]]
quote = "The more you like yourself, the less you are like anyone else, which makes you unique."
author = "Walt Disney"

[[quotes]]
quote = "All the adversity I've had in my life, all my troubles and obstacles, have strengthened me... You may not realize it when it happens, but a kick in the teeth may be the best thing in the world for you."
author = "Walt Disney"

[[quotes]]
quote = "If you can dream it, you can do it."
author = "Walt Disney"
