[[quotes]]
quote = "Times and conditions change so rapidly that we must keep our aim constantly focused on the future."
author = "Walt Disney"

[[quotes]]
quote = "I always like to look on the optimistic side of life, but I am realistic enough to know that life is a complex matter."
author = "Walt Disney"

[[quotes]]
quote = "I do not like to repeat successes, I like to go on to other things."
author = "Walt Disney"

[[quotes]]
quote = "Our heritage and ideals, our code and standards - the things we live by and teach our children - are preserved or diminished by how freely we exchange ideas and feelings."
author = "Walt Disney"

[[quotes]]
quote = "A man should never neglect his family for business."
author = "Walt Disney"

[[quotes]]
quote = "I have been up against tough competition all my life. I wouldn't know how to get along without it."
author = "Walt Disney"

[[quotes]]
quote = "Of all the things I've done, the most vital is coordinating those who work with me and aiming their efforts at a certain goal."
author = "Walt Disney"

[[quotes]]
quote = "Crowded classrooms and half-day sessions are a tragic waste of our greatest national resource - the minds of our children."
author = "Walt Disney"

[[quotes]]
quote = "When you're curious, you find lots of interesting things to do."
author = "Walt Disney"

[[quotes]]
quote = "Somehow I can’t believe that there are any heights that can’t be scaled by a man who knows the secrets of making dreams come true. This special secret, it seems to me, can be summarized in four C s. They are curiosity, confidence, courage, and constancy."
author = "Walt Disney"

[[quotes]]
quote = "Leadership means that a group, large or small, is willing to entrust authority to a person who has shown judgment, wisdom, personal appeal, and proven competence."
author = "Walt Disney"
