[[quotes]]
quote = "If you tell the truth, you don't have to remember anything"
author = "Mark Twain"

[[quotes]]
quote = "The secret of getting ahead is getting started"
author = "Mark Twain"

[[quotes]]
quote = "It's not the size of the dog in the fight, it's the size of the fight in the dog"
author = "Mark Twain"

[[quotes]]
quote = "The two most important days in your life are the day you are born and the day you find out why"
author = "Mark Twain"

[[quotes]]
quote = "If you don't read the newspaper, you're uniformed. If you read the newspaper, you're mis-informed"
author = "Mark Twain"

[[quotes]]
quote = "Kindness is the language which the deaf can hear and the blind can see"
author = "Mark Twain"

[[quotes]]
quote = "You can't depend on your eyes when your imagination is out of focus"
author = "Mark Twain"

[[quotes]]
quote = "Courage is resistance to fear, master of fear, not absence of fear"
author = "Mark Twain"

[[quotes]]
quote = "It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt"
author = "Mark Twain"

[[quotes]]
quote = "Age is an issue of mind over matter. If you don't mind, it doesn't matter"
author = "Mark Twain"

[[quotes]]
quote = "All you need in this life is ignorance and confidence, and then success is sure"
author = "Mark Twain"
