[[quotes]]
quote = "Do the right thing. It will gratify some people and astonish the rest"
author = "Mark Twain"

[[quotes]]
quote = "A person who won't read has no advantage over one who can't read"
author = "Mark Twain"

[[quotes]]
quote = "The best way to cheer yourself up is to try to cheer somebody else up"
author = "Mark Twain"

[[quotes]]
quote = "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not"
author = "Mark Twain"

[[quotes]]
quote = "Humor is mankind's greatest blessing"
author = "Mark Twain"

[[quotes]]
quote = "When you fish for love, bait with your heart, not your brain"
author = "Mark Twain"

[[quotes]]
quote = "Wrinkles should merely indicate where smiles have been"
author = "Mark Twain"

[[quotes]]
quote = "When in doubt, tell the truth"
author = "Mark Twain"

[[quotes]]
quote = "He understood well enough how a man with a choice between pride and responsibility will almost always choose pride—if responsibility robs him of his manhood."
author = "Stephen King"

[[quotes]]
quote = "We do not admire the man of timid peace. We admire the man who embodies victorious effort; the man who never wrongs his neighbor, who is prompt to help a friend, but who has those virile qualities necessary to win in the stern strife of actual life."
author = "Theodore Roosevelt"

[[quotes]]
quote = "It is not what he has, or even what he does which expresses the worth of a man, but what he is."
author = "Henri-Frédéric Amiel"
