[[quotes]]
quote = "The way of a superior man is three-fold: virtuous, he is free from anxieties; wise, he is free from perplexities; bold, he is free from fear."
author = "Confucius"

[[quotes]]
quote = "A man should be able to hear, and to bear, the worst that could be said of him."
author = "Saul Bellow"

[[quotes]]
quote = "Nobody can give you freedom. Nobody can give you equality or justice or anything. If you’re a man, you take it"
author = "Malcolm X"

[[quotes]]
quote = "To be a man requires that you accept everything life has to give you, beginning with your name"
author = "Burl Ives"

[[quotes]]
quote = "Gardens are not made by singing 'Oh, how beautiful,' and sitting in the shade."
author = "Rudyard Kipling"

[[quotes]]
quote = "Man needs his difficulties because they are necessary to enjoy success."
author = "A. P. J. Abdul Kalam"

[[quotes]]
quote = "Fortune always favors the brave, and never helps a man who does not help himself."
author = "P.T. Barnum"

[[quotes]]
quote = "A hero is no braver than an ordinary man, but he is brave five minutes longer."
author = "Ralph Waldo Emerson"

[[quotes]]
quote = "I'd rather regret the things I've done than regret the things I haven't done."
author = "Lucille Ball"

[[quotes]]
quote = "We cannot direct the wind, but we can adjust the sails."
author = "Dolly Parton"

[[quotes]]
quote = "My hope still is to leave the world a bit better than when I got here."
author = "Jim Henson"
