[[quotes]]
quote = "When I started counting my blessings, my whole life turned around."
author = "Willie Nelson"

[[quotes]]
quote = "We are what we believe we are."
author = "C.S. Lewis"

[[quotes]]
quote = "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen."
author = "Winston Churchill"

[[quotes]]
quote = "A gem cannot be polished without friction, nor a man perfected without trials."
author = "Lucius Annaeus Seneca"

[[quotes]]
quote = "Success is not final, failure is not fatal: it is the courage to continue that counts."
author = "Winston Churchill"

[[quotes]]
quote = "There is nothing so stable as change."
author = "Bob Dylan"

[[quotes]]
quote = "You can't play life like an untuned instrument and then ask why the music is unpleasent."
author = "Shaan Ahmed"

[[quotes]]
quote = "Reality is wrong. Dreams are for real."
author = "Tupac Shakur"

[[quotes]]
quote = "Just know that I was once considered just a dreamer... Then I paid my dues and turned so many doubters to believers..."
author = "Big K.R.I.T."

[[quotes]]
quote = "Don't let nobody tell you that you can't do it. Love what you do until you don't love it anymore. Nothing's impossible."
author = "Fetty Wap"

[[quotes]]
quote = "If you don't build your dream someone will hire you to help build theirs."
author = "Tony A. Gaskins Jr."
