[[quotes]]
quote = "I can accept failure, everyone fails at something. But I can’t accept not trying."
author = "Michael Jordan"

[[quotes]]
quote = "Only those who will risk going too far can possibly find out how far it is possible to go."
author = "TS Eliot"

[[quotes]]
quote = "Believe in your dreams and dream big. And then after you’ve done that, dream bigger."
author = "Howard Schultz, CEO Starbucks"

[[quotes]]
quote = "If your actions inspire others to dream more, learn more, do more and become more, you are a leader."
author = "John Quincy Adams"

[[quotes]]
quote = "Success is not built on success. It’s built on failure. It’s built on frustration. Sometimes its built on catastrophe."
author = "Sumner Redstone"

[[quotes]]
quote = "Skills are cheap. Passion is priceless."
author = "Gary Vaynerchuk"

[[quotes]]
quote = "I think the thing to do is enjoy the ride while you’re on it."
author = "Johnny Depp"

[[quotes]]
quote = "Sometimes you need to push people into the deep for some people will never learn to swim if they've never been taught how it feels to drown"
author = "Shaan Ahmed"

[[quotes]]
quote = "No one should have the power to shatter your dreams unless you give it to them."
author = "Unknown"

[[quotes]]
quote = "A creative man is motivated by the desire to achieve, not by the desire to beat others."
author = "Ayn Rand"

[[quotes]]
quote = "Pain is temporary. Quitting lasts forever."
author = "Lance Armstrong"
