[[quotes]]
quote = "Understanding is the first step to acceptance, and only with acceptance can there be recovery."
author = "J.K. Rowling"

[[quotes]]
quote = "Mistakes are the portals of discovery."
author = "James Joyce"

[[quotes]]
quote = "We ought to walk through the rooms of our lives not looking for flaws, but looking for potential."
author = "Ellen Goodman"

[[quotes]]
quote = " If you are not willing to risk the usual you will have to settle for the ordinary. "
author = "Jim Rohn"

[[quotes]]
quote = "Opportunities don’t happen, you create them."
author = "Chris Grosser"

[[quotes]]
quote = " I have not failed. I’ve just found 10,000 ways that won’t work."
author = "Thomas A. Edison"

[[quotes]]
quote = "The distance between insanity and genius is measured only by success. "
author = "Bruce Feirstein"

[[quotes]]
quote = "When you stop chasing the wrong things you give the right things a chance to catch you. "
author = "Lolly Daskal"

[[quotes]]
quote = "Don’t be afraid to give up the good to go for the great."
author = "John D. Rockefeller"

[[quotes]]
quote = "In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it. "
author = "Jane Smiley"

[[quotes]]
quote = "People rarely succeed unless they have fun in what they are doing. "
author = "Dale Carnegie"
