[[quotes]]
quote = "Mistakes are always forgivable, if one has the courage to admit them"
author = "Bruce Lee"

[[quotes]]
quote = "If you spend too much time thinking about a thing, you'll never get it done"
author = "Bruce Lee"

[[quotes]]
quote = "A wise man can learn more from a foolish question than a fool can learn from a wise answer"
author = "Bruce Lee"

[[quotes]]
quote = "Design is not just what it looks like and feels like. Design is how it works"
author = "Steve Jobs"

[[quotes]]
quote = "Sometimes when you innovate, you make mistakes. It is best to admit them quickly, and get on with improving your other innovations"
author = "Steve Jobs"

[[quotes]]
quote = "Innovation distinguishes between a leader and a follower"
author = "Steve Jobs"

[[quotes]]
quote = "Don’t give up just because things get hard. Give up if you feel in your gut that moving on is the right choice for you."
author = "Lori Deschene"

[[quotes]]
quote = "Life isn’t always fair. Some people are born into better environments. Some people have better genetics. Some are in the right place at the right time. If you’re trying to change your life, all of this is irrelevant. All that matters is that you accept where you are, figure out where you want to be, and then do what you can, today and every day, to hold your head high and keep moving forward."
author = "Lori Deschene"

[[quotes]]
quote = "I survived because the fire inside me burned brighter than the fire around me."
author = "Joshua Graham"

[[quotes]]
quote = "Don’t let the fear of the time it will take to accomplish something stand in the way of your doing it."
author = "Earl Nightingale"

[[quotes]]
quote = "The strongest people aren’t always the people who win, but the people who don’t give up when they lose."
author = "Ashley Hodgeson"
