[[quotes]]
quote = "There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul. "
author = "Ella Wheeler Wilcox"

[[quotes]]
quote = "Our greatest fear should not be of failure but of succeeding at things in life that don’t really matter. "
author = "Francis Chan"

[[quotes]]
quote = "You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction. "
author = "George Lorimer"

[[quotes]]
quote = "To be successful you must accept all challenges that come your way. You can’t just accept the ones you like."
author = "Mike Gafka"

[[quotes]]
quote = "A ship in port is safe, but that's not what ships are built for."
author = "Grace Hopper"

[[quotes]]
quote = " It is often easier to ask for forgiveness than to ask for permission."
author = "Grace Hopper"

[[quotes]]
quote = "You don't manage people; you manage things. You lead people."
author = "Grace Hopper"

[[quotes]]
quote = "The two most important days in your life are the day you are born and the day you find out why."
author = "Mark Twain"

[[quotes]]
quote = "No matter how difficult and painful it may be, nothing sounds as good to the soul as the truth."
author = "Martha Beck"

[[quotes]]
quote = "Be first and be lonely."
author = "Ginni Rometty"

[[quotes]]
quote = "Step out of the history that is holding you back. Step into the new story you are willing to create."
author = "Oprah Winfrey"
