[[quotes]]
quote = "What you do makes a difference, and you have to decide what kind of difference you want to make."
author = "Jane Goodall"

[[quotes]]
quote = "A good compromise is one where everybody makes a contribution."
author = "Angela Merkel"

[[quotes]]
quote = "I choose to make the rest of my life the best of my life."
author = "Louise Hay"

[[quotes]]
quote = "In order to be irreplaceable one must always be different."
author = "Coco Chanel"

[[quotes]]
quote = "It’s one of the greatest gifts you can give yourself, to forgive. Forgive everybody."
author = "Maya Angelou"

[[quotes]]
quote = "If you’re not making some notable mistakes along the way, you’re certainly not taking enough business and career chances."
author = "Sallie Krawcheck"

[[quotes]]
quote = "Normal is not something to aspire to, it’s something to get away from."
author = "Jodie Foster"

[[quotes]]
quote = "Oh captain, my captain."
author = "Todd Anderson"

[[quotes]]
quote = "No matter what anybody tells you, words and ideas can change the world."
author = "John Keating"

[[quotes]]
quote = "Go ahead. Look out the window. Isn't it a beautiful day?"
author = "Anonymous"

[[quotes]]
quote = "People are crazy and times are strange/ I'm locked in tight, I'm out of range/ I used to care, but things have changed."
author = "Bob Dylan"
