[[quotes]]
quote = "Discipline is the bridge between goals and accomplishment."
author = "Jim Rohn"

[[quotes]]
quote = "It's a slow process, but quitting won't speed it up."
author = "Anonymous"

[[quotes]]
quote = "A river cuts through a rock not because of its power but its persistence."
author = "Anonymous"

[[quotes]]
quote = "The man on top of the mountain didn't fall there."
author = "Vince Lombardi"

[[quotes]]
quote = "I can and I will. Watch me."
author = "Anonymous"

[[quotes]]
quote = "Doubt kills more dreams than failure ever will."
author = "Karim Seddiki"

[[quotes]]
quote = "Be so good they can't ignore you."
author = "Steve Martin"

[[quotes]]
quote = "The expert in anything was once a beginner."
author = "Anonymous"

[[quotes]]
quote = "Wake up. Kick ass. Repeat."
author = "Anonymous"

[[quotes]]
quote = "Failure is a bruise, not a tattoo."
author = "Jon Sinclair"

[[quotes]]
quote = "Worrying is stupid. It's like walking around with an umbrella waiting for it to rain."
author = "Wiz Khalifa"
