[[quotes]]
quote = "A smooth sea never made a skilled sailor."
author = "Franklin D. Roosevelt"

[[quotes]]
quote = "Go the extra mile -- it's never crowded."
author = "Anonymous"

[[quotes]]
quote = "Look in the mirror... That's your competition."
author = "Anonymous"

[[quotes]]
quote = "I won't be a rock star. I will be a legend."
author = "Freddie Mercury"

[[quotes]]
quote = "Like the United Nations, there is something inspirational about New York as a great melting pot of different cultures and traditions. And if this is the city that never sleeps, the United Nations works tirelessly, around the clock around the world."
author = "Ban Ki-moon"

[[quotes]]
quote = "Once you have a lot of success, you become a target in many ways."
author = "Jennifer Lopez"

[[quotes]]
quote = "You are not here merely to make a living. You are here in order to enable the world to live more amply, with greater vision, with a finer spirit of hope and achievement. You are here to enrich the world, and you impoverish yourself if you forget the errand."
author = "Woodrow Wilson"

[[quotes]]
quote = "Every success in limiting armaments is a sign that the will to achieve mutual understanding exists, and every such success thus supports the fight for international law and order."
author = "Ludwig Quidde"

[[quotes]]
quote = "Learning is the beginning of wealth. Learning is the beginning of health. Learning is the beginning of spirituality. Searching and learning is where the miracle process all begins."
author = "Jim Rohn"

[[quotes]]
quote = "Keep in mind that neither success nor failure is ever final."
author = "Roger Babson"

[[quotes]]
quote = "I'm used to adversity and working really well in difficult situations. It was hard for me to accept the success."
author = "Paula Cole"
