[[quotes]]
quote = "A constant struggle, a ceaseless battle to bring success from inhospitable surroundings, is the price of all great achievements."
author = "Orison Swett Marden"

[[quotes]]
quote = "The real end winner of NAFTA is going to be Mexico because we have the human capital. We have that resource that is vital to the success of the U.S. economy."
author = "Vicente Fox"

[[quotes]]
quote = "Success is often the result of taking a misstep in the right direction."
author = "Al Bernstein"

[[quotes]]
quote = "A lot of people don't have near the amount of success as I've been blessed to have, and it's all about working hard and hoping that continues."
author = "Luke Bryan"

[[quotes]]
quote = "Success is the most important to many, to me it's just a bonus."
author = "Lucas Grabeel"

[[quotes]]
quote = "I think that success is having fun."
author = "Bruno Mars"

[[quotes]]
quote = "I believe in pink. I believe that laughing is the best calorie burner. I believe in kissing, kissing a lot. I believe in being strong when everything seems to be going wrong. I believe that happy girls are the prettiest girls. I believe that tomorrow is another day and I believe in miracles."
author = "Audrey Hepburn"

[[quotes]]
quote = "It is no use saying, 'We are doing our best.' You have got to succeed in doing what is necessary."
author = "Winston Churchill"

[[quotes]]
quote = "Change your thoughts and you change your world."
author = "Norman Vincent Peale"

[[quotes]]
quote = "I'm a gay disabled man who has become very successful. I don't get up in the morning and think I'm inspirational; I just get up thinking that I love horses."
author = "Lee Pearson"

[[quotes]]
quote = "Sound character provides the power with which a person may ride the emergencies of life instead of being overwhelmed by them. Failure is... the highway to success."
author = "Og Mandino"
