[[quotes]]
quote = "To know oneself, one should assert oneself."
author = "Albert Camus"

[[quotes]]
quote = "As kids we're not taught how to deal with success; we're taught how to deal with failure. If at first you don't succeed, try, try again. If at first you succeed, then what?"
author = "Charlie Sheen"

[[quotes]]
quote = "Everything you need for better future and success has already been written. And guess what? All you have to do is go to the library."
author = "Henri Frederic Amiel"

[[quotes]]
quote = "You can't cross the sea merely by standing and staring at the water."
author = "Rabindranath Tagore"

[[quotes]]
quote = "I never assumed I would have that commercial success, so it was a total surprise. And honestly, I never assumed that it would ever happen again."
author = "Tracy Chapman"

[[quotes]]
quote = "You cannot allow your desire to be a winner to be diminished by achieving success before and I believe there is room for improvement in every sportsman."
author = "Lionel Messi"

[[quotes]]
quote = "Failure is only postponed success as long as courage 'coaches' ambition. The habit of persistence is the habit of victory."
author = "Herbert Kaufman"

[[quotes]]
quote = "I think anyone who has a passion for what they love to do, and who pursue it, is inspirational for me."
author = "Colin Morgan"

[[quotes]]
quote = "Every moment and every event of every man's life on earth plants something in his soul."
author = "Thomas Merton"

[[quotes]]
quote = "To enjoy enduring success we should travel a little in advance of the world."
author = "John McDonald"

[[quotes]]
quote = "Success? You can't get a big head about it. When people stare at me, they could be whispering to their friend, 'That guy sucks! Have you seen him before? He's horrible.'"
author = "David Spade"
