[[quotes]]
quote = "I am so fresh in soul and spirit that life gushes and bubbles around me in a thousand springs."
author = "Robert Schumann"

[[quotes]]
quote = "Enjoy failure and learn from it. You can never learn from success."
author = "James Dyson"

[[quotes]]
quote = "I believe there are three keys to success. For me it is keeping my priorities in order: It's my faith and my family, and then the business."
author = "Kathy Ireland"

[[quotes]]
quote = "In motivating people, you've got to engage their minds and their hearts. I motivate people, I hope, by example - and perhaps by excitement, by having productive ideas to make others feel involved."
author = "Rupert Murdoch"

[[quotes]]
quote = "Wal-Mart's success strategies and tactics are easy to understand yet hard to duplicate."
author = "Michael Bergdahl"

[[quotes]]
quote = "Create each day anew."
author = "Morihei Ueshiba"

[[quotes]]
quote = "You can be discouraged by failure, or you can learn from it. So go ahead and make mistakes, make all you can. Because, remember that's where you'll find success - on the far side of failure."
author = "Thomas J. Watson"

[[quotes]]
quote = "A lot of America is kind of done. People have been making films about it for 100 years. Everything to me feels used up. But Jo-Burg feels unbelievably inspirational to me."
author = "Neill Blomkamp"

[[quotes]]
quote = "We make the world we live in and shape our own environment."
author = "Orison Swett Marden"

[[quotes]]
quote = "Money and success don't change people; they merely amplify what is already there."
author = "Will Smith"

[[quotes]]
quote = "To do a common thing uncommonly well brings success."
author = "Henry J. Heinz"
