[[quotes]]
quote = "Your heaviest artillery will be your will to live. Keep that big gun going."
author = "Norman Cousins"

[[quotes]]
quote = "It's not just the 'Grammys' that I've pulled out of. I also pulled out of the English awards as well. The reason that I wanted to pull out was because I believe very much that the music industry as a whole is mainly concerned with material success."
author = "Alanis Morissette"

[[quotes]]
quote = "Without an open-minded mind, you can never be a great success."
author = "Martha Stewart"

[[quotes]]
quote = "Today is the only day. Yesterday is gone."
author = "John Wooden"

[[quotes]]
quote = "Happiness resides not in possessions, and not in gold, happiness dwells in the soul."
author = "Democritus"

[[quotes]]
quote = "Happiness is not something you postpone for the future; it is something you design for the present."
author = "Jim Rohn"

[[quotes]]
quote = "Love the moment and the energy of that moment will spread beyond all boundaries."
author = "Corita Kent"

[[quotes]]
quote = "However difficult life may seem, there is always something you can do and succeed at."
author = "Stephen Hawking"

[[quotes]]
quote = "Success breeds success, and failure leads to a sort of fallow period."
author = "Felicity Kendal"

[[quotes]]
quote = "One fails forward toward success."
author = "Charles Kettering"

[[quotes]]
quote = "Can you imagine what I would do if I could do all I can?"
author = "Jeff Rich"
