[[quotes]]
quote = "In the first six to twelve months of a war with the United States and Great Britain I will run wild and win victory upon victory. But then, if the war continues after that, I have no expectation of success."
author = "Isoroku Yamamoto"

[[quotes]]
quote = "Try to be like the turtle - at ease in your own shell."
author = "Bill Copeland"

[[quotes]]
quote = "Every heart that has beat strongly and cheerfully has left a hopeful impulse behind it in the world, and bettered the tradition of mankind."
author = "Robert Louis Stevenson"

[[quotes]]
quote = "It's always too early to quit."
author = "Norman Vincent Peale"

[[quotes]]
quote = "Creativity is the key to success in the future, and primary education is where teachers can bring creativity in children at that level."
author = "A. P. J. Abdul Kalam"

[[quotes]]
quote = "Better to be called something positive and inspirational than something negative."
author = "Donnie Yen"

[[quotes]]
quote = "It is such a luxury to open a new book that's highly recommended by friends - either an inspirational yet humorously self-deprecating memoir, or a page-turning piece of fiction."
author = "Kelli O'Hara"

[[quotes]]
quote = "The future of America is not an entitlement. We have been given a treasure chest of gifts and opportunities, but some people are being left behind, and success is not sustainable unless it is shared."
author = "Howard Schultz"

[[quotes]]
quote = "I know why I am here and my only real focused goal is to live each day to the fullest and to try and honor God and be an encouragement to others. What the future holds is firmly in God's hands, and I am very happy about that!"
author = "Ken Hensley"

[[quotes]]
quote = "My greatest success story has been my family."
author = "Alex Spanos"

[[quotes]]
quote = "I'm a motivational speaker."
author = "Young Jeezy"
