[[quotes]]
quote = "The truth is that relative income is not directly related to happiness. Nonpartisan social-survey data clearly show that the big driver of happiness is earned success: a person's belief that he has created value in his life or the life of others."
author = "Arthur C. Brooks"

[[quotes]]
quote = "Success has always been easy to measure. It is the distance between one's origins and one's final achievement."
author = "Michael Korda"

[[quotes]]
quote = "Success is the only motivational factor that a boy with character needs."
author = "Woody Hayes"

[[quotes]]
quote = "If there were no night, we would not appreciate the day, nor could we see the stars and the vastness of the heavens. We must partake of the bitter with the sweet. There is a divine purpose in the adversities we encounter every day. They prepare, they purge, they purify, and thus they bless."
author = "James E. Faust"

[[quotes]]
quote = "Just what future the Designer of the universe has provided for the souls of men I do not know, I cannot prove. But I find that the whole order of Nature confirms my confidence that, if it is not like our noblest hopes and dreams, it will transcend them."
author = "Henry Norris Russell"

[[quotes]]
quote = "I know of no single formula for success. But over the years I have observed that some attributes of leadership are universal and are often about finding ways of encouraging people to combine their efforts, their talents, their insights, their enthusiasm and their inspiration to work together."
author = "Queen Elizabeth II"

[[quotes]]
quote = "I am very optimistic, and I wish that God almighty grants me success to get a qualifying time. Only then can I go to the Olympics. If this happens I will be the first Palestinian athlete to gain a qualifying time. This will be a big achievement."
author = "Nader al-Masri"

[[quotes]]
quote = "There is nothing deep down inside us except what we have put there ourselves."
author = "Richard Rorty"

[[quotes]]
quote = "From success you get a lot of things, but not that great inside thing that love brings you."
author = "Samuel Goldwyn"

[[quotes]]
quote = "I realise that I do not change the course of history. I am an actor, I do a movie, that's the end of it. You have to realise we are just clowns for hire. After I had success it was great, at first, not to worry about money. It was on my mind when I was growing up."
author = "Leonardo DiCaprio"

[[quotes]]
quote = "There are a lot of things that go into creating success. I don't like to do just the things I like to do. I like to do things that cause the company to succeed. I don't spend a lot of time doing my favorite activities."
author = "Michael Dell"
