[[quotes]]
quote = "At any given moment, you have the power to say: This is not how the story is going to end."
author = "Christine Mason Miller"

[[quotes]]
quote = "Life’s blows cannot break a person whose spirit is warmed by the fire of enthusiasm."
author = "Norman Vincent Peale"

[[quotes]]
quote = "When you believe something can be done, really believe, your mind will find ways to do it."
author = "Dr. David Schwartz"

[[quotes]]
quote = "Your belief determines your action and your action determines your results, but first you have to believe."
author = "Mark Victor Hansen"

[[quotes]]
quote = "A man’s errors are his portals of discovery."
author = "James Joyce"

[[quotes]]
quote = "Wisdom is knowing what to do next, skill is knowing how to do it, and virtue is doing it."
author = "David Starr Jordan"

[[quotes]]
quote = "Never allow a person to tell you no who doesn’t have the power to say yes."
author = "Eleanor Roosevelt"

[[quotes]]
quote = "Turn your face toward the sun and the shadows will fall behind you."
author = "Maori Proverb"

[[quotes]]
quote = "Doing your best means never stop trying."
author = "Unknown"

[[quotes]]
quote = "A hard fall means a high bounce…if you’re made of the right material."
author = "Unknown"

[[quotes]]
quote = "People who urge you to be realistic generally want you to accept their version of reality."
author = "Unknown"
