[[quotes]]
quote = "Arriving at one goal is the starting point to another."
author = "John Dewey"

[[quotes]]
quote = "There are thousands of inspirational stories waiting to be told about young women who yearn for a great education. They are stories of struggle and stories of success, and they will inspire others to take action and work to change lives."
author = "Soledad O'Brien"

[[quotes]]
quote = "I take great pride in all the tremendous success we've enjoyed at CBS. And the good news is that I feel even more enthusiastic about what my terrific team and I will accomplish going forward."
author = "Leslie Moonves"

[[quotes]]
quote = "The limits of the possible can only be defined by going beyond them into the impossible."
author = "Arthur C. Clarke"

[[quotes]]
quote = "I believe there's an inner power that makes winners or losers. And the winners are the ones who really listen to the truth of their hearts."
author = "Sylvester Stallone"

[[quotes]]
quote = "Silent pictures show us how we lived and what our attitudes were. And as an art form, they can be wonderfully entertaining and often inspirational."
author = "Kevin Brownlow"

[[quotes]]
quote = "What you do today can improve all your tomorrows."
author = "Ralph Marston"

[[quotes]]
quote = "Do you wish to rise? Begin by descending. You plan a tower that will pierce the clouds? Lay first the foundation of humility."
author = "Saint Augustine"

[[quotes]]
quote = "Think with your whole body."
author = "Taisen Deshimaru"

[[quotes]]
quote = "People always accuse me of being motivational in a way, like it was a bad thing, but that's just how I was raised. My mom raised me in a positive environment, with lots of love in my heart, and that reflects in my music."
author = "Lenny Kravitz"

[[quotes]]
quote = "Success is the child of audacity."
author = "Benjamin Disraeli"
