[[quotes]]
quote = "I try not to put anything political on the forefront of what I'm trying to do creatively. At the same time, I do think it's wonderful when I hear people say that it's inspirational that I'm an Indian woman on camera. My life is very diverse, and my friends are a diverse group of people."
author = "Mindy Kaling"

[[quotes]]
quote = "Actually, I'm an overnight success, but it took twenty years."
author = "Monty Hall"

[[quotes]]
quote = "Prayer is man's greatest power!"
author = "W. Clement Stone"

[[quotes]]
quote = "If you think you can do it, you can."
author = "John Burroughs"

[[quotes]]
quote = "Frustration, although quite painful at times, is a very positive and essential part of success."
author = "Bo Bennett"

[[quotes]]
quote = "Success or failure depends more upon attitude than upon capacity successful men act as though they have accomplished or are enjoying something. Soon it becomes a reality. Act, look, feel successful, conduct yourself accordingly, and you will be amazed at the positive results."
author = "William James"

[[quotes]]
quote = "We're constantly striving for success, fame and comfort when all we really need to be happy is someone or some thing to be enthusiastic about."
author = "H. Jackson Brown, Jr."

[[quotes]]
quote = "Feeling anxious or depressed sometimes is part of what it means to be a person, and it might even be essential to success."
author = "K. Flay"

[[quotes]]
quote = "Success has always been a great liar."
author = "Friedrich Nietzsche"

[[quotes]]
quote = "God always strives together with those who strive."
author = "Aeschylus"

[[quotes]]
quote = "Hard work and dedication is important to success, and I have those qualities."
author = "Nargis Fakhri"
