[[quotes]]
quote = "One of the key elements of human behavior is, humans have a greater fear of loss than enjoyment of success. All the academic studies will show you that the fear of loss of capital is far greater than the enjoyment of gains."
author = "Laurence D. Fink"

[[quotes]]
quote = "Do something wonderful, people may imitate it."
author = "Albert Schweitzer"

[[quotes]]
quote = "Any fact facing us is not as important as our attitude toward it, for that determines our success or failure. The way you think about a fact may defeat you before you ever do anything about it. You are overcome by the fact because you think you are."
author = "Norman Vincent Peale"

[[quotes]]
quote = "There's enormous progressive activism and, more often than not, success at the grassroots level - everything from living wage campaigns to efforts to finance our elections are having terrific success."
author = "Jim Hightower"

[[quotes]]
quote = "If you look at the common denominator of all the comics who have had big success, it's being true to their nature... that's what takes a long time to learn."
author = "Ron White"

[[quotes]]
quote = "There is nothing stronger in the world than gentleness."
author = "Han Suyin"

[[quotes]]
quote = "Let each man exercise the art he knows."
author = "Aristophanes"

[[quotes]]
quote = "Prospering just doesn't have to do with money."
author = "Joel Osteen"

[[quotes]]
quote = "Success is dangerous. One begins to copy oneself, and to copy oneself is more dangerous than to copy others. It leads to sterility."
author = "Pablo Picasso"

[[quotes]]
quote = "Love is a fruit in season at all times, and within reach of every hand."
author = "Mother Teresa"

[[quotes]]
quote = "There is no scientific answer for success. You can't define it. You've simply got to live it and do it."
author = "Anita Roddick"
