[[quotes]]
quote = "As people are walking all the time, in the same spot, a path appears."
author = "John Locke"

[[quotes]]
quote = "I hope that at the end of the seven years, people will say that I have been of some inspirational value to them at home in terms of inclusiveness and abroad, I look forward to representing Ireland."
author = "Michael D. Higgins"

[[quotes]]
quote = "Success is nothing more than a few simple disciplines, practiced every day."
author = "Jim Rohn"

[[quotes]]
quote = "I firmly believe that unless one has tasted the bitter pill of failure, one cannot aspire enough for success."
author = "A. P. J. Abdul Kalam"

[[quotes]]
quote = "Success is more dangerous than failure, the ripples break over a wider coastline."
author = "Graham Greene"

[[quotes]]
quote = "To me, the Seventies were very inspirational and very influential... With my whole persona as Snoop Dogg, as a person, as a rapper. I just love the Seventies style, the way all the players dressed nice, you know, kept their hair looking good, drove sharp cars and they talked real slick."
author = "Snoop Dogg"

[[quotes]]
quote = "I think all of us certainly believed the statistics which said that probably 88% chance of mission success and maybe 96% chance of survival. And we were willing to take those odds."
author = "Alan Shepard"

[[quotes]]
quote = "What they have done in Japan, which I find so inspirational, is they've brought the toilet out from behind the locked door. They've made it conversational. People go out and upgrade their toilet. They talk about it. They've sanitized it."
author = "Rose George"

[[quotes]]
quote = "If the doors of perception were cleansed everything would appear to man as it is, infinite."
author = "William Blake"

[[quotes]]
quote = "Real success is not on the stage, but off the stage as a human being, and how you get along with your fellow man."
author = "Sammy Davis, Jr."

[[quotes]]
quote = "Everyone has inside of him a piece of good news. The good news is that you don't know how great you can be! How much you can love! What you can accomplish! And what your potential is!"
author = "Anne Frank"
