[[quotes]]
quote = "Of all the things people have taught me regarding life lessons or anything that would benefit me, I don't think anything helped me learn more about life than football. You go through so many different things: adversity, how to handle adversity, how to handle success, how to lead, how to be a teammate, how to communicate."
author = "Josh McDaniels"

[[quotes]]
quote = "I think, aesthetically, car design is so interesting - the dashboards, the steering wheels, and the beauty of the mechanics. I don't know how any of it works, I don't want to know, but it's inspirational."
author = "Paloma Picasso"

[[quotes]]
quote = "The first question which the priest and the Levite asked was: 'If I stop to help this man, what will happen to me?' But... the good Samaritan reversed the question: 'If I do not stop to help this man, what will happen to him?'"
author = "Martin Luther King, Jr."

[[quotes]]
quote = "Nothing is as seductive as the assurance of success."
author = "Gertrude Himmelfarb"

[[quotes]]
quote = "A great social success is a pretty girl who plays her cards as carefully as if she were plain."
author = "F. Scott Fitzgerald"

[[quotes]]
quote = "The success of any stand-up act comes out of life experience."
author = "Howie Mandel"

[[quotes]]
quote = "For a gallant spirit there can never be defeat."
author = "Wallis Simpson"

[[quotes]]
quote = "When deeds speak, words are nothing."
author = "Pierre-Joseph Proudhon"

[[quotes]]
quote = "Success depends almost entirely on how effectively you learn to manage the game's two ultimate adversaries: the course and yourself."
author = "Jack Nicklaus"

[[quotes]]
quote = "At the end of the day, the one commonality that both Hindi cinema and Hollywood share is that they are full of talented and inspirational people. Outside of this, there are many differences, from the scheduling and rehearsal to promotion and directing techniques."
author = "Nargis Fakhri"

[[quotes]]
quote = "I pray God may preserve your health and life many years."
author = "Junipero Serra"
