[[quotes]]
quote = "Be brave enough to live life creatively. The creative place where no one else has ever been."
author = "Alan Alda"

[[quotes]]
quote = "An artist must never be a prisoner. Prisoner? An artist should never be a prisoner of himself, prisoner of style, prisoner of reputation, prisoner of success, etc."
author = "Henri Matisse"

[[quotes]]
quote = "People say we were an overnight success. It took us a year to be an overnight success."
author = "James Daly"

[[quotes]]
quote = "I have no time for those who say there is no way Scotland could go it alone. I know first-hand the contribution Scotland and Scots make to Britain's success - so for me there's no question about whether Scotland could be an independent nation."
author = "David Cameron"

[[quotes]]
quote = "While formal schooling is an important advantage, it is not a guarantee of success nor is its absence a fatal handicap."
author = "Ray Kroc"

[[quotes]]
quote = "The books that help you most are those which make you think that most. The hardest way of learning is that of easy reading; but a great book that comes from a great thinker is a ship of thought, deep freighted with truth and beauty."
author = "Pablo Neruda"

[[quotes]]
quote = "What drew me towards team sport were the camaraderie and friendship. The chance to celebrate victory and success with a group of other people is something I have enjoyed doing."
author = "Rahul Dravid"

[[quotes]]
quote = "God loves to help him who strives to help himself."
author = "Aeschylus"

[[quotes]]
quote = "Steroids do not guarantee you're going to have success. I think a lot of people think that they will, but they don't."
author = "Tony Gwynn"

[[quotes]]
quote = "One secret of success in life is for a man to be ready for his opportunity when it comes."
author = "Benjamin Disraeli"

[[quotes]]
quote = "Telecom is a dramatic success in India and our view is, respecting the political process, and respecting the fact that these are sovereign decisions, is that, approaching India as a friend."
author = "John W. Snow"
