[[quotes]]
quote = "Success is a journey, not a destination. The doing is often more important than the outcome."
author = "Arthur Ashe"

[[quotes]]
quote = "Obedience is the mother of success and is wedded to safety."
author = "Aeschylus"

[[quotes]]
quote = "I've always believed that one woman's success can only help another woman's success."
author = "Gloria Vanderbilt"

[[quotes]]
quote = "A somebody was once a nobody who wanted to and did."
author = "John Burroughs"

[[quotes]]
quote = "Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others."
author = "Jack Welch"

[[quotes]]
quote = "Success is a consequence and must not be a goal."
author = "Gustave Flaubert"

[[quotes]]
quote = "Even if you fall on your face, you're still moving forward."
author = "Victor Kiam"

[[quotes]]
quote = "Success is the progressive realization of a worthy goal or ideal."
author = "Earl Nightingale"

[[quotes]]
quote = "Your chances of success in any undertaking can always be measured by your belief in yourself."
author = "Robert Collier"

[[quotes]]
quote = "Always be yourself, express yourself, have faith in yourself, do not go out and look for a successful personality and duplicate it."
author = "Bruce Lee"

[[quotes]]
quote = "I started doing motivational tours. I've seen all kinds of people, from the CEOs to the lowest executive, opening up to their fears. We don't introspect as much as we should."
author = "Anupam Kher"
