[[quotes]]
quote = "Success is not a good teacher, failure makes you humble."
author = "Shah Rukh Khan"

[[quotes]]
quote = "Invincibility lies in the defence; the possibility of victory in the attack."
author = "Sun Tzu"

[[quotes]]
quote = "The superior man makes the difficulty to be overcome his first interest; success only comes later."
author = "Confucius"

[[quotes]]
quote = "What we think, we become."
author = "Buddha"

[[quotes]]
quote = "The fact that I can plant a seed and it becomes a flower, share a bit of knowledge and it becomes another's, smile at someone and receive a smile in return, are to me continual spiritual exercises."
author = "Leo Buscaglia"

[[quotes]]
quote = "If you find it in your heart to care for somebody else, you will have succeeded."
author = "Maya Angelou"

[[quotes]]
quote = "I believe success is preparation, because opportunity is going to knock on your door sooner or later but are you prepared to answer that?"
author = "Omar Epps"

[[quotes]]
quote = "Whosoever desires constant success must change his conduct with the times."
author = "Niccolo Machiavelli"

[[quotes]]
quote = "One day, I got so disgusted that I sat down and wrote a list called 'Justin's list of things to do before he kicks the bucket.' I wrote it for myself and shortened it to 'Justin's Bucket List.' It was there on the wall, not as a story idea but as a motivational tool for myself, which actually ended up working pretty well."
author = "Justin Zackham"

[[quotes]]
quote = "Wonder rather than doubt is the root of all knowledge."
author = "Abraham Joshua Heschel"

[[quotes]]
quote = "Who seeks shall find."
author = "Sophocles"
