[[quotes]]
quote = "Most people give up just when they're about to achieve success. They quit on the one yard line. They give up at the last minute of the game one foot from a winning touchdown."
author = "Ross Perot"

[[quotes]]
quote = "After a lifetime of working, raising families, and contributing to the success of this nation in countless other ways, senior citizens deserve to retire with dignity."
author = "Charlie Gonzalez"

[[quotes]]
quote = "Four things for success: work and pray, think and believe."
author = "Norman Vincent Peale"

[[quotes]]
quote = "I've had great success being a total idiot."
author = "Jerry Lewis"

[[quotes]]
quote = "Success - it's what you do with what you've got."
author = "Woody Hayes"

[[quotes]]
quote = "I don't know what keeps me going. Sometimes I wonder... I think it's just pure perseverance and wanting to succeed and having that burning desire to always have success."
author = "Tanya Tucker"

[[quotes]]
quote = "The authentic self is the soul made visible."
author = "Sarah Ban Breathnach"

[[quotes]]
quote = "Decide what you want, decide what you are willing to exchange for it. Establish your priorities and go to work."
author = "H. L. Hunt"

[[quotes]]
quote = "'Get along, go along' is not an inspirational philosophy, and only God knows how much moral cowardice it has covered up over the years. Serve your time, collect your chits, and cash 'em in for your home state? No, I'd say we could ask for more than that from our senators."
author = "Molly Ivins"

[[quotes]]
quote = "This CD became something of a personal journey for me. The tone of the whole CD is uplifting and inspirational. It's an upper. We have enough downers in the world."
author = "Roma Downey"

[[quotes]]
quote = "The world is full of magical things patiently waiting for our wits to grow sharper."
author = "Bertrand Russell"
