[[quotes]]
quote = "It takes 20 years to make an overnight success."
author = "Eddie Cantor"

[[quotes]]
quote = "I think you can have 10,000 explanations for failure, but no good explanation for success."
author = "Paulo Coelho"

[[quotes]]
quote = "From a small seed a mighty trunk may grow."
author = "Aeschylus"

[[quotes]]
quote = "By providing clear objectives for your team, and setting guardrails for how they get there, you will set them on the path to success."
author = "Chris Fussell"

[[quotes]]
quote = "Either I will find a way, or I will make one."
author = "Philip Sidney"

[[quotes]]
quote = "Tears of joy are like the summer rain drops pierced by sunbeams."
author = "Hosea Ballou"

[[quotes]]
quote = "Success is survival."
author = "Leonard Cohen"

[[quotes]]
quote = "I know that when I like music, when it touches my heart, that it will touch your heart, too. That, I think, is the secret to my success."
author = "Andre Rieu"

[[quotes]]
quote = "Deserve your dream."
author = "Octavio Paz"

[[quotes]]
quote = "Success breeds complacency. Complacency breeds failure. Only the paranoid survive."
author = "Andy Grove"

[[quotes]]
quote = "Commercial success still hasn't come to an artist that isn't signed to a record label. There are very few artists that can succeed without the help of a record label. The role of the record label is still required, it's still necessary."
author = "Edgar Bronfman, Jr."
