[[quotes]]
quote = "If we are facing in the right direction, all we have to do is keep on walking."
author = "Proverb"

[[quotes]]
quote = "Life’s challenges are not supposed to paralyze you, they’re supposed to help you discover who you are."
author = "Bernice Johnson Reagon"

[[quotes]]
quote = "I cannot make my days longer so I strive to make them better."
author = "Henry David Thoreau"

[[quotes]]
quote = "We all have problems. The way we solve them is what makes us different."
author = "Unknown"

[[quotes]]
quote = "Whenever you fall, pick something up. "
author = "Oswald Avery"

[[quotes]]
quote = "Care and diligence bring luck."
author = "Proverb"

[[quotes]]
quote = "A bend in the road is not the end of the road…unless you fail to make the turn."
author = "Unknown"

[[quotes]]
quote = "Stop being afraid of what could go wrong, and start being excited about what could go right."
author = "Unknown"

[[quotes]]
quote = "What is not started today is never finished tomorrow."
author = "Johann Wolfgang von Goethe"

[[quotes]]
quote = "You can do what’s reasonable or you can decide what’s possible."
author = "Unknown"

[[quotes]]
quote = "If you lose today, win tomorrow. In this never-ending spirit of challenge is the heart of a victor."
author = "Daisaku Ikeda"
