[[quotes]]
quote = "Other people's success spurs me on to do well and gives me motivation."
author = "Nicholas Hoult"

[[quotes]]
quote = "A passionate belief in your business and personal objectives can make all the difference between success and failure. If you aren't proud of what you're doing, why should anybody else be?"
author = "Richard Branson"

[[quotes]]
quote = "Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist. Be curious."
author = "Stephen Hawking"

[[quotes]]
quote = "Anyone who has to fight, even with the most modern weapons, against an enemy in complete command of the air, fights like a savage against modern European troops, under the same handicaps and with the same chances of success."
author = "Erwin Rommel"

[[quotes]]
quote = "Success isn't about the end result, it's about what you learn along the way."
author = "Vera Wang"

[[quotes]]
quote = "I can't change the direction of the wind, but I can adjust my sails to always reach my destination."
author = "Jimmy Dean"

[[quotes]]
quote = "People are beginning to see that the first requisite to success in life is to be a good animal."
author = "Herbert Spencer"

[[quotes]]
quote = "Whatever obstacle comes your way, you gotta be prepared to jump over it! And I think that's what separates the legends from the regular artists. It's all in how you manage that success, and how you deal with the controversy when it actually comes."
author = "Akon"

[[quotes]]
quote = "I have gone from being a 21-year-old with wide eyes to a 24-year-old woman. With success comes a lot of responsibility and power."
author = "Vanessa Carlton"

[[quotes]]
quote = "There's more to life than success, and if you can try to be more well-rounded, you'll be able to enjoy your success more. It won't own you or control you."
author = "Ricky Williams"

[[quotes]]
quote = "The road to success is always under construction."
author = "Lily Tomlin"
