[[quotes]]
quote = "My success was due to good luck, hard work, and support and advice from friends and mentors. But most importantly, it depended on me to keep trying after I had failed."
author = "Mark Warner"

[[quotes]]
quote = "The manic pursuit of success cost me everything I could love: my wife, my three children, some friends I would have liked to grow old with."
author = "Sammy Davis, Jr."

[[quotes]]
quote = "Some people dream of success, while other people get up every morning and make it happen."
author = "Wayne Huizenga"

[[quotes]]
quote = "Just don't give up trying to do what you really want to do. Where there is love and inspiration, I don't think you can go wrong."
author = "Ella Fitzgerald"

[[quotes]]
quote = "No one succeeds without effort... Those who succeed owe their success to perseverance."
author = "Ramana Maharshi"

[[quotes]]
quote = "You always draw inspiration from your family or your parents if they've proven to be inspirational. My mother is someone who's always been inspirational to me."
author = "Dustin Clare"

[[quotes]]
quote = "I've always thought of acting as more of an exercise in empathy, which is not to be confused with sympathy. You're trying to get inside a certain emotional reality or motivational reality and try to figure out what that's about so you can represent it."
author = "Edward Norton"

[[quotes]]
quote = "Perseverance is failing 19 times and succeeding the 20th."
author = "Julie Andrews"

[[quotes]]
quote = "A desire to be in charge of our own lives, a need for control, is born in each of us. It is essential to our mental health, and our success, that we take control."
author = "Robert Foster Bennett"

[[quotes]]
quote = "I want to make sure I don't interfere with the success of that team next year. I don't see any way I could go to practice like most of 'em do, and not hurt the team. I'd go nuts if I tried doing that."
author = "Bear Bryant"

[[quotes]]
quote = "Success isn't a result of spontaneous combustion. You must set yourself on fire."
author = "Arnold H. Glasow"
