[[quotes]]
quote = "Victory has a thousand fathers, but defeat is an orphan."
author = "John F. Kennedy"

[[quotes]]
quote = "Positive thinking is the key to success in business, education, pro football, anything that you can mention. I go out there thinking that I'm going to complete every pass."
author = "Ron Jaworski"

[[quotes]]
quote = "Every soldier must know, before he goes into battle, how the little battle he is to fight fits into the larger picture, and how the success of his fighting will influence the battle as a whole."
author = "Bernard Law Montgomery"

[[quotes]]
quote = "No matter what people tell you, words and ideas can change the world."
author = "Robin Williams"

[[quotes]]
quote = "Before you can become a millionaire, you must learn to think like one. You must learn how to motivate yourself to counter fear with courage. Making critical decisions about your career, business, investments and other resources conjures up fear, fear that is part of the process of becoming a financial success."
author = "Thomas J. Stanley"

[[quotes]]
quote = "Feeling is the consciousness of the resulting conditions - of success, failure, equilibrium, compromise or balance, in this continuous rivalry of ideas."
author = "James Mark Baldwin"

[[quotes]]
quote = "Success listens only to applause. To all else it is deaf."
author = "Elias Canetti"

[[quotes]]
quote = "There's no success story. Everybody's got a ghetto story. You always want to make it bigger than what it is."
author = "Bernie Mac"

[[quotes]]
quote = "Tears are often the telescope by which men see far into heaven."
author = "Henry Ward Beecher"

[[quotes]]
quote = "I've always believed that success for anyone is all about drive, dedication, and desire, but for me, it's also been about confidence and faith."
author = "Stephen Curry"

[[quotes]]
quote = "I feel like I want to take care of everyone and I also feel this terrible guilt if I am unable to. And I have felt this way ever since all this success started."
author = "Jim Carrey"
