[[quotes]]
quote = "Success has nothing to do with what you gain in life or accomplish for yourself. It's what you do for others."
author = "Danny Thomas"

[[quotes]]
quote = "With self-discipline most anything is possible."
author = "Theodore Roosevelt"

[[quotes]]
quote = "It is in your moments of decision that your destiny is shaped."
author = "Tony Robbins"

[[quotes]]
quote = "'Star Wars' is fun, its exciting, its inspirational, and people respond to that. It's what they want."
author = "George Lucas"

[[quotes]]
quote = "I want to be an inspirational model. I want people to look at me and say, 'Wow, she looks healthy.'"
author = "Ireland Baldwin"

[[quotes]]
quote = "It always seems impossible until it's done."
author = "Nelson Mandela"

[[quotes]]
quote = "The talent of success is nothing more than doing what you can do well, and doing well whatever you do without thought of fame. If it comes at all it will come because it is deserved, not because it is sought after."
author = "Henry Wadsworth Longfellow"

[[quotes]]
quote = "Reach for the stars."
author = "Christa McAuliffe"

[[quotes]]
quote = "I saw a lot of people have success handed to them that then exploited it. They didn't protect it or cherish it."
author = "Aaron Paul"

[[quotes]]
quote = "Light tomorrow with today!"
author = "Elizabeth Barrett Browning"

[[quotes]]
quote = "Successful people make money. It's not that people who make money become successful, but that successful people attract money. They bring success to what they do."
author = "Wayne Dyer"
