[[quotes]]
quote = "Barack Obama likes to point to General Motors as the poster child for the job creation success of his economic policies. However, whatever your sentiments about the government's bailout of General Motors, for every job Barack Obama 'saved-or-created' in the U.S. there were two jobs off shore."
author = "Bob Beauprez"

[[quotes]]
quote = "I think true success is intrinsic... It's love. It's kindness. It's community."
author = "Tom Shadyac"

[[quotes]]
quote = "Treat failure as a lesson on how not to approach achieving a goal, and then use that learning to improve your chances of success when you try again. Failure is only the end if you decide to stop."
author = "Richard Branson"

[[quotes]]
quote = "Nurture your minds with great thoughts. To believe in the heroic makes heroes."
author = "Benjamin Disraeli"

[[quotes]]
quote = "Infuse your life with action. Don't wait for it to happen. Make it happen. Make your own future. Make your own hope. Make your own love. And whatever your beliefs, honor your creator, not by passively waiting for grace to come down from upon high, but by doing what you can to make grace happen... yourself, right now, right down here on Earth."
author = "Bradley Whitford"

[[quotes]]
quote = "No man succeeds without a good woman behind him. Wife or mother, if it is both, he is twice blessed indeed."
author = "Godfrey Winn"

[[quotes]]
quote = "The compensation of a very early success is a conviction that life is a romantic matter. In the best sense one stays young."
author = "F. Scott Fitzgerald"

[[quotes]]
quote = "My success was not based so much on any great intelligence but on great common sense."
author = "Helen Gurley Brown"

[[quotes]]
quote = "Success demands singleness of purpose."
author = "Vince Lombardi"

[[quotes]]
quote = "They talk about the failure of socialism but where is the success of capitalism in Africa, Asia and Latin America?"
author = "Fidel Castro"

[[quotes]]
quote = "Yesterday we obeyed kings and bent our necks before emperors. But today we kneel only to truth, follow only beauty, and obey only love."
author = "Khalil Gibran"
