[[quotes]]
quote = "At Princeton I gained a great deal of pleasure from success in my classes. knowing that I could accomplish those things, and I realized that my success was directly proportionate to the work I put in."
author = "Brooke Shields"

[[quotes]]
quote = "You stand with the least likely to succeed until success is succeeded by something more valuable: kinship. You stand with the belligerent, the surly and the badly behaved until bad behavior is recognized for the language it is: the vocabulary of the deeply wounded and of those whose burdens are more than they can bear."
author = "Greg Boyle"

[[quotes]]
quote = "So I feel like success is opportunity plus preparation, so work begets work, and as long as you're prepared it's going to continue to come your way."
author = "Anthony Mackie"

[[quotes]]
quote = "Success in golf depends less on strength of body than upon strength of mind and character."
author = "Arnold Palmer"

[[quotes]]
quote = "Success is the maximum utilization of the ability that you have."
author = "Zig Ziglar"

[[quotes]]
quote = "When you reach the end of your rope, tie a knot in it and hang on."
author = "Franklin D. Roosevelt"

[[quotes]]
quote = "The battle of life is, in most cases, fought uphill; and to win it without a struggle were perhaps to win it without honor. If there were no difficulties there would be no success; if there were nothing to struggle for, there would be nothing to be achieved."
author = "Samuel Smiles"

[[quotes]]
quote = "I don't know the key to success, but the key to failure is trying to please everybody."
author = "Bill Cosby"

[[quotes]]
quote = "I celebrate myself, and sing myself."
author = "Walt Whitman"

[[quotes]]
quote = "Let us dream of tomorrow where we can truly love from the soul, and know love as the ultimate truth at the heart of all creation."
author = "Michael Jackson"

[[quotes]]
quote = "Achievers have an enabling attitude, realism, and a conviction that they themselves were the laboratory of innovation. Their ability to change themselves is central to their success. They have learned to conserve their energy by minimizing the time spent in regret or complaint. Every event is a lesson to them, every person a teacher."
author = "Marilyn Ferguson"
