[[quotes]]
quote = "I believe in luck: how else can you explain the success of those you dislike?"
author = "Jean Cocteau"

[[quotes]]
quote = "We learned about honesty and integrity - that the truth matters... that you don't take shortcuts or play by your own set of rules... and success doesn't count unless you earn it fair and square."
author = "Michelle Obama"

[[quotes]]
quote = "Motivation is the art of getting people to do what you want them to do because they want to do it."
author = "Dwight D. Eisenhower"

[[quotes]]
quote = "I do not think that there is any other quality so essential to success of any kind as the quality of perseverance. It overcomes almost everything, even nature."
author = "John D. Rockefeller"

[[quotes]]
quote = "To have success in your professional life is not so hard. To succeed as a man is more difficult."
author = "Yann Arthus-Bertrand"

[[quotes]]
quote = "A little more persistence, a little more effort, and what seemed hopeless failure may turn to glorious success."
author = "Elbert Hubbard"

[[quotes]]
quote = "Every video I've made has an inspirational message behind it. Since day one, I thought, 'Okay, I want my audience to be, like, Disney members.' So if that's the case, I have to keep everything rated G."
author = "Michelle Phan"

[[quotes]]
quote = "When you fail you learn from the mistakes you made and it motivates you to work even harder."
author = "Natalie Gulbis"

[[quotes]]
quote = "Success is the space one occupies in the newspaper. Success is one day's insolence."
author = "Elias Canetti"

[[quotes]]
quote = "I am not afraid... I was born to do this."
author = "Joan of Arc"

[[quotes]]
quote = "I think that's a great opportunity, to pick a script where you can build up a good skill. I think the main thing I look for when I look at scripts is if it's inspirational. If it's something that teenagers can relate to. And is it something that the audience is going to get something out of. If not, then it's really not worth doing."
author = "Carly Schroeder"
