[[quotes]]
quote = "Refuse to accept the belief that your professional relevance, career success or financial security turns on the next update on the latest technology. Sometimes it's good to put the paddle down and just let the canoe glide."
author = "Simon Mainwaring"

[[quotes]]
quote = "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome."
author = "Booker T. Washington"

[[quotes]]
quote = "The more we do, the more we can do."
author = "William Hazlitt"

[[quotes]]
quote = "If you have no critics you'll likely have no success."
author = "Malcolm X"

[[quotes]]
quote = "Teachers are always trying to inspire people to do better, to learn, to grow. That's what we do, and we're proud of the success we've had here doing that, and it's something we'll certainly continue to do."
author = "Nick Saban"

[[quotes]]
quote = "People need to realise what real happiness and success is, because success as an actor is fleeting. You can be up there one day and gone the next."
author = "Chuck Norris"

[[quotes]]
quote = "Commitment, belief and positive attitude are all important if you're going to be a success, whether you're in sports, in business or, as in my case, anthropology."
author = "Donald Johanson"

[[quotes]]
quote = "You can never quit. Winners never quit, and quitters never win."
author = "Ted Turner"

[[quotes]]
quote = "Great leaders understand that historical success tends to produce stable and inwardly focused organizations, and these outfits, in turn, reinforce a feeling of contentment with the status quo."
author = "John P. Kotter"

[[quotes]]
quote = "Consult not your fears but your hopes and your dreams. Think not about your frustrations, but about your unfulfilled potential. Concern yourself not with what you tried and failed in, but with what it is still possible for you to do."
author = "Pope John XXIII"

[[quotes]]
quote = "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful."
author = "Albert Schweitzer"
