[[quotes]]
quote = "Successful entrepreneurs find the balance between listening to their inner voice and staying persistent in driving for success - because sometimes success is waiting right across from the transitional bump that's disguised as failure."
author = "Naveen Jain"

[[quotes]]
quote = "I knew, regardless of anything else, singing in front of an orchestra was going to be inspirational. It would feed me."
author = "George Michael"

[[quotes]]
quote = "No man ever achieved worth-while success who did not, at one time or other, find himself with at least one foot hanging well over the brink of failure."
author = "Napoleon Hill"

[[quotes]]
quote = "Great hopes make great men."
author = "Thomas Fuller"

[[quotes]]
quote = "I used to make up stuff in my bio all the time, that I used to be a professional ice-skater and stuff like that. I found it so inspirational. Why not make myself cooler than I am?"
author = "Stephen Colbert"

[[quotes]]
quote = "Let every dawn be to you as the beginning of life, and every setting sun be to you as its close."
author = "John Ruskin"

[[quotes]]
quote = "There are people out there who hate me and who say I'm arrogant, vain, and whatever. That's all part of my success. I am made to be the best."
author = "Cristiano Ronaldo"

[[quotes]]
quote = "Be kind whenever possible. It is always possible."
author = "Dalai Lama"

[[quotes]]
quote = "Only the educated are free."
author = "Epictetus"

[[quotes]]
quote = "Nothing makes one feel so strong as a call for help."
author = "Pope Paul VI"

[[quotes]]
quote = "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds."
author = "Orison Swett Marden"
