[[quotes]]
quote = "Success is not the absence of failure; it's the persistence through failure."
author = "Aisha Tyler"

[[quotes]]
quote = "An empowered organisation is one in which individuals have the knowledge, skill, desire, and opportunity to personally succeed in a way that leads to collective organisational success."
author = "Stephen Covey"

[[quotes]]
quote = "Success is not greedy, as people think, but insignificant. That is why it satisfies nobody."
author = "Lucius Annaeus Seneca"

[[quotes]]
quote = "The secret of success is learning how to use pain and pleasure instead of having pain and pleasure use you. If you do that, you're in control of your life. If you don't, life controls you."
author = "Tony Robbins"

[[quotes]]
quote = "There is no success without hardship."
author = "Sophocles"

[[quotes]]
quote = "I came to America with a dream and I made it. The dream became reality. America is built for success."
author = "Jean-Claude Van Damme"

[[quotes]]
quote = "The real secret of success is enthusiasm."
author = "Walter Chrysler"

[[quotes]]
quote = "The secret of your success is determined by your daily agenda."
author = "John C. Maxwell"

[[quotes]]
quote = "It's the price of success: people start to think you're omnipotent."
author = "Ben Bernanke"

[[quotes]]
quote = "Coming together is a beginning; keeping together is progress; working together is success."
author = "Henry Ford"

[[quotes]]
quote = "We need to accept that we won't always make the right decisions, that we'll screw up royally sometimes - understanding that failure is not the opposite of success, it's part of success."
author = "Arianna Huffington"
