[[quotes]]
quote = "Always bear in mind that your own resolution to succeed is more important than any other."
author = "Abraham Lincoln"

[[quotes]]
quote = "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time"
author = "Thomas Edison"

[[quotes]]
quote = "Don't go around saying the world owes you a living. The world owes you nothing. It was here first"
author = "Mark Twain"

[[quotes]]
quote = "We keep moving forward, opening new doors, and doing new things, because we're curious and curiosity keeps leading us down new paths"
author = "Walt Disney"

[[quotes]]
quote = "Nothing exterior to me will ever take command of me."
author = "Walt Whitman"

[[quotes]]
quote = "Nothing is impossible to him who will try."
author = "Alexander The Great"

[[quotes]]
quote = "If there are no struggles, there is no progress."
author = "Frederick Douglas"

[[quotes]]
quote = "We are what we repeatedly do. Excellence, then, is not an act, but a habit."
author = "Aristotle"

[[quotes]]
quote = "If you want to achieve greatness stop asking for permission."
author = "Unknown"

[[quotes]]
quote = "Things work out best for those who make the best of how things work out."
author = "John Wooden"

[[quotes]]
quote = "To live a creative life, we must lose our fear of being wrong."
author = "Unknown"
