[[quotes]]
quote = "I never expected any sort of success with 'Mockingbird'... I sort of hoped someone would like it enough to give me encouragement."
author = "Harper Lee"

[[quotes]]
quote = "The harder the conflict, the more glorious the triumph."
author = "Thomas Paine"

[[quotes]]
quote = "Success is following the pattern of life one enjoys most."
author = "Al Capp"

[[quotes]]
quote = "Taxation is the price we pay for failing to build a civilized society. The higher the tax level, the greater the failure. A centrally planned totalitarian state represents a complete defeat for the civilized world, while a totally voluntary society represents its ultimate success."
author = "Mark Skousen"

[[quotes]]
quote = "Your present circumstances don't determine where you can go; they merely determine where you start."
author = "Nido Qubein"

[[quotes]]
quote = "Quality is not an act, it is a habit."
author = "Aristotle"

[[quotes]]
quote = "Time is the most precious element of human existence. The successful person knows how to put energy into time and how to draw success from time."
author = "Denis Waitley"

[[quotes]]
quote = "It's cool to have critical success because it's always nice for your peers to say, 'Good job.' But who cares about them?"
author = "Zac Hanson"

[[quotes]]
quote = "Lord, grant that I may always desire more than I can accomplish."
author = "Michelangelo"

[[quotes]]
quote = "Nothing is impossible, the word itself says 'I'm possible'!"
author = "Audrey Hepburn"

[[quotes]]
quote = "Act like you expect to get into the end zone."
author = "Christopher Morley"
