[[quotes]]
quote = "Real success is finding you lifework in the work that you love."
author = "David McCullough"

[[quotes]]
quote = "We aim above the mark to hit the mark."
author = "Ralph Waldo Emerson"

[[quotes]]
quote = "Silence is the last thing the world will ever hear from me."
author = "Marlee Matlin"

[[quotes]]
quote = "Formal education will make you a living; self-education will make you a fortune."
author = "Jim Rohn"

[[quotes]]
quote = "I was obliged to be industrious. Whoever is equally industrious will succeed equally well."
author = "Johann Sebastian Bach"

[[quotes]]
quote = "The only place success comes before work is in the dictionary."
author = "Vince Lombardi"

[[quotes]]
quote = "A good plan violently executed now is better than a perfect plan executed next week."
author = "George S. Patton"

[[quotes]]
quote = "I think that my biggest attribute to any success that I have had is hard work. There really is no substitute for working hard."
author = "Maria Bartiromo"

[[quotes]]
quote = "Part of being a man is learning to take responsibility for your successes and for your failures. You can't go blaming others or being jealous. Seeing somebody else's success as your failure is a cancerous way to live."
author = "Kevin Bacon"

[[quotes]]
quote = "On the recollection of so many and great favours and blessings, I now, with a high sense of gratitude, presume to offer up my sincere thanks to the Almighty, the Creator and Preserver."
author = "William Bartram"

[[quotes]]
quote = "Failure is success if we learn from it."
author = "Malcolm Forbes"
