[[quotes]]
quote = "Good planning is important. I've also regarded a sense of humor as one of the most important things on a big expedition. When you're in a difficult or dangerous situation, or when you're depressed about the chances of success, someone who can make you laugh eases the tension."
author = "Edmund Hillary"

[[quotes]]
quote = "The one thing that makes me feel super lucky about my financial success is that I have a housekeeper."
author = "Gwen Stefani"

[[quotes]]
quote = "Every man's life is a fairy tale written by God's fingers."
author = "Hans Christian Andersen"

[[quotes]]
quote = "I always envisioned myself being a rapper and being in the game and having success, but you never know what it feels like or how you're going to be when you're there."
author = "Wiz Khalifa"

[[quotes]]
quote = "The ladder of success is best climbed by stepping on the rungs of opportunity."
author = "Ayn Rand"

[[quotes]]
quote = "Fear comes in two packages fear of failure, and sometimes, fear of success."
author = "Tom Kite"

[[quotes]]
quote = "A strong, positive self-image is the best possible preparation for success."
author = "Joyce Brothers"

[[quotes]]
quote = "Success has a simple formula: do your best, and people may like it."
author = "Sam Ewing"

[[quotes]]
quote = "You look at the tremendous success of Facebook. To my mind there is not a lot of commerce going on in these social networking sites. eBay is a community anchored in commerce. It is a commerce site that built a community around it. What has not been proven is if the reverse can happen and people will go to community sites to do commerce."
author = "Meg Whitman"

[[quotes]]
quote = "If you fell down yesterday, stand up today."
author = "H. G. Wells"

[[quotes]]
quote = "When it comes to success, there are no shortcuts."
author = "Bo Bennett"
