[[quotes]]
quote = "Belief in oneself is one of the most important bricks in building any successful venture."
author = "Lydia M. Child"

[[quotes]]
quote = "There is no substitute for victory."
author = "Douglas MacArthur"

[[quotes]]
quote = "Success is doing ordinary things extraordinarily well."
author = "Jim Rohn"

[[quotes]]
quote = "A will finds a way."
author = "Orison Swett Marden"

[[quotes]]
quote = "Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success."
author = "Swami Vivekananda"

[[quotes]]
quote = "Have regular hours for work and play; make each day both useful and pleasant, and prove that you understand the worth of time by employing it well. Then youth will be delightful, old age will bring few regrets, and life will become a beautiful success."
author = "Louisa May Alcott"

[[quotes]]
quote = "The path to success is to take massive, determined action."
author = "Tony Robbins"

[[quotes]]
quote = "There's a lot of blood, sweat, and guts between dreams and success."
author = "Paul Bryant"

[[quotes]]
quote = "The secret to success is good leadership, and good leadership is all about making the lives of your team members or workers better."
author = "Tony Dungy"

[[quotes]]
quote = "If you've got a talent, protect it."
author = "Jim Carrey"

[[quotes]]
quote = "One measure of your success will be the degree to which you build up others who work with you. While building up others, you will build up yourself."
author = "James E. Casey"
