[[quotes]]
quote = "True leadership lies in guiding others to success. In ensuring that everyone is performing at their best, doing the work they are pledged to do and doing it well."
author = "Bill Owens"

[[quotes]]
quote = "You've got to eat while you dream. You've got to deliver on short-range commitments, while you develop a long-range strategy and vision and implement it. The success of doing both. Walking and chewing gum if you will. Getting it done in the short-range, and delivering a long-range plan, and executing on that."
author = "Jack Welch"

[[quotes]]
quote = "Those who have succeeded at anything and don't mention luck are kidding themselves."
author = "Larry King"

[[quotes]]
quote = "I'm an addict, I'm addicted to success. Thankfully, there's no rehab for success."
author = "Lil Wayne"

[[quotes]]
quote = "We are constantly emphasizing to people that they need to address anything that affects flight safety or mission success - many pathways to do that. We need to understand better what may be preventing people from using those pathways."
author = "Ellen Ochoa"

[[quotes]]
quote = "It is not the going out of port, but the coming in, that determines the success of a voyage."
author = "Henry Ward Beecher"

[[quotes]]
quote = "I worked half my life to be an overnight success, and still it took me by surprise."
author = "Jessica Savitch"

[[quotes]]
quote = "I believe that one defines oneself by reinvention. To not be like your parents. To not be like your friends. To be yourself. To cut yourself out of stone."
author = "Henry Rollins"

[[quotes]]
quote = "There is no passion to be found playing small - in settling for a life that is less than the one you are capable of living."
author = "Nelson Mandela"

[[quotes]]
quote = "The people who influence you are the people who believe in you."
author = "Henry Drummond"

[[quotes]]
quote = "Carry on any enterprise as if all future success depended on it."
author = "Cardinal Richelieu"
