[[quotes]]
quote = "Too low they build, who build beneath the stars."
author = "Edward Young"

[[quotes]]
quote = "I think the success that I have is due to hard work and destiny. It is important to stay grounded and not take things for granted."
author = "Alia Bhatt"

[[quotes]]
quote = "Success makes so many people hate you. I wish it wasn't that way. It would be wonderful to enjoy success without seeing envy in the eyes of those around you."
author = "Marilyn Monroe"

[[quotes]]
quote = "Success is a journey, not a destination."
author = "Ben Sweetland"

[[quotes]]
quote = "Lee's great gifts are teaching and inspirational guidance, not administration and management."
author = "Cheryl Crawford"

[[quotes]]
quote = "Most of us have far more courage than we ever dreamed we possessed."
author = "Dale Carnegie"

[[quotes]]
quote = "Some of the best lessons we ever learn are learned from past mistakes. The error of the past is the wisdom and success of the future."
author = "Dale Turner"

[[quotes]]
quote = "You grow up a bit damaged or broken then you have some success but you don't know how to feel good about the work you're doing or the life you're leading."
author = "Johnny Depp"

[[quotes]]
quote = "The most effective way to do it, is to do it."
author = "Amelia Earhart"

[[quotes]]
quote = "I'm not here to impose Sharia law, and I'm not here to have a message about disability being inspirational - I'm here to make people laugh. But when I can layer things and make people not only laugh but question, make people not only laugh but be offended... I have to do that."
author = "Maysoon Zayid"

[[quotes]]
quote = "Success represents the 1% of your work which results from the 99% that is called failure."
author = "Soichiro Honda"
