[[quotes]]
quote = "Success is sweet and sweeter if long delayed and gotten through many struggles and defeats."
author = "Amos Bronson Alcott"

[[quotes]]
quote = "As an actor there's a lot of scrutiny and, even when you've had success, it becomes about sustaining that success. A friend of mine described it as a peakless mountain. Even for De Niro there's Pacino and for Pacino there's De Niro."
author = "Eddie Redmayne"

[[quotes]]
quote = "And now, this is the sweetest and most glorious day that ever my eyes did see."
author = "Donald Cargill"

[[quotes]]
quote = "Traveling around the country, meeting fans and hearing their stories in person and on my radio show has reenergized my commitment to creating honest and inspirational content that not only serves my own creative purposes but can help and touch others as well."
author = "Nikki Sixx"

[[quotes]]
quote = "Success is not two cars or a swimming pool. It's the approval of your peers."
author = "Peter Finch"

[[quotes]]
quote = "Many are called but few get up."
author = "Oliver Herford"

[[quotes]]
quote = "Whatever you do to gain success, you have to hang in there and hope good things happen. Always think positive."
author = "Don Rickles"

[[quotes]]
quote = "A concerted effort to preserve our heritage is a vital link to our cultural, educational, aesthetic, inspirational, and economic legacies - all of the things that quite literally make us who we are."
author = "Steve Berry"

[[quotes]]
quote = "Your heart is full of fertile seeds, waiting to sprout."
author = "Morihei Ueshiba"

[[quotes]]
quote = "The success I have achieved in bodybuilding, motion pictures, and business would not have been possible without the generosity of the American people and the freedom here to pursue your dreams."
author = "Arnold Schwarzenegger"

[[quotes]]
quote = "Of all human activities, man's listening to God is the supreme act of his reasoning and will."
author = "Pope Paul VI"
