[[quotes]]
quote = "Through perseverance many people win success out of what seemed destined to be certain failure."
author = "Benjamin Disraeli"

[[quotes]]
quote = "There's a way to do it better - find it."
author = "Thomas A. Edison"

[[quotes]]
quote = "Desire is the key to motivation, but it's determination and commitment to an unrelenting pursuit of your goal - a commitment to excellence - that will enable you to attain the success you seek."
author = "Mario Andretti"

[[quotes]]
quote = "The key to success is to focus our conscious mind on things we desire not things we fear."
author = "Brian Tracy"

[[quotes]]
quote = "Although he's no longer with us, Steve Jobs is still inspirational to me, as he managed to find the balance between right brain/left-brain thinking that is crucial to building a creative technology business."
author = "Imran Amed"

[[quotes]]
quote = "When we seek to discover the best in others, we somehow bring out the best in ourselves."
author = "William Arthur Ward"

[[quotes]]
quote = "I can, therefore I am."
author = "Simone Weil"

[[quotes]]
quote = "I'm going to write a book, continue acting, continue motivational speaking and just share with people who I am and what I've learned in my second chance of life and pass it on to people in their first chance of life."
author = "J. R. Martinez"

[[quotes]]
quote = "The foundation stones for a balanced success are honesty, character, integrity, faith, love and loyalty."
author = "Zig Ziglar"

[[quotes]]
quote = "In this world it is not what we take up, but what we give up, that makes us rich."
author = "Henry Ward Beecher"

[[quotes]]
quote = "When you're working hard and doing all you can to achieve your goals, anything that can give you an edge is powerful and will streamline your path to success."
author = "Travis Bradberry"
