[[quotes]]
quote = "The most successful men in the end are those whose success is the result of steady accretion."
author = "Alexander Graham Bell"

[[quotes]]
quote = "And when I breathed, my breath was lightning."
author = "Black Elk"

[[quotes]]
quote = "Business gives you a massive high. Doing a great deal, coming up with an inspirational solution... It's very addictive. But it doesn't last long. In isolation, it's a bit sterile. It doesn't reward the soul."
author = "John Caudwell"

[[quotes]]
quote = "Give light and people will find the way."
author = "Ella Baker"

[[quotes]]
quote = "There is a loftier ambition than merely to stand high in the world. It is to stoop down and lift mankind a little higher."
author = "Henry Van Dyke"

[[quotes]]
quote = "I look up to a strong woman; maybe that's why I fell for Gaga. She works incredibly hard and is very strong and inspirational like Mom, with a great work ethic."
author = "Taylor Kinney"

[[quotes]]
quote = "Man never made any material as resilient as the human spirit."
author = "Bernard Williams"

[[quotes]]
quote = "The success combination in business is: Do what you do better... and: do more of what you do."
author = "David Joseph Schwartz"

[[quotes]]
quote = "Success is not the key to happiness. Happiness is the key to success. If you love what you do, you'll be successful."
author = "Tyga"

[[quotes]]
quote = "Success is that old ABC - ability, breaks, and courage."
author = "Charles Luckman"

[[quotes]]
quote = "That man is a success who has lived well, laughed often and loved much."
author = "Robert Louis Stevenson"
