[[quotes]]
quote = "Let us make our future now, and let us make our dreams tomorrow's reality."
author = "Malala Yousafzai"

[[quotes]]
quote = "The hardest thing to find in life is balance - especially, the more success you have, the more you look to the other side of the gate."
author = "Celine Dion"

[[quotes]]
quote = "I do like alternative rock and rap, but as far as inspirational, then I go full-on orchestra. It fills up your entire being."
author = "Osric Chau"

[[quotes]]
quote = "Such a faith would be fatal to my reason, to my liberty, and even to the success of my undertakings; it would immediately transform me into a stupid slave, an instrument of the will and interests of others."
author = "Mikhail Bakunin"

[[quotes]]
quote = "When Bill Clinton ran in '92, and I listened to him, and I had of course known of his record from Arkansas, I found him extraordinarily inspirational, and I voted Democratic."
author = "Wesley Clark"

[[quotes]]
quote = "I've a great family, two children to take care of. Then, of course, I do commentary for TV. I do speak about various women's issues around the world - like LGBT, motivational speeches. I have a lot on my plate right now. But eventually, yes, I would like to pass on the knowledge and something that I would like to do."
author = "Martina Navratilova"

[[quotes]]
quote = "However things may seem, no evil thing is success and no good thing is failure."
author = "Henry Wadsworth Longfellow"

[[quotes]]
quote = "In order to succeed, your desire for success should be greater than your fear of failure."
author = "Bill Cosby"

[[quotes]]
quote = "Luxury is the wolf at the door and its fangs are the vanities and conceits germinated by success. When an artist learns this, he knows where the danger is."
author = "Tennessee Williams"

[[quotes]]
quote = "Some say I'm an overnight success. Well, that was a very long night that lasted about 10 years."
author = "Lisa Morton"

[[quotes]]
quote = "The season of failure is the best time for sowing the seeds of success."
author = "Paramahansa Yogananda"
