[[quotes]]
quote = "If you are not willing to risk the usual you will have to settle for the ordinary."
author = "Jim Rohn"

[[quotes]]
quote = "Trust because you are willing to accept the risk, not because it's safe or certain."
author = "Unknown"

[[quotes]]
quote = "Take up one idea. Make that one idea your life--think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success."
author = "Swami Vivekananda"

[[quotes]]
quote = "All our dreams can come true if we have the courage to pursue them."
author = "Walt Disney"

[[quotes]]
quote = "Good things come to people who wait, but better things come to those who go out and get them."
author = "Unknown"

[[quotes]]
quote = "If you do what you always did, you will get what you always got."
author = "Unknown"

[[quotes]]
quote = "Success is walking from failure to failure with no loss of enthusiasm."
author = "Winston Churchill"

[[quotes]]
quote = "Just when the caterpillar thought the world was ending, he turned into a butterfly."
author = "Proverb"

[[quotes]]
quote = "Successful entrepreneurs are givers and not takers of positive energy."
author = "Unknown"

[[quotes]]
quote = "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them."
author = "Vaibhav Shah"

[[quotes]]
quote = "Opportunities don't happen, you create them."
author = "Chris Grosser"
