[[quotes]]
quote = "Success is not in never failing, but rising everytime you fall!"
author = "Jonathan Taylor Thomas"

[[quotes]]
quote = "The NFL is a performance-based business, so you should have to perform to earn some of your money. At the same time, I realize that my success isn't just because of what I do out there."
author = "Colin Kaepernick"

[[quotes]]
quote = "After a storm comes a calm."
author = "Matthew Henry"

[[quotes]]
quote = "Failure is not an option. Everyone has to succeed."
author = "Arnold Schwarzenegger"

[[quotes]]
quote = "It is so inspirational, to see that in the world of Westeros, men are answering to women, and they are a force to be reckoned with. It's empowering, and it's inspirational as well, because you're just like, 'This is great!'"
author = "Rose Leslie"

[[quotes]]
quote = "I've been very lucky to have achieved a lot of the things that I dreamt of achieving as a young man. But, at the end of the day - and I truly believe this - it is not about achieving great wealth or success. Because they don't bring happiness, ultimately."
author = "Leonardo DiCaprio"

[[quotes]]
quote = "There are people who can achieve huge success in life, while adding a bit of fun and a splash of colour to this increasingly grey world."
author = "Peter James"

[[quotes]]
quote = "Success is finding satisfaction in giving a little more than you take."
author = "Christopher Reeve"

[[quotes]]
quote = "We know what we are, but know not what we may be."
author = "William Shakespeare"

[[quotes]]
quote = "For marriage to be a success, every woman and every man should have her and his own bathroom. The end."
author = "Catherine Zeta-Jones"

[[quotes]]
quote = "I have an idea of who I want to be, I have a vision of my own success."
author = "Wiz Khalifa"
