[[quotes]]
quote = "Success follows those adept at preserving the substance of the past by clothing it in the forms of the future."
author = "Dee Hock"

[[quotes]]
quote = "The secret of my success is my hairspray."
author = "Richard Gere"

[[quotes]]
quote = "Whatever you want in life, other people are going to want it too. Believe in yourself enough to accept the idea that you have an equal right to it."
author = "Diane Sawyer"

[[quotes]]
quote = "Beside every great success are the seeds of enormous failure. In every failure, there's the opportunity seeds of great success. They're not miles apart. So if they're that close together, and if you're really working, you're always gonna have that likelihood that something's not going to work."
author = "Peter Guber"

[[quotes]]
quote = "People fall forward to success."
author = "Mary Kay Ash"

[[quotes]]
quote = "I wonder how many times people give up just before a breakthrough - when they are on the very brink of success."
author = "Joyce Meyer"

[[quotes]]
quote = "I wish I could just go tell all the young women I work with, all these fabulous women, 'Believe in yourself and negotiate for yourself. Own your own success.' I wish I could tell that to my daughter. But it's not that simple."
author = "Sheryl Sandberg"

[[quotes]]
quote = "Setting goals is the first step in turning the invisible into the visible."
author = "Tony Robbins"

[[quotes]]
quote = "As I've progressed in my career, I've come to appreciate - and really value - the other attributes that define a company's success beyond the P&L: great leadership, long-term financial strength, ethical business practices, evolving business strategies, sound governance, powerful brands, values-based decision-making."
author = "Ursula Burns"

[[quotes]]
quote = "Winning isn't everything, it's the only thing."
author = "Vince Lombardi"

[[quotes]]
quote = "Success or failure in business is caused more by the mental attitude even than by mental capacities."
author = "Walter Scott"
