[[quotes]]
quote = "'Do What You Gotta Do' is a positive, inspirational song that says no matter what it is; whether you're up against challenges or trying to get your dreams and aspirations met, you should do what whatever you have to do shy of killing yourself or someone else."
author = "Angie Stone"

[[quotes]]
quote = "If you want to achieve things in life, you've just got to do them, and if you're talented and smart, you'll succeed."
author = "Juliana Hatfield"

[[quotes]]
quote = "Don't aim for success if you want it; just do what you love and believe in, and it will come naturally."
author = "David Frost"

[[quotes]]
quote = "The secret of success is constancy to purpose."
author = "Benjamin Disraeli"

[[quotes]]
quote = "I've lost count of the number of times that I've been approached by strangers wanting to tell me that they think I'm brave or inspirational, and this was long before my work had any kind of public profile."
author = "Stella Young"

[[quotes]]
quote = "Show me your hands. Do they have scars from giving? Show me your feet. Are they wounded in service? Show me your heart. Have you left a place for divine love?"
author = "Fulton J. Sheen"

[[quotes]]
quote = "You must take action now that will move you towards your goals. Develop a sense of urgency in your life."
author = "H. Jackson Brown, Jr."

[[quotes]]
quote = "Do the one thing you think you cannot do. Fail at it. Try again. Do better the second time. The only people who never tumble are those who never mount the high wire. This is your moment. Own it."
author = "Oprah Winfrey"

[[quotes]]
quote = "Many individuals are doing what they can. But real success can only come if there is a change in our societies and in our economics and in our politics."
author = "David Attenborough"

[[quotes]]
quote = "Success cannot come from standstill men. Methods change and men must change with them."
author = "James Cash Penney"

[[quotes]]
quote = "Success is getting what you want. Happiness is liking what you get."
author = "H. Jackson Brown, Jr."
