[[quotes]]
quote = "The difference between us and them, between you and success, is not that you never fail, but it's how you recover from those failures - is that you keep getting up time and time again. You figure out what you did wrong, and then you make it right. I say that to my kids every day."
author = "Michelle Obama"

[[quotes]]
quote = "Like success, failure is many things to many people. With Positive Mental Attitude, failure is a learning experience, a rung on the ladder, a plateau at which to get your thoughts in order and prepare to try again."
author = "W. Clement Stone"

[[quotes]]
quote = "Do not wait; the time will never be 'just right.' Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along."
author = "George Herbert"

[[quotes]]
quote = "I've been absolutely terrified every moment of my life - and I've never let it keep me from doing a single thing I wanted to do."
author = "Georgia O'Keeffe"

[[quotes]]
quote = "When one must, one can."
author = "Charlotte Whitton"

[[quotes]]
quote = "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'"
author = "Muhammad Ali"

[[quotes]]
quote = "I don't think 'Cocktail' was a perfect critical success, but it touched a vein in our culture."
author = "Elisabeth Shue"

[[quotes]]
quote = "Think little goals and expect little achievements. Think big goals and win big success."
author = "David Joseph Schwartz"

[[quotes]]
quote = "So I wanted to sing inspirational music, and that's exactly how I approached it - only the words have been changed to declare my relationship with God."
author = "Smokey Robinson"

[[quotes]]
quote = "Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared."
author = "Buddha"

[[quotes]]
quote = "Every charitable act is a stepping stone toward heaven."
author = "Henry Ward Beecher"
