[[quotes]]
quote = "I must admit that I personally measure success in terms of the contributions an individual makes to her or his fellow human beings."
author = "Margaret Mead"

[[quotes]]
quote = "More than half of people who leave their jobs do so because of their relationship with their boss. Smart companies make certain their managers know how to balance being professional with being human. These are the bosses who celebrate an employee's success, empathize with those going through hard times, and challenge people, even when it hurts."
author = "Travis Bradberry"

[[quotes]]
quote = "The common idea that success spoils people by making them vain, egotistic and self-complacent is erroneous; on the contrary it makes them, for the most part, humble, tolerant and kind."
author = "W. Somerset Maugham"

[[quotes]]
quote = "The success of a production depends on the attention paid to detail."
author = "David O. Selznick"

[[quotes]]
quote = "When a small child, I thought that success spelled happiness. I was wrong, happiness is like a butterfly which appears and delights us for one brief moment, but soon flits away."
author = "Anna Pavlova"

[[quotes]]
quote = "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand."
author = "Vince Lombardi"

[[quotes]]
quote = "To follow, without halt, one aim: that's the secret of success."
author = "Anna Pavlova"

[[quotes]]
quote = "I would say I'm an inspirational guidelines book. You can take my life story or scenarios or songs and relate to them and apply them to your everyday life."
author = "Chris Brown"

[[quotes]]
quote = "You cannot climb the ladder of success dressed in the costume of failure."
author = "Zig Ziglar"

[[quotes]]
quote = "Greatness is so often a courteous synonym for great success."
author = "Philip Guedalla"

[[quotes]]
quote = "No matter how much success you're having, you can't continue working together if you can't communicate."
author = "Matt Cameron"
