[[quotes]]
quote = "Pray that success will not come any faster than you are able to endure it."
author = "Elbert Hubbard"

[[quotes]]
quote = "I am never without my lyric book. If anything inspirational happens, I have it there so nothing's forgotten."
author = "Gabrielle Aplin"

[[quotes]]
quote = "In sports teams, apart from talk of sporting prowess and the imparting of inspirational thought, an extraordinary amount of time is spent discussing, and flaunting, material possessions."
author = "Harsha Bhogle"

[[quotes]]
quote = "I have had all of the disadvantages required for success."
author = "Larry Ellison"

[[quotes]]
quote = "You will never win if you never begin."
author = "Helen Rowland"

[[quotes]]
quote = "I sort of understood that when I first started: that you shouldn't repeat a success. Very often you're going to, and maybe the first time you do, it works. And you love it. But then you're trapped."
author = "Jack Nicholson"

[[quotes]]
quote = "People are the key to success or extraordinary success."
author = "Azim Premji"

[[quotes]]
quote = "There's no abiding success without commitment."
author = "Tony Robbins"

[[quotes]]
quote = "Check your ego at the door. The ego can be the great success inhibitor. It can kill opportunities, and it can kill success."
author = "Dwayne Johnson"

[[quotes]]
quote = "In fact, I wouldn't really call this a Gospel album, I call it more an inspirational album."
author = "Smokey Robinson"

[[quotes]]
quote = "Don't fight the problem, decide it."
author = "George C. Marshall"
