[[quotes]]
quote = "True happiness involves the full use of one's power and talents."
author = "John W. Gardner"

[[quotes]]
quote = "I don't believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be."
author = "Ken Venturi"

[[quotes]]
quote = "Seventy percent of success in life is showing up."
author = "Woody Allen"

[[quotes]]
quote = "Don't judge each day by the harvest you reap but by the seeds that you plant."
author = "Robert Louis Stevenson"

[[quotes]]
quote = "The ideal life is in our blood and never will be still."
author = "Phillips Brooks"

[[quotes]]
quote = "There are no secrets to success. It is the result of preparation, hard work, and learning from failure."
author = "Colin Powell"

[[quotes]]
quote = "The reward of art is not fame or success but intoxication: that is why so many bad artists are unable to give it up."
author = "Jean Cocteau"

[[quotes]]
quote = "We've had great successes, but our future is not about our past success. It's going to be about whether we will invent things that are really going to drive our future."
author = "Satya Nadella"

[[quotes]]
quote = "Determine never to be idle. No person will have occasion to complain of the want of time who never loses any. It is wonderful how much may be done if we are always doing."
author = "Thomas Jefferson"

[[quotes]]
quote = "The greatest sign of success for a teacher... is to be able to say, 'The children are now working as if I did not exist.'"
author = "Maria Montessori"

[[quotes]]
quote = "He has achieved success who has worked well, laughed often, and loved much."
author = "Elbert Hubbard"
