[[quotes]]
quote = "I congratulate you, my brave countrymen and fellow soldiers, on the spirit and success with which you have executed this important part of our enterprise."
author = "James Wolfe"

[[quotes]]
quote = "I do a lot of inspirational talks for kids, to motivate them to change their lives and give them hope."
author = "Adam Beach"

[[quotes]]
quote = "An artist cannot fail; it is a success to be one."
author = "Charles Horton Cooley"

[[quotes]]
quote = "The more defects a man may have, the older he is, the less lovable, the more resounding his success."
author = "Marquis de Sade"

[[quotes]]
quote = "If you don't ask, you don't get."
author = "Stevie Wonder"

[[quotes]]
quote = "Success doesn't necessarily come from breakthrough innovation but from flawless execution. A great strategy alone won't win a game or a battle; the win comes from basic blocking and tackling."
author = "Naveen Jain"

[[quotes]]
quote = "Success is nothing if you don't have the right people to share it with; you're just gonna end up lonely."
author = "Selena Gomez"

[[quotes]]
quote = "What makes the desert beautiful is that somewhere it hides a well."
author = "Antoine de Saint-Exupery"

[[quotes]]
quote = "People think that at the top there isn't much room. They tend to think of it as an Everest. My message is that there is tons of room at the top."
author = "Margaret Thatcher"

[[quotes]]
quote = "With the success of a show, you get an opportunity to call attention to things that you believe in."
author = "Bradley Whitford"

[[quotes]]
quote = "I pull a lot of the stuff that I play off the rhythm tracks - and Keith Richards has been one of the main contributors to my inspirational playing."
author = "Bobby Keys"
