[[quotes]]
quote = "Hope is but the dream of those who wake."
author = "Matthew Prior"

[[quotes]]
quote = "Many of life's failures are people who did not realize how close they were to success when they gave up."
author = "Thomas A. Edison"

[[quotes]]
quote = "You don't have to be a genius or a visionary or even a college graduate to be successful. You just need a framework and a dream."
author = "Michael Dell"

[[quotes]]
quote = "Sometimes I worry about being a success in a mediocre world."
author = "Lily Tomlin"

[[quotes]]
quote = "You can't expect to hit the jackpot if you don't put a few nickels in the machine."
author = "Flip Wilson"

[[quotes]]
quote = "For an actress to be a success, she must have the face of a Venus, the brains of a Minerva, the grace of Terpsichore, the memory of a MaCaulay, the figure of Juno, and the hide of a rhinoceros."
author = "Ethel Barrymore"

[[quotes]]
quote = "The way a team plays as a whole determines its success."
author = "George Herman"

[[quotes]]
quote = "I have always been pushed by the negative. The apparent failure of a play sends me back to my typewriter that very night, before the reviews are out. I am more compelled to get back to work than if I had a success."
author = "Tennessee Williams"

[[quotes]]
quote = "Oh, I would love to be a motivational speaker. I have pulled myself out of a million potholes, and I can see the potholes ahead of me. That doesn't mean that I could always do that so perfectly for my own life. I totally fall in potholes."
author = "Drew Barrymore"

[[quotes]]
quote = "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence."
author = "Helen Keller"

[[quotes]]
quote = "We do not celebrate people who have made success out of serious hard work."
author = "Iain Duncan Smith"
