[[quotes]]
quote = "I went to a motivational training course once, a course of self-discovery, and I found out after a week that my fear - it was not a fear of not being accepted - was a very violent fear of failure."
author = "Emanuel Steward"

[[quotes]]
quote = "The will to succeed is important, but what's more important is the will to prepare."
author = "Bobby Knight"

[[quotes]]
quote = "If I could offer but one helpful hint to young Hoosiers hoping to better their odds for success in life, I would simply note the importance of thoughtful reading."
author = "Richard Lugar"

[[quotes]]
quote = "We reached a high point in my opinion with the passage of the civil rights legislation and Martin Luther King's success and the crusade of others. I think we kind of breathed a sigh of relief as if we had achieved the end of racial discrimination or white supremacy."
author = "Jimmy Carter"

[[quotes]]
quote = "Happiness is the natural flower of duty."
author = "Phillips Brooks"

[[quotes]]
quote = "I wanted to do something inspirational for my children."
author = "Harvey Weinstein"

[[quotes]]
quote = "My success is not due to any personal superiority over other people."
author = "John Philip Sousa"

[[quotes]]
quote = "Success is like death. The more successful you become, the higher the houses in the hills get and the higher the fences get."
author = "Kevin Spacey"

[[quotes]]
quote = "Willpower is the key to success. Successful people strive no matter what they feel by applying their will to overcome apathy, doubt or fear."
author = "Dan Millman"

[[quotes]]
quote = "The winner's edge is not in a gifted birth, a high IQ, or in talent. The winner's edge is all in the attitude, not aptitude. Attitude is the criterion for success."
author = "Denis Waitley"

[[quotes]]
quote = "I think 'Heroes of Cosplay' will show a lot of the positive things, like how much effort it takes to make a costume. These people on the show aren't taking shortcuts. As long as that effort gets through to the viewers, we will be inspirational. Then there will be people who watch the show that want to get in and hands-on make outfits."
author = "Yaya Han"
